import test from 'node:test';
import assert from 'node:assert/strict';
import { runCalendarDiscovery,refreshCalendarDiscoveryToken,type DiscoveryWorkflowDependencies } from './calendarDiscoveryWorkflow.ts';
import {handleCalendarDiscovery} from './calendarDiscoveryBoundary.ts';
const connectionId='4d2b4b34-9f79-496b-82b0-663e71cd3b5a',workspaceId='fdce6c53-d1cb-48bc-b35a-7f57674d80f6',userId='baf67b40-2fdf-4496-9c1d-1ac1aa5e9892';
const metadata={providerAccountReference:'owner@example.test',calendars:[{providerCalendarReference:'default',displayName:'Calendar',ownerAddress:'owner@example.test',isDefault:true}]};
function fixture(overrides:Partial<DiscoveryWorkflowDependencies>={}){const calls:string[]=[];const deps:DiscoveryWorkflowDependencies={load:async()=>{calls.push('load');return{refresh_token:'old-fake',credential_reference:userId,revision:1};},refresh:async token=>{calls.push('refresh');assert.equal(token,'old-fake');return{accessToken:'fake-access',refreshToken:'new-fake'};},rotate:async(token,revision)=>{calls.push('rotate');assert.equal(token,'new-fake');assert.equal(revision,1);return{credential_reference:userId,revision:2};},discover:async token=>{calls.push('discover');assert.equal(token,'fake-access');return metadata;},save:async(result,reference,revision)=>{calls.push('save');assert.equal(result,metadata);assert.equal(reference,userId);assert.equal(revision,2);return{connection_id:connectionId,connection_status:'connected',calendar_count:1};},...overrides};return{calls,deps};}
test('rotation is durable before Graph; save uses exact revision and returns metadata only',async()=>{const f=fixture();assert.deepEqual(await runCalendarDiscovery(connectionId,f.deps),{connectionId,connectionStatus:'connected',calendarCount:1});assert.deepEqual(f.calls,['load','refresh','rotate','discover','save']);});
test('refusal at each stage stops later stages without automatic retries',async()=>{for(const stage of ['load','refresh','rotate','discover','save'] as const){let calls=0;const f=fixture({[stage]:async()=>{calls++;throw new Error('denied');}});await assert.rejects(runCalendarDiscovery(connectionId,f.deps));assert.equal(calls,1);assert.equal(f.calls.length,['load','refresh','rotate','discover','save'].indexOf(stage));}});
test('stale rotation refuses Graph',async()=>{const f=fixture({rotate:async()=>({credential_reference:userId,revision:1})});await assert.rejects(runCalendarDiscovery(connectionId,f.deps));assert.deepEqual(f.calls,['load','refresh']);});
test('refresh transport requests only calendar read scope and handles optional refresh rotation',async()=>{for(const rotated of [undefined,'rotated-fake']){let calls=0;const result=await refreshCalendarDiscoveryToken({clientId:userId,clientSecret:'fake-secret',authority:'organizations',redirectUri:'http://127.0.0.1:5180/calendar/outlook/callback'},'old-fake',async(url,init)=>{calls++;assert.equal(url,'https://login.microsoftonline.com/organizations/oauth2/v2.0/token');assert.equal(init?.redirect,'error');const body=new URLSearchParams(String(init?.body));assert.equal(body.get('grant_type'),'refresh_token');assert.equal(body.get('scope'),'offline_access https://graph.microsoft.com/Calendars.Read');return Response.json({access_token:'fake-access',token_type:'Bearer',expires_in:3600,scope:'Calendars.Read',...(rotated?{refresh_token:rotated}:{})});});assert.equal(calls,1);assert.equal(result.refreshToken,rotated??'old-fake');}});
test('write refresh requests and requires the explicitly granted calendar write scope',async()=>{const config={clientId:userId,clientSecret:'fake-secret',authority:'organizations',redirectUri:'http://127.0.0.1:5180/calendar/outlook/callback'};let calls=0;const result=await refreshCalendarDiscoveryToken(config,'old-write-fake',async(_url,init)=>{calls++;const body=new URLSearchParams(String(init?.body));assert.equal(body.get('scope'),'offline_access https://graph.microsoft.com/Calendars.ReadWrite');return Response.json({access_token:'write-access-fake',token_type:'Bearer',expires_in:3600,scope:'https://graph.microsoft.com/Calendars.ReadWrite',refresh_token:'rotated-write-fake'});},'write');assert.equal(calls,1);assert.deepEqual(result,{accessToken:'write-access-fake',refreshToken:'rotated-write-fake'});await assert.rejects(refreshCalendarDiscoveryToken(config,'old-read-fake',async()=>Response.json({access_token:'read-access-fake',token_type:'Bearer',expires_in:3600,scope:'Calendars.Read'}),'write'));});
test('authenticated boundary accepts only identifiers and timezone, denying injected token and member role',async()=>{let calls=0;const origin='http://127.0.0.1:5180';const deps={allowedOrigin:origin,getUserId:async()=>userId,canManage:async()=>true,discover:async(w:string,c:string,u:string,t:string)=>{calls++;assert.equal(w,workspaceId);assert.equal(c,connectionId);assert.equal(u,userId);assert.equal(t,'Europe/London');return{connectionId,connectionStatus:'connected' as const,calendarCount:1};}};const req=(body:unknown)=>new Request('https://example.test/discover',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json'},body:JSON.stringify(body)});const body={workspaceId,connectionId,timezone:'Europe/London'};assert.equal((await handleCalendarDiscovery(req(body),deps)).status,200);assert.equal((await handleCalendarDiscovery(req({...body,accessToken:'injected'}),deps)).status,400);assert.equal((await handleCalendarDiscovery(req(body),{...deps,canManage:async()=>false})).status,403);assert.equal(calls,1);});
