import test from 'node:test';import assert from 'node:assert/strict';
import {handleSchedulingAssignmentSave,AssignmentRefusal,type AssignmentDependencies,type AssignmentInput} from './schedulingAssignmentBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',job='44444444-4444-4444-8444-444444444444',assignment='55555555-5555-4555-8555-555555555555',requestId='66666666-6666-4666-8666-666666666666';
const origin='http://localhost:5180';
const body={workspaceId:ws,workerId:worker,jobId:job,requestId,assignmentId:null as string|null,status:'active',expectedVersion:0,expectedWorkerVersion:1,expectedJobVersion:2,expectedPatternVersion:3};
function req(value:unknown=body,headers:Record<string,string>={},method='POST'){return new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer verified','Content-Type':'application/json',...headers},body:['GET','OPTIONS'].includes(method)?undefined:JSON.stringify(value)});}
function fixture(){const calls:AssignmentInput[]=[];let auth=0;const deps:AssignmentDependencies={allowedOrigin:origin,getUserId:async()=>{auth++;return actor;},canManage:async()=>true,save:async input=>{calls.push(input);return {assignment_id:input.target_assignment_id??assignment,workspace_id:ws,worker_id:worker,job_id:job,start_at:'2026-10-08T09:00:00+00:00',end_at:'2026-10-08T10:00:00+00:00',status:input.target_status,version:input.expected_version+1,private_token:'secret'};}};return {deps,calls,auth:()=>auth};}
test('verified manager sends only scoped identifiers and exact revisions; safe no-store metadata returns',async()=>{const f=fixture(),r=await handleSchedulingAssignmentSave(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.deepEqual(f.calls[0],{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_assignment_id:null,target_worker_id:worker,target_job_id:job,target_status:'active',expected_version:0,expected_worker_version:1,expected_job_version:2,expected_pattern_version:3});assert.deepEqual(await r.json(),{assignmentId:assignment,workspaceId:ws,workerId:worker,jobId:job,startAt:'2026-10-08T09:00:00.000Z',endAt:'2026-10-08T10:00:00.000Z',status:'active',version:1});});
test('injected actor, interval, identifiers and invalid revision combinations stop before auth',async()=>{for(const patch of [{actorUserId:actor},{startAt:'2026-10-08T09:00:00Z'},{workerId:'bad'},{expectedWorkerVersion:null},{expectedJobVersion:0},{expectedPatternVersion:1.5},{expectedVersion:1},{status:'cancelled'},{assignmentId:assignment},{expectedWorkerVersion:Number.MAX_SAFE_INTEGER}]){const f=fixture();assert.equal((await handleSchedulingAssignmentSave(req({...body,...patch}),f.deps)).status,400);assert.equal(f.auth(),0);assert.equal(f.calls.length,0);}});
test('origin, method, bearer and content type never reach save',async()=>{for(const r of [req(body,{Origin:'https://foreign.test'}),req(body,{},'GET'),req(body,{Authorization:''}),req(body,{'Content-Type':'text/plain'})]){const f=fixture();assert.ok((await handleSchedulingAssignmentSave(r,f.deps)).status>=400);assert.equal(f.calls.length,0);}});
test('invalid session and denied manager role never reach save',async()=>{for(const patch of [{getUserId:async()=>null},{canManage:async()=>false}]){const f=fixture();assert.ok((await handleSchedulingAssignmentSave(req(),{...f.deps,...patch})).status>=400);assert.equal(f.calls.length,0);}});
test('preflight permits Supabase headers without authentication or save',async()=>{const f=fixture(),r=await handleSchedulingAssignmentSave(req(undefined,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.ok(r.headers.get('Access-Control-Allow-Headers')?.includes('x-client-info'));assert.equal(f.auth(),0);assert.equal(f.calls.length,0);});
test('cancellation uses saved assignment revision and no creation revisions',async()=>{const f=fixture(),cancel={...body,assignmentId:assignment,status:'cancelled',expectedVersion:1,expectedWorkerVersion:null,expectedJobVersion:null,expectedPatternVersion:null};const r=await handleSchedulingAssignmentSave(req(cancel),f.deps);assert.equal(r.status,200);assert.equal((await r.json()).version,2);assert.equal(f.calls[0].expected_worker_version,null);assert.equal((await handleSchedulingAssignmentSave(req({...cancel,expectedJobVersion:2}),f.deps)).status,400);});
test('known transactional refusal returns exact safe reason and request without retry',async()=>{let count=0;const f=fixture();f.deps.save=async()=>{count++;throw new AssignmentRefusal('overlap');};const r=await handleSchedulingAssignmentSave(req(),f.deps);assert.equal(r.status,409);assert.deepEqual(await r.json(),{status:'refused',code:'overlap',requestId});assert.equal(count,1);});
test('unknown failure and mismatched result stay uncertain and hide private details',async()=>{for(const field of ['workspace_id','worker_id','job_id','assignment_id','status','version','start_at','end_at']){const f=fixture(),save=f.deps.save;f.deps.save=async input=>({...await save(input) as object,[field]:'wrong'});const r=await handleSchedulingAssignmentSave(req(),f.deps);assert.equal(r.status,503);assert.equal(f.calls.length,1);assert.ok(!(await r.text()).includes('secret'));}const f=fixture();let count=0;f.deps.save=async()=>{count++;throw Error('private database error');};const r=await handleSchedulingAssignmentSave(req(),f.deps);assert.equal(r.status,503);assert.equal(count,1);assert.ok(!(await r.text()).includes('private'));});
