import type {SkillRequirementMode} from './skillMatching.ts';
export interface SchedulingJob {jobId:string;workspaceId:string;title:string;startAt:string;endAt:string;timezone:string;location:string;requiredSkills:string[];skillRequirementMode:SkillRequirementMode;staffingCount:number;status:'open'|'cancelled';version:number;}
export type JobAttempt=Omit<SchedulingJob,'jobId'|'version'>&{jobId:string|null;requestId:string;expectedVersion:number};
export type JobInvoke=(name:string,body:Record<string,unknown>)=>Promise<{status:number;data:unknown}>;
export const jobRefusalMessages={active_assignments:'Cancel this job’s worker assignments first.'} as const;
export class JobSaveRefused extends Error{readonly code:keyof typeof jobRefusalMessages;constructor(code:keyof typeof jobRefusalMessages){super(jobRefusalMessages[code]);this.code=code;}}
export const jobColumns='id,workspace_id,title,start_at,end_at,timezone,location,required_skills,skill_requirement_mode,staffing_count,status,version';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid job');return v as Record<string,unknown>;}
function instant(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)||!Number.isFinite(Date.parse(v)))throw Error('Invalid time');return new Date(v).toISOString();}
function fields(v:Record<string,unknown>){if(!id(v.workspaceId)||typeof v.title!=='string'||v.title.length<1||v.title.length>160||v.title!==v.title.trim()||typeof v.location!=='string'||v.location.length<1||v.location.length>300||v.location!==v.location.trim()||instant(v.startAt)!==v.startAt||instant(v.endAt)!==v.endAt||Date.parse(v.startAt as string)>=Date.parse(v.endAt as string)||typeof v.timezone!=='string'||!v.timezone||v.timezone!==v.timezone.trim()||v.timezone.length>100||!Array.isArray(v.requiredSkills)||v.requiredSkills.length>30||v.requiredSkills.some(t=>typeof t!=='string'||!t||t.length>80||t!==t.trim())||new Set(v.requiredSkills).size!==v.requiredSkills.length||!['all','any'].includes((v.skillRequirementMode??'all') as string)||!Number.isInteger(v.staffingCount)||(v.staffingCount as number)<1||(v.staffingCount as number)>100||!['open','cancelled'].includes(v.status as string))throw Error('Invalid job');new Intl.DateTimeFormat('en-GB',{timeZone:v.timezone});}
export function validateJobAttempt(value:unknown):JobAttempt{const v=obj(value);fields(v);const legacyKeys='endAt,expectedVersion,jobId,location,requestId,requiredSkills,staffingCount,startAt,status,timezone,title,workspaceId',modeKeys='endAt,expectedVersion,jobId,location,requestId,requiredSkills,skillRequirementMode,staffingCount,startAt,status,timezone,title,workspaceId',keys=Object.keys(v).sort().join(',');if((keys!==legacyKeys&&keys!==modeKeys)||!id(v.requestId)||(v.jobId!==null&&!id(v.jobId))||!Number.isSafeInteger(v.expectedVersion)||(v.expectedVersion as number)<0||(v.expectedVersion as number)>=Number.MAX_SAFE_INTEGER||(v.jobId===null?(v.expectedVersion!==0||v.status!=='open'):v.expectedVersion===0))throw Error('Invalid request');return {...v,skillRequirementMode:v.skillRequirementMode??'all',requiredSkills:[...(v.requiredSkills as string[])].sort()} as JobAttempt;}
export async function loadSchedulingJobs(ws:string,read:(columns:string,ws:string)=>Promise<unknown>):Promise<SchedulingJob[]>{if(!id(ws))throw Error('Workspace required');const raw=await read(jobColumns,ws);if(!Array.isArray(raw))throw Error('Invalid jobs');const seen=new Set<string>(),legacyColumns=jobColumns.split(',').filter(column=>column!=='skill_requirement_mode').sort().join(',');return raw.map(value=>{const r=obj(value),keys=Object.keys(r).sort().join(',');if(keys!==jobColumns.split(',').sort().join(',')&&keys!==legacyColumns)throw Error('Unexpected fields');const v={jobId:r.id,workspaceId:r.workspace_id,title:r.title,startAt:instant(r.start_at),endAt:instant(r.end_at),timezone:r.timezone,location:r.location,requiredSkills:r.required_skills,skillRequirementMode:r.skill_requirement_mode??'all',staffingCount:r.staffing_count,status:r.status,version:r.version};fields(v);if(!id(v.jobId)||seen.has(v.jobId)||v.workspaceId!==ws||!Number.isSafeInteger(v.version)||(v.version as number)<1)throw Error('Invalid job');seen.add(v.jobId);return v as SchedulingJob;}).sort((a,b)=>a.startAt.localeCompare(b.startAt));}
export async function submitJobAttempt(a:JobAttempt,invoke:JobInvoke):Promise<SchedulingJob>{const v=validateJobAttempt(a),response=await invoke('rev-scheduling-job-save',{...v});
 // Only an exact refusal bound to this request proves nothing was saved; any other reply stays unconfirmed.
 if(response.status===409){const x=obj(response.data);if(Object.keys(x).sort().join(',')==='code,requestId,status'&&x.status==='refused'&&x.requestId===v.requestId&&typeof x.code==='string'&&Object.prototype.hasOwnProperty.call(jobRefusalMessages,x.code))throw new JobSaveRefused(x.code as keyof typeof jobRefusalMessages);throw Error('Save unconfirmed');}
 if(response.status!==200)throw Error('Save unconfirmed');const r=obj(response.data),legacyKeys='endAt,jobId,location,requiredSkills,staffingCount,startAt,status,timezone,title,version,workspaceId',modeKeys='endAt,jobId,location,requiredSkills,skillRequirementMode,staffingCount,startAt,status,timezone,title,version,workspaceId',keys=Object.keys(r).sort().join(','),mode=r.skillRequirementMode??'all';fields({...r,skillRequirementMode:mode});if((keys!==legacyKeys&&keys!==modeKeys)||!id(r.jobId)||(v.jobId!==null&&r.jobId!==v.jobId)||r.workspaceId!==v.workspaceId||r.title!==v.title||r.startAt!==v.startAt||r.endAt!==v.endAt||r.timezone!==v.timezone||r.location!==v.location||JSON.stringify(r.requiredSkills)!==JSON.stringify(v.requiredSkills)||mode!==v.skillRequirementMode||r.staffingCount!==v.staffingCount||r.status!==v.status||r.version!==v.expectedVersion+1)throw Error('Save unconfirmed');return {...r,skillRequirementMode:mode} as unknown as SchedulingJob;}
interface Storage{getItem(k:string):string|null;setItem(k:string,v:string):void;removeItem(k:string):void;}
function key(ws:string,user:string){if(!id(ws)||!id(user))throw Error('Identity required');return `rev-job-save:${ws}:${user}`;}
export function rememberJobAttempt(s:Storage,user:string,a:JobAttempt){const v=validateJobAttempt(a);s.setItem(key(v.workspaceId,user),JSON.stringify(v));}
export function restoreJobAttempt(s:Storage,ws:string,user:string):JobAttempt|null{const raw=s.getItem(key(ws,user));if(raw===null)return null;const v=validateJobAttempt(JSON.parse(raw));if(v.workspaceId!==ws)throw Error('Wrong workspace');return v;}
export function clearJobAttempt(s:Storage,ws:string,user:string){s.removeItem(key(ws,user));}
