export interface Assignment{assignmentId:string;workspaceId:string;workerId:string;jobId:string;startAt:string;endAt:string;status:'active'|'cancelled';version:number;}
export interface AssignmentAttempt{workspaceId:string;workerId:string;jobId:string;requestId:string;assignmentId:string|null;status:'active'|'cancelled';expectedVersion:number;expectedWorkerVersion:number|null;expectedJobVersion:number|null;expectedPatternVersion:number|null;expectedStartAt:string;expectedEndAt:string;}
export const assignmentColumns='id,workspace_id,worker_id,job_id,start_at,end_at,status,version';
export const allocationMessages={worker_inactive:'Worker is inactive.',job_unavailable:'Job is unavailable.',missing_skills:'Worker lacks required skills.',outside_working_availability:'Job does not fit recorded working availability.',worker_unavailable:'Worker has overlapping leave or unavailability.',overlap:'Worker already has overlapping work.',capacity_full:'All required places are filled.',stale_worker:'Worker changed. Refresh before allocating.',stale_job:'Job changed. Refresh before allocating.',stale_pattern:'Working pattern changed. Refresh before allocating.',stale_assignment:'Assignment changed. Refresh before cancelling.'};
export class AllocationRefused extends Error{readonly code:keyof typeof allocationMessages;constructor(code:keyof typeof allocationMessages){super(allocationMessages[code]);this.code=code;}}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
const revision=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=1&&v<Number.MAX_SAFE_INTEGER;
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Assignment unavailable');return v as Record<string,unknown>;}
function instant(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)||!Number.isFinite(Date.parse(v)))throw Error('Invalid time');return new Date(v).toISOString();}
export function validateAssignmentAttempt(value:unknown):AssignmentAttempt{const v=obj(value);if(Object.keys(v).sort().join(',')!=='assignmentId,expectedEndAt,expectedJobVersion,expectedPatternVersion,expectedStartAt,expectedVersion,expectedWorkerVersion,jobId,requestId,status,workerId,workspaceId'||!id(v.workspaceId)||!id(v.workerId)||!id(v.jobId)||!id(v.requestId)||(v.assignmentId!==null&&!id(v.assignmentId))||instant(v.expectedStartAt)!==v.expectedStartAt||instant(v.expectedEndAt)!==v.expectedEndAt||Date.parse(v.expectedStartAt as string)>=Date.parse(v.expectedEndAt as string)||(v.assignmentId===null?(v.status!=='active'||v.expectedVersion!==0||!revision(v.expectedWorkerVersion)||!revision(v.expectedJobVersion)||!revision(v.expectedPatternVersion)):(v.status!=='cancelled'||!revision(v.expectedVersion)||v.expectedWorkerVersion!==null||v.expectedJobVersion!==null||v.expectedPatternVersion!==null)))throw Error('Invalid assignment request');return v as unknown as AssignmentAttempt;}
function row(value:unknown):Assignment{const r=obj(value);if(Object.keys(r).sort().join(',')!=='assignmentId,endAt,jobId,startAt,status,version,workerId,workspaceId'||!id(r.assignmentId)||!id(r.workspaceId)||!id(r.workerId)||!id(r.jobId)||!revision(r.version)||!['active','cancelled'].includes(r.status as string)||instant(r.startAt)!==r.startAt||instant(r.endAt)!==r.endAt||Date.parse(r.startAt as string)>=Date.parse(r.endAt as string))throw Error('Invalid assignment');return r as unknown as Assignment;}
export async function loadAssignments(ws:string,job:string,read:(columns:string,ws:string,job:string)=>Promise<unknown>):Promise<Assignment[]>{if(!id(ws)||!id(job))throw Error('Job required');const raw=await read(assignmentColumns,ws,job);if(!Array.isArray(raw))throw Error('Assignments unavailable');const seen=new Set<string>();return raw.map(value=>{const r=obj(value);if(Object.keys(r).sort().join(',')!==assignmentColumns.split(',').sort().join(','))throw Error('Unexpected fields');const a=row({assignmentId:r.id,workspaceId:r.workspace_id,workerId:r.worker_id,jobId:r.job_id,startAt:instant(r.start_at),endAt:instant(r.end_at),status:r.status,version:r.version});if(a.workspaceId!==ws||a.jobId!==job||seen.has(a.assignmentId))throw Error('Assignment unavailable');seen.add(a.assignmentId);return a;});}
export type AssignmentInvoke=(name:string,body:Record<string,unknown>)=>Promise<{status:number;data:unknown}>;
export async function submitAssignmentAttempt(value:AssignmentAttempt,invoke:AssignmentInvoke):Promise<Assignment>{const a=validateAssignmentAttempt(value);const {expectedStartAt,expectedEndAt,...body}=a;const response=await invoke('rev-scheduling-assignment-save',body);if(response.status===409){const refusal=obj(response.data);if(Object.keys(refusal).sort().join(',')==='code,requestId,status'&&refusal.status==='refused'&&refusal.requestId===a.requestId&&typeof refusal.code==='string'&&Object.prototype.hasOwnProperty.call(allocationMessages,refusal.code))throw new AllocationRefused(refusal.code as keyof typeof allocationMessages);throw Error('Outcome unknown');}if(response.status!==200)throw Error('Outcome unknown');const r=row(response.data);if(r.workspaceId!==a.workspaceId||r.workerId!==a.workerId||r.jobId!==a.jobId||(a.assignmentId!==null&&r.assignmentId!==a.assignmentId)||r.status!==a.status||r.version!==a.expectedVersion+1||r.startAt!==expectedStartAt||r.endAt!==expectedEndAt)throw Error('Save unconfirmed');return r;}
interface Storage{getItem(k:string):string|null;setItem(k:string,v:string):void;removeItem(k:string):void;}
function key(ws:string,user:string,job:string){if(!id(ws)||!id(user)||!id(job))throw Error('Identity required');return `rev-allocation:${ws}:${user}:${job}`;}
export function rememberAssignment(s:Storage,user:string,a:AssignmentAttempt){const v=validateAssignmentAttempt(a);s.setItem(key(v.workspaceId,user,v.jobId),JSON.stringify(v));}
export function restoreAssignment(s:Storage,ws:string,user:string,job:string):AssignmentAttempt|null{const raw=s.getItem(key(ws,user,job));if(raw===null)return null;const a=validateAssignmentAttempt(JSON.parse(raw));if(a.workspaceId!==ws||a.jobId!==job)throw Error('Wrong scope');return a;}
export function clearAssignment(s:Storage,ws:string,user:string,job:string){s.removeItem(key(ws,user,job));}
