export const unavailabilityColumns='id,workspace_id,worker_id,start_at,end_at,category,status,version';
export interface UnavailablePeriod {unavailabilityId:string;workspaceId:string;workerId:string;startAt:string;endAt:string;category:'leave'|'unavailable';status:'active'|'cancelled';version:number;}
export type LeaveAttempt=Omit<UnavailablePeriod,'unavailabilityId'|'version'>&{unavailabilityId:string|null;requestId:string;expectedVersion:number};
export interface LegacyLeaveCancelAttempt {workspaceId:string;workerId:string;unavailabilityId:string;requestId:string;expectedVersion:number;}
export const leaveRefusalMessages={assignment_conflict:"Cancel this worker's overlapping assignments before adding or changing this unavailable period.",stale_period:'This unavailable period changed. Refresh the record, review it and try again.',already_cancelled:'This unavailable period is already cancelled. Refresh to see its current status.',inactive_worker:'Reactivate this worker before adding an unavailable period.'} as const;
export class LeaveSaveRefused extends Error{readonly code:keyof typeof leaveRefusalMessages;constructor(code:keyof typeof leaveRefusalMessages){super(leaveRefusalMessages[code]);this.code=code;}}
export const legacyLeaveRefusalMessages={stale_legacy_leave:'This historical leave changed. Refresh it before cancelling.',already_cancelled:'This historical leave is already cancelled.',accounted_leave:'This leave has annual-leave accounting and must be cancelled through Annual Leave.',request_conflict:'This cancellation request ID was already used with different details.'} as const;
export class LegacyLeaveCancelRefused extends Error{readonly code:keyof typeof legacyLeaveRefusalMessages;constructor(code:keyof typeof legacyLeaveRefusalMessages){super(legacyLeaveRefusalMessages[code]);this.code=code;}}
export type LeaveInvoke=(name:string,body:Record<string,unknown>)=>Promise<{status:number;data:unknown}>;
interface Storage{getItem(k:string):string|null;setItem(k:string,v:string):void;removeItem(k:string):void;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Unavailable period invalid');return v as Record<string,unknown>;}
function instant(v:unknown):string{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)||!Number.isFinite(Date.parse(v)))throw new Error('UTC time required');return new Date(v).toISOString();}
function fields(v:Record<string,unknown>){if(!id(v.workspaceId)||!id(v.workerId)||instant(v.startAt)!==v.startAt||instant(v.endAt)!==v.endAt||Date.parse(v.startAt as string)>=Date.parse(v.endAt as string)||!['leave','unavailable'].includes(v.category as string)||!['active','cancelled'].includes(v.status as string))throw new Error('Valid unavailable period required');}
export function validateLeaveAttempt(value:unknown):LeaveAttempt{const v=obj(value);fields(v);if(Object.keys(v).sort().join(',')!=='category,endAt,expectedVersion,requestId,startAt,status,unavailabilityId,workerId,workspaceId'||v.category!=='unavailable'||!id(v.requestId)||(v.unavailabilityId!==null&&!id(v.unavailabilityId))||!Number.isSafeInteger(v.expectedVersion)||(v.expectedVersion as number)<0||(v.expectedVersion as number)>=Number.MAX_SAFE_INTEGER||(v.unavailabilityId===null?(v.expectedVersion!==0||v.status!=='active'):v.expectedVersion===0))throw new Error('Valid request required');return v as unknown as LeaveAttempt;}
export async function loadWorkerUnavailability(ws:string,worker:string,read:(columns:string,ws:string,worker:string)=>Promise<unknown>):Promise<UnavailablePeriod[]>{
 if(!id(ws)||!id(worker))throw new Error('Worker required');const raw=await read(unavailabilityColumns,ws,worker);if(!Array.isArray(raw))throw new Error('Unavailable periods invalid');const seen=new Set<string>();return raw.map(value=>{const r=obj(value);if(Object.keys(r).sort().join(',')!==unavailabilityColumns.split(',').sort().join(','))throw new Error('Unexpected fields');const p={unavailabilityId:r.id,workspaceId:r.workspace_id,workerId:r.worker_id,startAt:instant(r.start_at),endAt:instant(r.end_at),category:r.category,status:r.status,version:r.version};fields(p);if(!id(p.unavailabilityId)||seen.has(p.unavailabilityId)||p.workspaceId!==ws||p.workerId!==worker||!Number.isSafeInteger(p.version)||(p.version as number)<1)throw new Error('Unavailable period invalid');seen.add(p.unavailabilityId);return p as UnavailablePeriod;}).sort((a,b)=>a.startAt.localeCompare(b.startAt));
}
export async function loadAccountedLeaveIds(ws:string,worker:string,read:(columns:string,ws:string,worker:string)=>Promise<unknown>):Promise<Set<string>>{
 if(!id(ws)||!id(worker))throw new Error('Worker required');const raw=await read('unavailability_id',ws,worker);if(!Array.isArray(raw))throw new Error('Annual leave links invalid');const result=new Set<string>();for(const value of raw){const row=obj(value);if(Object.keys(row).join(',')!=='unavailability_id'||!id(row.unavailability_id)||result.has(row.unavailability_id))throw new Error('Annual leave links invalid');result.add(row.unavailability_id);}return result;
}
export async function submitLeaveAttempt(attempt:LeaveAttempt,invoke:LeaveInvoke):Promise<UnavailablePeriod>{const v=validateLeaveAttempt(attempt);const response=await invoke('rev-worker-unavailability-save',{...v});if(response.status===409){const refusal=obj(response.data);if(Object.keys(refusal).sort().join(',')==='code,requestId,status'&&refusal.status==='refused'&&refusal.requestId===v.requestId&&typeof refusal.code==='string'&&Object.prototype.hasOwnProperty.call(leaveRefusalMessages,refusal.code))throw new LeaveSaveRefused(refusal.code as keyof typeof leaveRefusalMessages);throw new Error('Save unconfirmed');}if(response.status!==200)throw new Error('Save unconfirmed');const r=obj(response.data);fields(r);if(Object.keys(r).sort().join(',')!=='category,endAt,startAt,status,unavailabilityId,version,workerId,workspaceId'||!id(r.unavailabilityId)||(v.unavailabilityId!==null&&r.unavailabilityId!==v.unavailabilityId)||r.workspaceId!==v.workspaceId||r.workerId!==v.workerId||r.startAt!==v.startAt||r.endAt!==v.endAt||r.category!==v.category||r.status!==v.status||r.version!==v.expectedVersion+1)throw new Error('Save unconfirmed');return r as unknown as UnavailablePeriod;}
function key(ws:string,user:string,worker:string){if(!id(ws)||!id(user)||!id(worker))throw new Error('Scoped identity required');return `rev-worker-leave:${ws}:${user}:${worker}`;}
export function rememberLeaveAttempt(s:Storage,user:string,a:LeaveAttempt){const v=validateLeaveAttempt(a);s.setItem(key(v.workspaceId,user,v.workerId),JSON.stringify(v));}
export function restoreLeaveAttempt(s:Storage,ws:string,user:string,worker:string):LeaveAttempt|null{const raw=s.getItem(key(ws,user,worker));if(raw===null)return null;const v=validateLeaveAttempt(JSON.parse(raw));if(v.workspaceId!==ws||v.workerId!==worker)throw new Error('Pending period invalid');return v;}
export function clearLeaveAttempt(s:Storage,ws:string,user:string,worker:string){s.removeItem(key(ws,user,worker));}
function legacyKey(ws:string,user:string,worker:string){if(!id(ws)||!id(user)||!id(worker))throw new Error('Scoped identity required');return `rev-worker-legacy-leave-cancel:${ws}:${user}:${worker}`;}
export function validateLegacyLeaveCancelAttempt(value:unknown):LegacyLeaveCancelAttempt{const v=obj(value);if(Object.keys(v).sort().join(',')!=='expectedVersion,requestId,unavailabilityId,workerId,workspaceId'||!id(v.workspaceId)||!id(v.workerId)||!id(v.unavailabilityId)||!id(v.requestId)||!Number.isSafeInteger(v.expectedVersion)||(v.expectedVersion as number)<1||(v.expectedVersion as number)>=Number.MAX_SAFE_INTEGER)throw new Error('Valid historical leave cancellation required');return v as unknown as LegacyLeaveCancelAttempt;}
export async function submitLegacyLeaveCancellation(attempt:LegacyLeaveCancelAttempt,invoke:LeaveInvoke):Promise<UnavailablePeriod>{const v=validateLegacyLeaveCancelAttempt(attempt);const response=await invoke('rev-legacy-annual-leave-cancel',v as unknown as Record<string,unknown>);if(response.status===409){const refusal=obj(response.data);if(Object.keys(refusal).sort().join(',')==='code,requestId,status'&&refusal.status==='refused'&&refusal.requestId===v.requestId&&typeof refusal.code==='string'&&Object.prototype.hasOwnProperty.call(legacyLeaveRefusalMessages,refusal.code))throw new LegacyLeaveCancelRefused(refusal.code as keyof typeof legacyLeaveRefusalMessages);throw new Error('Historical cancellation unconfirmed');}if(response.status!==200)throw new Error('Historical cancellation unconfirmed');const r=obj(response.data);fields(r);if(Object.keys(r).sort().join(',')!=='category,endAt,startAt,status,unavailabilityId,version,workerId,workspaceId'||r.unavailabilityId!==v.unavailabilityId||r.workspaceId!==v.workspaceId||r.workerId!==v.workerId||r.category!=='leave'||r.status!=='cancelled'||r.version!==v.expectedVersion+1)throw new Error('Historical cancellation unconfirmed');return r as unknown as UnavailablePeriod;}
export function rememberLegacyLeaveCancelAttempt(s:Storage,user:string,a:LegacyLeaveCancelAttempt){const v=validateLegacyLeaveCancelAttempt(a);s.setItem(legacyKey(v.workspaceId,user,v.workerId),JSON.stringify(v));}
export function restoreLegacyLeaveCancelAttempt(s:Storage,ws:string,user:string,worker:string):LegacyLeaveCancelAttempt|null{const raw=s.getItem(legacyKey(ws,user,worker));if(raw===null)return null;const v=validateLegacyLeaveCancelAttempt(JSON.parse(raw));if(v.workspaceId!==ws||v.workerId!==worker)throw new Error('Pending historical cancellation invalid');return v;}
export function clearLegacyLeaveCancelAttempt(s:Storage,ws:string,user:string,worker:string){s.removeItem(legacyKey(ws,user,worker));}
function localValue(ms:number,tz:string):string{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const get=(type:string)=>parts.find(p=>p.type===type)?.value;return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`;}
export function localLeaveToUtc(local:string,timezone:string):string{
 if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(local)||local<'1000-01-01T00:00')throw new Error('Valid local date required');const base=Date.parse(local+':00.000Z');if(!Number.isFinite(base)||new Date(base).toISOString().slice(0,16)!==local)throw new Error('Valid local date required');
 const offsets=new Set<number>();for(let hours=-48;hours<=48;hours+=6){const probe=base+hours*3600000;const formatted=localValue(probe,timezone),parsed=Date.parse(formatted+':00.000Z');if(Number.isFinite(parsed))offsets.add(parsed-probe);}
 const matches=[...offsets].map(offset=>base-offset).filter(ms=>localValue(ms,timezone)===local);
 if(matches.length!==1)throw new Error('Local time is ambiguous or nonexistent; choose another time');return new Date(matches[0]).toISOString();
}
export function utcLeaveToLocal(utc:string,timezone:string){return localValue(Date.parse(instant(utc)),timezone);}
