export const patternColumns='id,workspace_id,worker_id,timezone,working_days,start_local,end_local,effective_from,effective_until,version';
export interface WorkingPattern {patternId:string;workspaceId:string;workerId:string;timezone:string;workingDays:number[];startLocal:string;endLocal:string;effectiveFrom:string;effectiveUntil:string|null;version:number;}
export type PatternAttempt=Omit<WorkingPattern,'patternId'|'version'>&{requestId:string;expectedVersion:number};
export const patternRefusalMessages={assignment_conflict:"Cancel this worker's affected assignments before changing their working availability.",stale_pattern:'Working availability changed. Refresh the record, review it and save again.',inactive_worker:'Reactivate this worker before saving working availability.'} as const;
export class PatternSaveRefused extends Error{readonly code:keyof typeof patternRefusalMessages;constructor(code:keyof typeof patternRefusalMessages){super(patternRefusalMessages[code]);this.code=code;}}
export type PatternInvoke=(name:string,body:Record<string,unknown>)=>Promise<{status:number;data:unknown}>;
interface Storage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
function object(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Working pattern unavailable');return v as Record<string,unknown>;}
function date(v:unknown):v is string{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1000-01-01')return false;const ms=Date.parse(v+'T00:00:00.000Z');return Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,10)===v;}
function fields(v:Record<string,unknown>){
 if(!id(v.workspaceId)||!id(v.workerId)||typeof v.timezone!=='string'||!v.timezone||v.timezone.trim()!==v.timezone||v.timezone.length>100||!Array.isArray(v.workingDays)||v.workingDays.length<1||v.workingDays.length>7||v.workingDays.some(d=>!Number.isInteger(d)||d<1||d>7)||new Set(v.workingDays).size!==v.workingDays.length||typeof v.startLocal!=='string'||typeof v.endLocal!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.startLocal)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.endLocal)||v.startLocal>=v.endLocal||!date(v.effectiveFrom)||(v.effectiveUntil!==null&&(!date(v.effectiveUntil)||v.effectiveUntil<v.effectiveFrom)))throw new Error('Valid working pattern required');
 new Intl.DateTimeFormat('en-GB',{timeZone:v.timezone});
}
export function validatePatternAttempt(value:unknown):PatternAttempt{const v=object(value);fields(v);if(Object.keys(v).sort().join(',')!=='effectiveFrom,effectiveUntil,endLocal,expectedVersion,requestId,startLocal,timezone,workerId,workingDays,workspaceId'||!id(v.requestId)||!Number.isSafeInteger(v.expectedVersion)||(v.expectedVersion as number)<0||(v.expectedVersion as number)>=Number.MAX_SAFE_INTEGER)throw new Error('Valid working-pattern request required');return {...v,workingDays:[...(v.workingDays as number[])].sort((a,b)=>a-b)} as unknown as PatternAttempt;}
export async function loadWorkingPattern(workspaceId:string,workerId:string,read:(columns:string,workspaceId:string,workerId:string)=>Promise<unknown>):Promise<WorkingPattern|null>{
 if(!id(workspaceId)||!id(workerId))throw new Error('Worker required');const raw=await read(patternColumns,workspaceId,workerId);if(!Array.isArray(raw)||raw.length>1)throw new Error('Working pattern unavailable');if(raw.length===0)return null;
 const row=object(raw[0]);if(Object.keys(row).sort().join(',')!==patternColumns.split(',').sort().join(','))throw new Error('Working pattern unavailable');
 const result={patternId:row.id,workspaceId:row.workspace_id,workerId:row.worker_id,timezone:row.timezone,workingDays:row.working_days,startLocal:row.start_local,endLocal:row.end_local,effectiveFrom:row.effective_from,effectiveUntil:row.effective_until,version:row.version};fields(result);
 if(!id(result.patternId)||result.workspaceId!==workspaceId||result.workerId!==workerId||!Number.isSafeInteger(result.version)||(result.version as number)<1)throw new Error('Working pattern unavailable');return result as WorkingPattern;
}
export async function submitPatternAttempt(attempt:PatternAttempt,invoke:PatternInvoke):Promise<WorkingPattern>{const input=validatePatternAttempt(attempt);const response=await invoke('rev-worker-pattern-save',{...input});if(response.status===409){const refusal=object(response.data);if(Object.keys(refusal).sort().join(',')==='code,requestId,status'&&refusal.status==='refused'&&refusal.requestId===input.requestId&&typeof refusal.code==='string'&&Object.prototype.hasOwnProperty.call(patternRefusalMessages,refusal.code))throw new PatternSaveRefused(refusal.code as keyof typeof patternRefusalMessages);throw new Error('Save could not be confirmed');}if(response.status!==200)throw new Error('Save could not be confirmed');const v=object(response.data);fields(v);if(Object.keys(v).sort().join(',')!=='effectiveFrom,effectiveUntil,endLocal,patternId,startLocal,timezone,version,workerId,workingDays,workspaceId'||!id(v.patternId)||v.workspaceId!==input.workspaceId||v.workerId!==input.workerId||v.timezone!==input.timezone||v.startLocal!==input.startLocal||v.endLocal!==input.endLocal||v.effectiveFrom!==input.effectiveFrom||v.effectiveUntil!==input.effectiveUntil||v.version!==input.expectedVersion+1||JSON.stringify([...(v.workingDays as number[])].sort((a,b)=>a-b))!==JSON.stringify(input.workingDays))throw new Error('Save could not be confirmed');return v as unknown as WorkingPattern;}
function key(ws:string,user:string,worker:string){if(!id(ws)||!id(user)||!id(worker))throw new Error('Scoped user and worker required');return `rev-worker-pattern:${ws}:${user}:${worker}`;}
export function rememberPatternAttempt(storage:Storage,userId:string,input:PatternAttempt){const v=validatePatternAttempt(input);storage.setItem(key(v.workspaceId,userId,v.workerId),JSON.stringify(v));}
export function restorePatternAttempt(storage:Storage,ws:string,user:string,worker:string):PatternAttempt|null{const raw=storage.getItem(key(ws,user,worker));if(raw===null)return null;const v=validatePatternAttempt(JSON.parse(raw));if(v.workspaceId!==ws||v.workerId!==worker)throw new Error('Pending pattern unavailable');return v;}
export function clearPatternAttempt(storage:Storage,ws:string,user:string,worker:string){storage.removeItem(key(ws,user,worker));}
