import {resolveAnnualLeaveOrigin} from '../_shared/annualLeaveOrigins.ts';

export interface AnnualLeaveAdjustmentInput{target_workspace_id:string;initiating_user_id:string;target_request_id:string;target_account_id:string;target_adjustment_minutes:number;target_reason:string;expected_version:number;}
export interface AnnualLeaveAdjustmentDependencies{allowedOrigin?:string;getUserId(authorization:string):Promise<string|null>;canManage(authorization:string,workspaceId:string,userId:string):Promise<boolean>;save(input:AnnualLeaveAdjustmentInput):Promise<unknown>;}
export const annualLeaveAdjustmentRefusalReasons={'Annual leave account changed':'stale_account'} as const;
export type AnnualLeaveAdjustmentRefusalCode=typeof annualLeaveAdjustmentRefusalReasons[keyof typeof annualLeaveAdjustmentRefusalReasons];
export class AnnualLeaveAdjustmentRefusal extends Error{readonly code:AnnualLeaveAdjustmentRefusalCode;constructor(code:AnnualLeaveAdjustmentRefusalCode){super('Annual leave adjustment refused');this.code=code;}}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,id=(value:unknown):value is string=>typeof value==='string'&&uuid.test(value),date=(value:unknown):value is string=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
export async function handleAnnualLeaveAdjustmentSave(request:Request,deps:AnnualLeaveAdjustmentDependencies):Promise<Response>{
 const origin=resolveAnnualLeaveOrigin(request.headers.get('Origin'),deps.allowedOrigin);if(!origin)return new Response(null,{status:403});const headers={'Access-Control-Allow-Origin':origin,Vary:'Origin','Cache-Control':'no-store','Content-Type':'application/json'},reply=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'authorization, content-type, apikey, x-client-info'}});if(request.method!=='POST')return reply(405,{error:'Method not allowed.'});const authorization=request.headers.get('Authorization')??'';if(!/^Bearer\s+\S+$/i.test(authorization))return reply(401,{error:'Authentication required.'});if(request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')return reply(415,{error:'JSON required.'});
 try{const raw=await request.text();if(raw.length>4096)return reply(400,{error:'Invalid annual leave adjustment.'});const body=JSON.parse(raw);if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).sort().join(',')!=='accountId,adjustmentMinutes,expectedVersion,reason,requestId,workspaceId'||!id(body.workspaceId)||!id(body.accountId)||!id(body.requestId)||!Number.isSafeInteger(body.adjustmentMinutes)||body.adjustmentMinutes===0||Math.abs(body.adjustmentMinutes)>10000000||typeof body.reason!=='string'||body.reason.length<1||body.reason.length>500||body.reason!==body.reason.trim()||!Number.isSafeInteger(body.expectedVersion)||body.expectedVersion<1||body.expectedVersion>=Number.MAX_SAFE_INTEGER)return reply(400,{error:'Invalid annual leave adjustment.'});const userId=await deps.getUserId(authorization);if(!id(userId))return reply(401,{error:'Authentication required.'});if(!await deps.canManage(authorization,body.workspaceId,userId))return reply(403,{error:'Annual leave adjustment could not be saved.'});let value:unknown;try{value=await deps.save({target_workspace_id:body.workspaceId,initiating_user_id:userId,target_request_id:body.requestId,target_account_id:body.accountId,target_adjustment_minutes:body.adjustmentMinutes,target_reason:body.reason,expected_version:body.expectedVersion});}catch(error){if(error instanceof AnnualLeaveAdjustmentRefusal&&Object.values(annualLeaveAdjustmentRefusalReasons).includes(error.code))return reply(409,{status:'refused',code:error.code,requestId:body.requestId});throw error;}if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid result');const row=value as Record<string,unknown>;
  if(!id(row.adjustment_id)||row.workspace_id!==body.workspaceId||row.account_id!==body.accountId||!id(row.worker_id)||!date(row.leave_year_start)||row.adjustment_minutes!==body.adjustmentMinutes||row.reason!==body.reason||row.account_version!==body.expectedVersion+1||!Number.isSafeInteger(row.adjustment_total_minutes)||row.accounting_status!=='policy_only')throw Error('Invalid result');return reply(200,{adjustmentId:row.adjustment_id,workspaceId:row.workspace_id,accountId:row.account_id,workerId:row.worker_id,leaveYearStart:row.leave_year_start,adjustmentMinutes:row.adjustment_minutes,reason:row.reason,accountVersion:row.account_version,adjustmentTotalMinutes:row.adjustment_total_minutes,accountingStatus:'policy_only'});
 }catch{return reply(503,{error:'Annual leave adjustment outcome could not be confirmed.',code:'outcome_unknown'});}
}