import test from'node:test';import assert from'node:assert/strict';import{AnnualLeaveAdjustmentRefusal,handleAnnualLeaveAdjustmentSave,type AnnualLeaveAdjustmentDependencies}from'./annualLeaveAdjustmentBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',account='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',adjustment='55555555-5555-4555-8555-555555555555',worker='66666666-6666-4666-8666-666666666666',origin='http://localhost:5180',body={workspaceId:ws,requestId,accountId:account,adjustmentMinutes:450,reason:'Contractual correction',expectedVersion:1};
const req=(value:unknown=body)=>new Request('https://example.test',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json'},body:JSON.stringify(value)});
function fixture(){const calls:unknown[]=[];const deps:AnnualLeaveAdjustmentDependencies={allowedOrigin:origin,getUserId:async()=>actor,canManage:async()=>true,save:async input=>{calls.push(input);return{adjustment_id:adjustment,workspace_id:ws,account_id:account,worker_id:worker,leave_year_start:'2026-04-01',adjustment_minutes:input.target_adjustment_minutes,reason:input.target_reason,account_version:input.expected_version+1,adjustment_total_minutes:input.target_adjustment_minutes,accounting_status:'policy_only',private:'hidden'};}};return{calls,deps};}
test('adjustment preflight allows both exact development origins and rejects missing or unrelated origins',async()=>{for(const requestOrigin of['http://localhost:5180','http://127.0.0.1:5180']){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const response=await handleAnnualLeaveAdjustmentSave(new Request('https://example.test',{method:'OPTIONS',headers:{Origin:requestOrigin}}),f.deps);assert.equal(response.status,204);assert.equal(response.headers.get('Access-Control-Allow-Origin'),requestOrigin);assert.equal(response.headers.get('Vary'),'Origin');assert.equal(auth,0);assert.equal(f.calls.length,0);}for(const requestOrigin of[undefined,'https://unrelated.example']){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const response=await handleAnnualLeaveAdjustmentSave(new Request('https://example.test',{method:'OPTIONS',headers:requestOrigin?{Origin:requestOrigin}:undefined}),f.deps);assert.equal(response.status,403);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null);assert.equal(auth,0);assert.equal(f.calls.length,0);}});
test('manager appends reasoned integer-minute adjustment against expected account version',async()=>{const f=fixture(),response=await handleAnnualLeaveAdjustmentSave(req(),f.deps);assert.equal(response.status,200);assert.deepEqual(f.calls,[{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_account_id:account,target_adjustment_minutes:450,target_reason:'Contractual correction',expected_version:1}]);const result=await response.json();assert.equal(result.accountVersion,2);assert.equal(result.accountingStatus,'policy_only');assert.ok(!Object.hasOwn(result,'private'));});
test('negative adjustment is accepted but zero, missing reason and invalid revisions stop locally',async()=>{const negative=fixture();assert.equal((await handleAnnualLeaveAdjustmentSave(req({...body,adjustmentMinutes:-225}),negative.deps)).status,200);for(const patch of[{adjustmentMinutes:0},{adjustmentMinutes:1.5},{reason:''},{reason:' padded '},{expectedVersion:0},{actorUserId:actor}]){const f=fixture();assert.equal((await handleAnnualLeaveAdjustmentSave(req({...body,...patch}),f.deps)).status,400);assert.equal(f.calls.length,0);}});
test('unverified or unauthorized callers never append adjustments',async()=>{for(const mode of['auth','role']){const f=fixture();if(mode==='auth')f.deps.getUserId=async()=>null;else f.deps.canManage=async()=>false;assert.ok((await handleAnnualLeaveAdjustmentSave(req(),f.deps)).status>=400);assert.equal(f.calls.length,0);}});
test('mismatched result or private failure remains unknown without retry',async()=>{for(const mode of['version','private']){const f=fixture(),save=f.deps.save;let calls=0;f.deps.save=async input=>{calls++;if(mode==='private')throw Error('private database error');return{...await save(input)as object,account_version:99};};const response=await handleAnnualLeaveAdjustmentSave(req(),f.deps);assert.equal(response.status,503);assert.equal(calls,1);assert.ok(!(await response.text()).includes('private database'));}});
test('stale account refusal is request-bound and definitive',async()=>{const f=fixture();f.deps.save=async()=>{throw new AnnualLeaveAdjustmentRefusal('stale_account');};const response=await handleAnnualLeaveAdjustmentSave(req(),f.deps);assert.equal(response.status,409);assert.deepEqual(await response.json(),{status:'refused',code:'stale_account',requestId});});
test('arbitrary adjustment errors remain outcome unknown even when text resembles a refusal',async()=>{const f=fixture();f.deps.save=async()=>{throw Error('Annual leave account changed');};const response=await handleAnnualLeaveAdjustmentSave(req(),f.deps);assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'Annual leave adjustment outcome could not be confirmed.',code:'outcome_unknown'});});