import test from 'node:test';
import assert from 'node:assert/strict';
import {readMicrosoftGraphSelectedCalendarAvailability} from './microsoftGraphSelectedCalendarAvailability.ts';
import type {MicrosoftGraphAvailabilityRequest} from './microsoftGraphAvailability.ts';
const request:MicrosoftGraphAvailabilityRequest={accessToken:'fake-access',workspaceId:'workspace',selectedCalendarId:'calendar',selectedCalendar:{id:'calendar',workspaceId:'workspace',connectionId:'connection',provider:'microsoft_graph',providerCalendarReference:'AAMk+/=',timezone:'Europe/London'},mailboxUserPrincipalName:'owner@example.test',searchStartAt:'2040-09-30T09:00:00.000Z',searchEndAt:'2040-09-30T17:00:00.000Z',timezone:'Europe/London'};
const event={showAs:'busy',isCancelled:false,start:{dateTime:'2040-09-30T10:00:00.0000000',timeZone:'UTC'},end:{dateTime:'2040-09-30T10:30:00.0000000',timeZone:'UTC'}};
function transport(values:unknown[]){const calls:{url:string;init:RequestInit|undefined}[]=[];const fetchImpl:typeof fetch=async(url,init)=>{calls.push({url:String(url),init});const value=values.shift();if(value instanceof Response)return value;if(value instanceof Error)throw value;if(value===undefined)throw new Error('Unexpected request');return Response.json(value);};return{calls,fetchImpl};}
test('reads exact selected calendar with GET and returns only UTC busy intervals',async()=>{const f=transport([{value:[event]}]);assert.deepEqual(await readMicrosoftGraphSelectedCalendarAvailability(request,f.fetchImpl),[{startAt:'2040-09-30T10:00:00.000Z',endAt:'2040-09-30T10:30:00.000Z'}]);const call=f.calls[0];assert.equal(new URL(call.url).pathname,'/v1.0/me/calendars/AAMk%2B%2F%3D/calendarView');assert.equal(call.init?.method,'GET');assert.equal(call.init?.redirect,'error');assert.equal((call.init?.headers as Record<string,string>).Prefer,'outlook.timezone="UTC"');assert.equal(call.init?.body,undefined);});
test('free and cancelled events do not block; tentative, out-of-office and working elsewhere do',async()=>{const f=transport([{value:[{...event,showAs:'free'},{...event,isCancelled:true},...['tentative','oof','workingElsewhere'].map(showAs=>({...event,showAs}))]}]);assert.equal((await readMicrosoftGraphSelectedCalendarAvailability(request,f.fetchImpl)).length,3);});
test('unknown status, missing cancellation flag and invalid UTC times refuse partial availability',async()=>{for(const bad of [{...event,showAs:'unknown'},{...event,isCancelled:undefined},{...event,start:{dateTime:'2040-09-30T10:00:00',timeZone:'Europe/London'}},{...event,end:event.start}]){const f=transport([{value:[event,bad]}]);await assert.rejects(readMicrosoftGraphSelectedCalendarAvailability(request,f.fetchImpl),e=>(e as {kind:string}).kind==='invalid_payload');}});
test('workspace, calendar, timezone and excessive range mismatches stop before HTTP',async()=>{for(const override of [{workspaceId:'other'},{selectedCalendarId:'other'},{timezone:'UTC'},{searchEndAt:'2040-10-10T17:00:00.000Z'}]){const f=transport([]);await assert.rejects(readMicrosoftGraphSelectedCalendarAvailability({...request,...override},f.fetchImpl));assert.equal(f.calls.length,0);}});
test('pagination reads all pages; foreign origins and other calendars never receive token',async()=>{const safe='https://graph.microsoft.com/v1.0/me/calendars/AAMk%2B%2F%3D/calendarView?$skiptoken=fake';const f=transport([{value:[event],'@odata.nextLink':safe},{value:[event]}]);assert.equal((await readMicrosoftGraphSelectedCalendarAvailability(request,f.fetchImpl)).length,2);for(const link of ['https://evil.test/events','https://graph.microsoft.com/v1.0/me/calendars/other/calendarView']){const blocked=transport([{value:[],'@odata.nextLink':link}]);await assert.rejects(readMicrosoftGraphSelectedCalendarAvailability(request,blocked.fetchImpl));assert.equal(blocked.calls.length,1);}});
test('429, provider refusal and transport uncertainty keep distinct error categories',async()=>{for(const [value,kind]of [[Response.json({}, {status:429}),'rate_limited'],[Response.json({}, {status:403}),'provider_rejected'],[new Error('timeout'),'read_outcome_unknown']] as const){const f=transport([value]);await assert.rejects(readMicrosoftGraphSelectedCalendarAvailability(request,f.fetchImpl),e=>(e as {kind:string}).kind===kind);assert.equal(f.calls.length,1);}});
