import test from 'node:test';
import assert from 'node:assert/strict';
import { discoverMicrosoftGraphCalendars } from './microsoftGraphCalendarDiscovery.ts';
const primary={id:'default-id',name:'Calendar',owner:{address:'Owner@example.test'}};
const secondary={id:'second-id',name:'Work',owner:{address:'owner@example.test'}};
function transport(values:unknown[]){const calls:{url:string;init:RequestInit|undefined}[]=[];const fetchImpl:typeof fetch=async(url,init)=>{calls.push({url:String(url),init});const value=values.shift();if(value instanceof Response)return value;if(value===undefined)throw new Error('Unexpected request');return Response.json(value);};return{calls,fetchImpl};}
test('discovers sanitized account-owned calendars, including default, using GET only',async()=>{const f=transport([primary,{value:[primary,secondary,{...secondary,id:'shared',owner:{address:'other@example.test'}}]}]);const result=await discoverMicrosoftGraphCalendars('fake-token',f.fetchImpl);assert.equal(result.providerAccountReference,'owner@example.test');assert.deepEqual(result.calendars.map(c=>[c.providerCalendarReference,c.isDefault]),[['default-id',true],['second-id',false]]);for(const call of f.calls){assert.equal(call.init?.method,'GET');assert.equal(call.init?.redirect,'error');assert.equal((call.init?.headers as Record<string,string>).Authorization,'Bearer fake-token');assert.ok(!call.init?.body);}assert.ok(!JSON.stringify(result).includes('fake-token'));});
test('safe pagination deduplicates calendars',async()=>{const next='https://graph.microsoft.com/v1.0/me/calendars?$skiptoken=fake';const f=transport([primary,{value:[primary],'@odata.nextLink':next},{value:[secondary]}]);assert.equal((await discoverMicrosoftGraphCalendars('fake',f.fetchImpl)).calendars.length,2);assert.equal(f.calls.length,3);});
test('external, cross-account and malformed pagination never receives bearer token',async()=>{for(const link of ['https://evil.test/calendars','https://graph.microsoft.com/v1.0/users/other/calendars','https://graph.microsoft.com/v1.0/me/calendars#fragment','https://graph.microsoft.com/v1.0/me/calendars?$expand=events']){const f=transport([primary,{value:[], '@odata.nextLink':link}]);await assert.rejects(discoverMicrosoftGraphCalendars('fake',f.fetchImpl));assert.equal(f.calls.length,2);}});
test('HTTP refusal, malformed owner and missing calendar fields fail without partial results',async()=>{for(const value of [Response.json({error:'private details'},{status:403}),{...primary,owner:{}},{...primary,id:''},{...primary,name:''}]){const f=transport([value]);await assert.rejects(discoverMicrosoftGraphCalendars('fake',f.fetchImpl),{message:'Calendar discovery unavailable'});}});
test('conflicting duplicate IDs and pagination loops fail closed',async()=>{const initial='https://graph.microsoft.com/v1.0/me/calendars?$select=id,name,owner&$top=100';for(const result of [{value:[{...primary,name:'Changed'}]},{value:[],'@odata.nextLink':initial}]){const f=transport([primary,result]);await assert.rejects(discoverMicrosoftGraphCalendars('fake',f.fetchImpl));assert.equal(f.calls.length,2);}});
test('invalid token stops before transport',async()=>{for(const token of ['', 'fake\r\nheader']){const f=transport([]);await assert.rejects(discoverMicrosoftGraphCalendars(token,f.fetchImpl));assert.equal(f.calls.length,0);}});
