import assert from 'node:assert/strict';
import test from 'node:test';
import {DocumentProviderFailure} from './openAiJobDocumentProvider.ts';
import {handleJobDocumentAnalysis,type AnalysisDependencies} from './jobDocumentAnalysisBoundary.ts';

const workspaceId='11111111-1111-4111-8111-111111111111',userId='22222222-2222-4222-8222-222222222222',jobId='33333333-3333-4333-8333-333333333333',documentId='44444444-4444-4444-8444-444444444444',requestId='55555555-5555-4555-8555-555555555555';
const requirements={tasks:[{value:'Provide support',references:[{page:1,section:null}]}],requiredSkills:[{value:'First aid',references:[{page:1,section:'Requirements'}]}],qualifications:[],location:null,dates:[],duration:null,missingInformation:['duration'],ambiguities:[]};
const body={action:'analyse',workspaceId,jobId,documentId,documentVersion:1,jobVersion:3,requestId};
const row=(patch:Record<string,unknown>={})=>({analysis_id:requestId,workspace_id:workspaceId,job_id:jobId,document_id:documentId,document_version:1,job_version:3,status:'claimed',version:1,should_attempt:true,extraction:null,error_code:null,...patch});
const source={filename:'brief.txt',mimeType:'text/plain' as const,base64:'aGVsbG8=',job:{title:'Support',startAt:'2026-10-12T08:00:00.000Z',endAt:'2026-10-12T16:00:00.000Z',timezone:'Europe/London',location:'Office',requiredSkills:[]}};
function dependencies(patch:Partial<AnalysisDependencies>={}):AnalysisDependencies{return{allowedOrigin:'http://localhost:5180',providerConfigured:true,getUserId:async()=>userId,canManage:async()=>true,claim:async()=>row(),source:async()=>source,analyse:async()=>({requirements,inputTokens:20,outputTokens:10,providerResponseId:'resp_1'}),complete:async input=>row({status:input.target_status,version:2,should_attempt:false,extraction:input.target_extraction,error_code:input.target_error_code}),...patch};}
const request=(value:unknown=body)=>new Request('http://localhost/functions/v1/rev-scheduling-job-document-analyse',{method:'POST',headers:{Origin:'http://localhost:5180',Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify(value)});

test('reports disabled provider status without attempting analysis',async()=>{let claimed=false;const response=await handleJobDocumentAnalysis(request({action:'status',workspaceId,jobId}),dependencies({providerConfigured:false,claim:async()=>{claimed=true;throw Error('not called');}}));assert.equal(response.status,200);assert.deepEqual(await response.json(),{available:false,model:null});assert.equal(claimed,false);});
test('extracts evidence once and returns the durable completion',async()=>{let attempts=0;const response=await handleJobDocumentAnalysis(request(),dependencies({analyse:async()=>{attempts++;return{requirements,inputTokens:20,outputTokens:10,providerResponseId:'resp_1'};}}));assert.equal(response.status,200);assert.equal((await response.json()).status,'succeeded');assert.equal(attempts,1);});
test('replays a completed claim without another provider attempt',async()=>{let attempts=0;const response=await handleJobDocumentAnalysis(request(),dependencies({claim:async()=>row({status:'succeeded',version:2,should_attempt:false,extraction:requirements}),analyse:async()=>{attempts++;throw Error('not called');}}));assert.equal(response.status,200);assert.equal(attempts,0);});
test('keeps an in-flight claim pending without another provider attempt',async()=>{const response=await handleJobDocumentAnalysis(request(),dependencies({claim:async()=>row({should_attempt:false})}));assert.equal(response.status,202);assert.equal((await response.json()).status,'claimed');});
test('returns a durable provider failure on an exact retry without another attempt',async()=>{let attempts=0;const response=await handleJobDocumentAnalysis(request(),dependencies({claim:async()=>row({status:'failed',version:2,should_attempt:false,error_code:'provider_unavailable'}),analyse:async()=>{attempts++;throw Error('not called');}}));assert.equal(response.status,409);assert.equal((await response.json()).code,'provider_unavailable');assert.equal(attempts,0);});
test('durably records provider refusal and never returns fabricated extraction',async()=>{let completion:Record<string,unknown>|null=null;const response=await handleJobDocumentAnalysis(request(),dependencies({analyse:async()=>{throw new DocumentProviderFailure('refused');},complete:async input=>{completion=input;return row({status:'failed',version:2,should_attempt:false,error_code:input.target_error_code});}}));assert.equal(response.status,502);assert.equal((await response.json()).code,'provider_refused');assert.equal(completion?.target_status,'failed');assert.equal(completion?.target_extraction,null);});
test('denies cross-workspace or unauthorized managers before claim',async()=>{let claimed=false;const response=await handleJobDocumentAnalysis(request(),dependencies({canManage:async()=>false,claim:async()=>{claimed=true;throw Error('not called');}}));assert.equal(response.status,403);assert.equal(claimed,false);});
