import test from'node:test';import assert from'node:assert/strict';import{AnnualLeavePolicyRefusal,handleAnnualLeavePolicySave,type AnnualLeavePolicyDependencies}from'./annualLeavePolicyBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',policy='55555555-5555-4555-8555-555555555555',origin='http://localhost:5180';
const body={workspaceId:ws,requestId,workerId:null,effectiveFromLeaveYear:2026,allowanceInputUnit:'days',allowanceInputValue:28,allowanceMinutes:12600,hoursPerDayMinutes:450,leaveYearStartMonth:4,leaveYearStartDay:1,bankHolidayTreatment:'included',expectedVersion:0};
const req=(value:unknown=body,headers:Record<string,string>={},method='POST')=>new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json',...headers},body:method==='POST'?JSON.stringify(value):undefined});
function fixture(){const calls:unknown[]=[];const deps:AnnualLeavePolicyDependencies={allowedOrigin:origin,getUserId:async()=>actor,canManage:async()=>true,save:async input=>{calls.push(input);return{policy_id:policy,workspace_id:ws,worker_id:input.target_worker_id,version:input.expected_version+1,effective_from_leave_year:input.target_effective_from_leave_year,allowance_input_unit:input.target_allowance_input_unit,allowance_input_value:input.target_allowance_input_value,allowance_minutes:input.target_allowance_minutes,hours_per_day_minutes:input.target_hours_per_day_minutes,leave_year_start_month:input.target_leave_year_start_month,leave_year_start_day:input.target_leave_year_start_day,bank_holiday_treatment:input.target_bank_holiday_treatment,private:'hidden'};}};return{calls,deps};}
test('policy preflight allows both exact development origins and rejects missing or unrelated origins',async()=>{for(const requestOrigin of['http://localhost:5180','http://127.0.0.1:5180']){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const response=await handleAnnualLeavePolicySave(new Request('https://example.test',{method:'OPTIONS',headers:{Origin:requestOrigin}}),f.deps);assert.equal(response.status,204);assert.equal(response.headers.get('Access-Control-Allow-Origin'),requestOrigin);assert.equal(response.headers.get('Vary'),'Origin');assert.equal(auth,0);assert.equal(f.calls.length,0);}for(const requestOrigin of[undefined,'https://unrelated.example']){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const response=await handleAnnualLeavePolicySave(new Request('https://example.test',{method:'OPTIONS',headers:requestOrigin?{Origin:requestOrigin}:undefined}),f.deps);assert.equal(response.status,403);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null);assert.equal(auth,0);assert.equal(f.calls.length,0);}});
test('manager saves canonical workspace default and receives safe integer-minute policy',async()=>{const f=fixture(),response=await handleAnnualLeavePolicySave(req(),f.deps);assert.equal(response.status,200);assert.deepEqual(f.calls,[{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_worker_id:null,target_effective_from_leave_year:2026,target_allowance_input_unit:'days',target_allowance_input_value:28,target_allowance_minutes:12600,target_hours_per_day_minutes:450,target_leave_year_start_month:4,target_leave_year_start_day:1,target_bank_holiday_treatment:'included',expected_version:0}]);const result=await response.json();assert.equal(result.allowanceMinutes,12600);assert.equal(result.workerId,null);assert.ok(!Object.hasOwn(result,'private'));});
test('full worker override and expected version pass unchanged',async()=>{const f=fixture(),response=await handleAnnualLeavePolicySave(req({...body,workerId:worker,allowanceInputUnit:'hours',allowanceInputValue:210,hoursPerDayMinutes:420,expectedVersion:2}),f.deps);assert.equal(response.status,200);assert.equal((f.calls[0]as{target_worker_id:string}).target_worker_id,worker);assert.equal((await response.json()).version,3);});
test('both exact development origins are allowed and reflected without wildcard CORS',async()=>{for(const configuredOrigin of['http://localhost:5180','http://127.0.0.1:5180'])for(const requestOrigin of['http://localhost:5180','http://127.0.0.1:5180']){const f=fixture();f.deps.allowedOrigin=configuredOrigin;const response=await handleAnnualLeavePolicySave(req(body,{Origin:requestOrigin}),f.deps);assert.equal(response.status,200);assert.equal(response.headers.get('Access-Control-Allow-Origin'),requestOrigin);assert.notEqual(response.headers.get('Access-Control-Allow-Origin'),'*');assert.equal(f.calls.length,1);}});
test('unrelated origins remain rejected before authentication or save',async()=>{const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const response=await handleAnnualLeavePolicySave(req(body,{Origin:'https://unrelated.example'}),f.deps);assert.equal(response.status,403);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null);assert.equal(auth,0);assert.equal(f.calls.length,0);});
test('a non-development configured origin does not enable either local origin',async()=>{const f=fixture();f.deps.allowedOrigin='https://rev.example';for(const requestOrigin of['http://localhost:5180','http://127.0.0.1:5180']){const response=await handleAnnualLeavePolicySave(req(body,{Origin:requestOrigin}),f.deps);assert.equal(response.status,403);}assert.equal(f.calls.length,0);});
test('invalid conversion, calendar date, fields and revisions stop before auth',async()=>{for(const patch of[{allowanceMinutes:12599},{leaveYearStartMonth:2,leaveYearStartDay:30},{allowanceInputValue:1.23456},{expectedVersion:-1},{actorUserId:actor},{bankHolidayTreatment:'automatic'}]){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};assert.equal((await handleAnnualLeavePolicySave(req({...body,...patch}),f.deps)).status,400);assert.equal(auth,0);assert.equal(f.calls.length,0);}});
test('origin, authentication and role denial never save',async()=>{for(const mode of['origin','auth','role']){const f=fixture();if(mode==='auth')f.deps.getUserId=async()=>null;if(mode==='role')f.deps.canManage=async()=>false;const response=await handleAnnualLeavePolicySave(mode==='origin'?req(body,{Origin:'https://wrong.test'}):req(),f.deps);assert.ok(response.status>=400);assert.equal(f.calls.length,0);}});
test('mismatched or private failures remain outcome unknown without retry',async()=>{for(const mode of['workspace','version','private']){const f=fixture(),save=f.deps.save;let calls=0;f.deps.save=async input=>{calls++;if(mode==='private')throw Error('database detail');const row=await save(input)as Record<string,unknown>;row[mode==='workspace'?'workspace_id':'version']='wrong';return row;};const response=await handleAnnualLeavePolicySave(req(),f.deps);assert.equal(response.status,503);assert.equal(calls,1);assert.deepEqual(await response.json(),{error:'Annual leave policy outcome could not be confirmed.',code:'outcome_unknown'});}});
test('stale policy refusal is request-bound and definitive',async()=>{const f=fixture();f.deps.save=async()=>{throw new AnnualLeavePolicyRefusal('stale_policy');};const response=await handleAnnualLeavePolicySave(req(),f.deps);assert.equal(response.status,409);assert.deepEqual(await response.json(),{status:'refused',code:'stale_policy',requestId});});
test('arbitrary policy errors remain outcome unknown even when text resembles a refusal',async()=>{const f=fixture();f.deps.save=async()=>{throw Error('Annual leave policy changed');};const response=await handleAnnualLeavePolicySave(req(),f.deps);assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'Annual leave policy outcome could not be confirmed.',code:'outcome_unknown'});});