import {resolveAnnualLeaveOrigin} from '../_shared/annualLeaveOrigins.ts';

export interface AnnualLeavePolicyInput{target_workspace_id:string;initiating_user_id:string;target_request_id:string;target_worker_id:string|null;target_effective_from_leave_year:number;target_allowance_input_unit:'hours'|'days';target_allowance_input_value:number;target_allowance_minutes:number;target_hours_per_day_minutes:number;target_leave_year_start_month:number;target_leave_year_start_day:number;target_bank_holiday_treatment:'included'|'additional';expected_version:number;}
export interface AnnualLeavePolicyDependencies{allowedOrigin?:string;getUserId(authorization:string):Promise<string|null>;canManage(authorization:string,workspaceId:string,userId:string):Promise<boolean>;save(input:AnnualLeavePolicyInput):Promise<unknown>;}
export const annualLeavePolicyRefusalReasons={'Annual leave policy changed':'stale_policy'} as const;
export type AnnualLeavePolicyRefusalCode=typeof annualLeavePolicyRefusalReasons[keyof typeof annualLeavePolicyRefusalReasons];
export class AnnualLeavePolicyRefusal extends Error{readonly code:AnnualLeavePolicyRefusalCode;constructor(code:AnnualLeavePolicyRefusalCode){super('Annual leave policy refused');this.code=code;}}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(value:unknown):value is string=>typeof value==='string'&&uuid.test(value);
const integer=(value:unknown,min:number,max:number)=>Number.isSafeInteger(value)&&(value as number)>=min&&(value as number)<=max;
const decimal=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=10000&&Math.round(value*10000)===value*10000;
function validDatePart(month:number,day:number){const value=new Date(Date.UTC(2001,month-1,day));return value.getUTCMonth()===month-1&&value.getUTCDate()===day;}
export async function handleAnnualLeavePolicySave(request:Request,deps:AnnualLeavePolicyDependencies):Promise<Response>{
 const origin=resolveAnnualLeaveOrigin(request.headers.get('Origin'),deps.allowedOrigin);
 if(!origin)return new Response(null,{status:403});
 const headers={'Access-Control-Allow-Origin':origin,Vary:'Origin','Cache-Control':'no-store','Content-Type':'application/json'},reply=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'authorization, content-type, apikey, x-client-info'}});
 if(request.method!=='POST')return reply(405,{error:'Method not allowed.'});const authorization=request.headers.get('Authorization')??'';if(!/^Bearer\s+\S+$/i.test(authorization))return reply(401,{error:'Authentication required.'});if(request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')return reply(415,{error:'JSON required.'});
 try{const raw=await request.text();if(raw.length>4096)return reply(400,{error:'Invalid annual leave policy.'});const body=JSON.parse(raw);
  if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).sort().join(',')!=='allowanceInputUnit,allowanceInputValue,allowanceMinutes,bankHolidayTreatment,effectiveFromLeaveYear,expectedVersion,hoursPerDayMinutes,leaveYearStartDay,leaveYearStartMonth,requestId,workerId,workspaceId'
   ||!id(body.workspaceId)||!id(body.requestId)||(body.workerId!==null&&!id(body.workerId))||!integer(body.effectiveFromLeaveYear,1900,9998)||!['hours','days'].includes(body.allowanceInputUnit)||!decimal(body.allowanceInputValue)||!integer(body.allowanceMinutes,0,10000000)||!integer(body.hoursPerDayMinutes,1,1440)||!integer(body.leaveYearStartMonth,1,12)||!integer(body.leaveYearStartDay,1,31)||!validDatePart(body.leaveYearStartMonth,body.leaveYearStartDay)||!['included','additional'].includes(body.bankHolidayTreatment)||!integer(body.expectedVersion,0,Number.MAX_SAFE_INTEGER-1)
   ||(body.allowanceInputUnit==='hours'?body.allowanceInputValue*60!==body.allowanceMinutes:body.allowanceInputValue*body.hoursPerDayMinutes!==body.allowanceMinutes))return reply(400,{error:'Invalid annual leave policy.'});
  const userId=await deps.getUserId(authorization);if(!id(userId))return reply(401,{error:'Authentication required.'});if(!await deps.canManage(authorization,body.workspaceId,userId))return reply(403,{error:'Annual leave policy could not be saved.'});
  let value:unknown;try{value=await deps.save({target_workspace_id:body.workspaceId,initiating_user_id:userId,target_request_id:body.requestId,target_worker_id:body.workerId,target_effective_from_leave_year:body.effectiveFromLeaveYear,target_allowance_input_unit:body.allowanceInputUnit,target_allowance_input_value:body.allowanceInputValue,target_allowance_minutes:body.allowanceMinutes,target_hours_per_day_minutes:body.hoursPerDayMinutes,target_leave_year_start_month:body.leaveYearStartMonth,target_leave_year_start_day:body.leaveYearStartDay,target_bank_holiday_treatment:body.bankHolidayTreatment,expected_version:body.expectedVersion});}catch(error){if(error instanceof AnnualLeavePolicyRefusal&&Object.values(annualLeavePolicyRefusalReasons).includes(error.code))return reply(409,{status:'refused',code:error.code,requestId:body.requestId});throw error;}
  if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid result');const row=value as Record<string,unknown>;
  if(!id(row.policy_id)||row.workspace_id!==body.workspaceId||row.worker_id!==body.workerId||row.version!==body.expectedVersion+1||row.effective_from_leave_year!==body.effectiveFromLeaveYear||row.allowance_input_unit!==body.allowanceInputUnit||Number(row.allowance_input_value)!==body.allowanceInputValue||row.allowance_minutes!==body.allowanceMinutes||row.hours_per_day_minutes!==body.hoursPerDayMinutes||row.leave_year_start_month!==body.leaveYearStartMonth||row.leave_year_start_day!==body.leaveYearStartDay||row.bank_holiday_treatment!==body.bankHolidayTreatment)throw Error('Invalid result');
  return reply(200,{policyId:row.policy_id,workspaceId:row.workspace_id,workerId:row.worker_id,version:row.version,effectiveFromLeaveYear:row.effective_from_leave_year,allowanceInputUnit:row.allowance_input_unit,allowanceInputValue:Number(row.allowance_input_value),allowanceMinutes:row.allowance_minutes,hoursPerDayMinutes:row.hours_per_day_minutes,leaveYearStartMonth:row.leave_year_start_month,leaveYearStartDay:row.leave_year_start_day,bankHolidayTreatment:row.bank_holiday_treatment});
 }catch{return reply(503,{error:'Annual leave policy outcome could not be confirmed.',code:'outcome_unknown'});}
}