import test from 'node:test';import assert from 'node:assert/strict';
import {handleWorkerUnavailabilitySave,WorkerUnavailabilityRefusal,type UnavailabilityDependencies} from './workerUnavailabilityBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',record='55555555-5555-4555-8555-555555555555',origin='http://localhost:5180';
const body={workspaceId:ws,workerId:worker,requestId,unavailabilityId:null,startAt:'2026-10-08T09:00:00.000Z',endAt:'2026-10-08T12:00:00.000Z',category:'unavailable',status:'active',expectedVersion:0};
const req=(value:unknown=body,headers:Record<string,string>={},method='POST')=>new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(value)}:{})});
function fixture(){const calls:unknown[]=[];const deps:UnavailabilityDependencies={allowedOrigin:origin,getUserId:async()=>actor,canManage:async()=>true,save:async(input)=>{calls.push(input);return{unavailability_id:input.target_unavailability_id??record,workspace_id:input.target_workspace_id,worker_id:input.target_worker_id,start_at:input.target_start_at.replace('.000Z','+00:00'),end_at:input.target_end_at.replace('.000Z','+00:00'),category:input.target_category,status:input.target_status,version:input.expected_version+1,private:'not exposed'};}};return{calls,deps};}
test('verified actor and stable request reach scoped RPC; result has canonical UTC and no private fields',async()=>{const f=fixture();const r=await handleWorkerUnavailabilitySave(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.deepEqual(f.calls,[{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_worker_id:worker,target_unavailability_id:null,target_start_at:body.startAt,target_end_at:body.endAt,target_category:'unavailable',target_status:'active',expected_version:0}]);assert.deepEqual(await r.json(),{unavailabilityId:record,workspaceId:ws,workerId:worker,startAt:body.startAt,endAt:body.endAt,category:'unavailable',status:'active',version:1});});
test('invalid intervals, annual leave, categories, IDs, versions and injected notes or actor stop before writes',async()=>{for(const patch of [{userId:actor},{notes:'private medical detail'},{workerId:'bad'},{startAt:'2026-02-30T09:00:00.000Z'},{endAt:body.startAt},{endAt:'infinity'},{startAt:'2026-10-08T09:00:00+01:00'},{category:'leave'},{category:'sickness-details'},{status:'cancelled'},{expectedVersion:1},{unavailabilityId:record,expectedVersion:0}]){const f=fixture();assert.equal((await handleWorkerUnavailabilitySave(req({...body,...patch}),f.deps)).status,400);assert.deepEqual(f.calls,[]);}});
test('origin, method, bearer and content type refuse writes',async()=>{for(const r of [req(body,{Origin:'https://wrong.test'}),req(body,{},'GET'),req(body,{Authorization:''}),req(body,{'Content-Type':'text/plain'})]){const f=fixture();assert.ok((await handleWorkerUnavailabilitySave(r,f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('invalid session and denied management role never reach service save',async()=>{for(const mode of ['auth','role']){const f=fixture();if(mode==='auth')f.deps.getUserId=async()=>null;else f.deps.canManage=async()=>false;assert.ok((await handleWorkerUnavailabilitySave(req(),f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('preflight includes Supabase headers without authentication or writes',async()=>{const f=fixture();f.deps.getUserId=async()=>{throw new Error('unreachable');};const r=await handleWorkerUnavailabilitySave(req(body,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers')??'',/x-client-info/);assert.deepEqual(f.calls,[]);});
test('cancellation carries saved interval and expected version to durable authority',async()=>{const f=fixture();const r=await handleWorkerUnavailabilitySave(req({...body,unavailabilityId:record,expectedVersion:3,status:'cancelled'}),f.deps);assert.equal(r.status,200);const value=await r.json();assert.equal(value.status,'cancelled');assert.equal(value.version,4);assert.equal(f.calls.length,1);});
test('allowlisted assignment conflict returns a scoped definitive refusal',async()=>{const f=fixture();f.deps.save=async()=>{throw new WorkerUnavailabilityRefusal('assignment_conflict');};const r=await handleWorkerUnavailabilitySave(req(),f.deps);assert.equal(r.status,409);assert.deepEqual(await r.json(),{status:'refused',code:'assignment_conflict',requestId});});
test('RPC refusal and mismatched results refuse success once without private errors or retry',async()=>{for(const mode of ['refused','worker','workspace','id','version','time','status']){const f=fixture();const original=f.deps.save;let count=0;f.deps.save=async(input)=>{count++;if(mode==='refused')throw new Error('private database detail');const row=await original(input) as Record<string,unknown>;if(mode==='worker')row.worker_id=actor;if(mode==='workspace')row.workspace_id=actor;if(mode==='id')row.unavailability_id=actor;if(mode==='version')row.version=100;if(mode==='time')row.end_at='2026-10-08T13:00:00Z';if(mode==='status')row.status='cancelled';return row;};const r=await handleWorkerUnavailabilitySave(req({...body,unavailabilityId:record,expectedVersion:1}),f.deps);assert.equal(r.status,403);assert.equal(count,1);assert.deepEqual(await r.json(),{error:'Unavailable period could not be saved.'});}});
