import test from 'node:test';
import assert from 'node:assert/strict';
import { handleCalendarConnectionCreation, type CalendarConnectionCreationDependencies } from './calendarConnectionCreation.ts';
const workspaceId='fdce6c53-d1cb-48bc-b35a-7f57674d80f6',requestId='4d2b4b34-9f79-496b-82b0-663e71cd3b5a',userId='baf67b40-2fdf-4496-9c1d-1ac1aa5e9892',origin='http://127.0.0.1:5180';
function req(body:unknown={workspaceId,requestId},headers:Record<string,string>={},method='POST'){return new Request('https://example.test/create',{method,headers:{Origin:origin,Authorization:'Bearer fake-session','Content-Type':'application/json',...headers},...(method==='OPTIONS'?{}:{body:JSON.stringify(body)})});}
function fixture(overrides:Partial<CalendarConnectionCreationDependencies>={}){let calls=0;const deps:CalendarConnectionCreationDependencies={allowedOrigin:origin,getUserId:async()=>userId,canManage:async()=>true,create:async(input)=>{calls++;assert.deepEqual(input,{target_workspace_id:workspaceId,initiating_user_id:userId,target_request_id:requestId});return{connection_id:requestId,connection_status:'disconnected'};},...overrides};return{deps,calls:()=>calls};}
test('verified actor and stable request ID reach service RPC; only metadata returns',async()=>{const f=fixture();const r=await handleCalendarConnectionCreation(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.deepEqual(await r.json(),{connectionId:requestId,connectionStatus:'disconnected'});assert.equal(f.calls(),1);});
test('origin, bearer and injected actor fail before creation',async()=>{for(const [request,status]of [[req(undefined,{Origin:'https://evil.test'}),403],[req(undefined,{Authorization:''}),401],[req({workspaceId,requestId,userId}),400],[req({workspaceId,requestId:'bad'}),400]]as const){const f=fixture();assert.equal((await handleCalendarConnectionCreation(request,f.deps)).status,status);assert.equal(f.calls(),0);}});
test('unverified caller and denied role stop before service creation',async()=>{for(const overrides of [{getUserId:async()=>null},{canManage:async()=>false}]){const f=fixture(overrides);assert.ok((await handleCalendarConnectionCreation(req(),f.deps)).status>=400);assert.equal(f.calls(),0);}});
test('preflight includes Supabase client header and never creates',async()=>{const f=fixture();const r=await handleCalendarConnectionCreation(req(undefined,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers')!,/x-client-info/);assert.equal(f.calls(),0);});
test('RPC refusal or mismatched row fails closed without private errors',async()=>{for(const create of [async()=>{throw new Error('private database error');},async()=>({connection_id:userId,connection_status:'disconnected'}),async()=>({connection_id:requestId,connection_status:'unsafe'})]){const f=fixture({create});const r=await handleCalendarConnectionCreation(req(),f.deps);assert.equal(r.status,403);assert.deepEqual(await r.json(),{error:'Calendar connection unavailable.'});}});
