import test from 'node:test';
import assert from 'node:assert/strict';
import {handleCalendarSelection,type CalendarSelectionDependencies} from './calendarSelectionBoundary.ts';
const workspaceId='fdce6c53-d1cb-48bc-b35a-7f57674d80f6',calendarId='4d2b4b34-9f79-496b-82b0-663e71cd3b5a',userId='baf67b40-2fdf-4496-9c1d-1ac1aa5e9892',origin='http://127.0.0.1:5180';
function req(body:unknown={workspaceId,calendarId},headers:Record<string,string>={}){return new Request('https://example.test/select',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json',...headers},body:JSON.stringify(body)});}
function fixture(overrides:Partial<CalendarSelectionDependencies>={}){let calls=0;const deps:CalendarSelectionDependencies={allowedOrigin:origin,getUserId:async()=>userId,canManage:async()=>true,select:async input=>{calls++;assert.deepEqual(input,{target_workspace_id:workspaceId,initiating_user_id:userId,target_calendar_id:calendarId});return{calendar_id:calendarId,connection_id:workspaceId,is_selected:true};},...overrides};return{deps,calls:()=>calls};}
test('only identifiers and verified caller reach selection RPC',async()=>{const f=fixture();const response=await handleCalendarSelection(req(),f.deps);assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');assert.deepEqual(await response.json(),{calendarId,connectionId:workspaceId,selected:true});assert.equal(f.calls(),1);});
test('origin, session, role and injected credentials fail before mutation',async()=>{for(const [request,overrides] of [[req(undefined,{Origin:'https://evil.test'}),{}],[req(),{getUserId:async()=>null}],[req(),{canManage:async()=>false}],[req({workspaceId,calendarId,userId}),{}],[req({workspaceId,calendarId,credential:'fake'}),{}]] as const){const f=fixture(overrides);assert.ok((await handleCalendarSelection(request,f.deps)).status>=400);assert.equal(f.calls(),0);}});
test('RPC refusal and mismatched selection never return success',async()=>{for(const select of [async()=>{throw new Error('private');},async()=>({calendar_id:userId,connection_id:workspaceId,is_selected:true}),async()=>({calendar_id:calendarId,connection_id:workspaceId,is_selected:false})]){const f=fixture({select});const response=await handleCalendarSelection(req(),f.deps);assert.equal(response.status,403);assert.deepEqual(await response.json(),{error:'Calendar connection unavailable.'});}});
