import assert from 'node:assert/strict';
import test from 'node:test';
import {handleJobDocumentAccess,type JobDocumentAccessDependencies} from './jobDocumentAccessBoundary.ts';

const workspaceId='11111111-1111-4111-8111-111111111111',userId='22222222-2222-4222-8222-222222222222',jobId='33333333-3333-4333-8333-333333333333',documentId='44444444-4444-4444-8444-444444444444';
const document={documentId,workspaceId,jobId,originalName:'brief.pdf',mimeType:'application/pdf' as const,sizeBytes:1024,storagePath:`${workspaceId}/${jobId}/${documentId}/${documentId}.pdf`,status:'stored' as const,version:1 as const};
const request=(body:unknown)=>new Request('http://localhost/functions/v1/rev-scheduling-job-document-access',{method:'POST',headers:{Origin:'http://localhost:5180',Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify(body)});
const body=(action:'open'|'download'='open')=>({workspaceId,jobId,documentId,action});
function dependencies(patch:Partial<JobDocumentAccessDependencies>={}):JobDocumentAccessDependencies{return{allowedOrigin:'http://localhost:5180',getUserId:async()=>userId,canManage:async()=>true,load:async()=>document,sign:async(_path,_seconds,download)=>`https://storage.test/signed/${download?'download':'open'}`,now:()=>Date.parse('2026-10-10T00:00:00.000Z'),...patch};}

test('authorised owner receives a short-lived document-bound URL',async()=>{let signed:unknown[]=[];const response=await handleJobDocumentAccess(request(body()),dependencies({sign:async(...args)=>{signed=args;return'https://storage.test/signed/open';}}));assert.equal(response.status,200);assert.deepEqual(signed,[document.storagePath,60,null]);assert.deepEqual(await response.json(),{workspaceId,jobId,documentId,originalName:'brief.pdf',mimeType:'application/pdf',sizeBytes:1024,action:'open',url:'https://storage.test/signed/open',expiresAt:'2026-10-10T00:01:00.000Z'});assert.equal(response.headers.get('Cache-Control'),'no-store');});
test('download signing binds the original filename',async()=>{let downloadName:string|null=null;const response=await handleJobDocumentAccess(request(body('download')),dependencies({sign:async(_path,_seconds,name)=>{downloadName=name;return'https://storage.test/signed/download';}}));assert.equal(response.status,200);assert.equal(downloadName,'brief.pdf');});
test('denied and cross-workspace requests never load or sign',async()=>{let loaded=false,signed=false;const denied=await handleJobDocumentAccess(request(body()),dependencies({canManage:async()=>false,load:async()=>{loaded=true;return document;},sign:async()=>{signed=true;return'';}}));assert.equal(denied.status,403);assert.equal(loaded,false);assert.equal(signed,false);const cross=await handleJobDocumentAccess(request({...body(),workspaceId:'55555555-5555-4555-8555-555555555555'}),dependencies());assert.equal(cross.status,404);});
test('each request creates a fresh expiring URL',async()=>{let count=0;const deps=dependencies({sign:async()=>`https://storage.test/signed/${++count}`});const first=await(await handleJobDocumentAccess(request(body()),deps)).json(),second=await(await handleJobDocumentAccess(request(body()),deps)).json();assert.notEqual(first.url,second.url);assert.equal(count,2);});
test('storage signing failures are explicit',async()=>{const response=await handleJobDocumentAccess(request(body()),dependencies({sign:async()=>{throw Error('expired service');}}));assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'A temporary document link could not be created.'});});
