import {useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {loadSchedulingWorkers,type Worker} from '@/services/schedulingWorkers';
import {loadWorkingPattern} from '@/services/workerWorkingPatterns';
import type {SchedulingJob} from '@/services/schedulingJobs';
import {loadAssignments,submitAssignmentAttempt,rememberAssignment,restoreAssignment,clearAssignment,AllocationRefused,type Assignment,type AssignmentAttempt} from '@/services/schedulingAssignments';
export function JobAssignmentsPanel({workspaceId,userId,job,disabled=false}:{workspaceId:string;userId:string;job:SchedulingJob;disabled?:boolean}){
 const [workers,setWorkers]=useState<Worker[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[pending,setPending]=useState<AssignmentAttempt|null>(null),[selected,setSelected]=useState(''),[cancel,setCancel]=useState<Assignment|null>(null),[message,setMessage]=useState('');
 const mounted=useRef(true),lock=useRef(false);
 const readWorkers=()=>loadSchedulingWorkers(workspaceId,async(columns,ws)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_workers').select(columns).eq('workspace_id',ws);if(error)throw Error('Unavailable');return data;});
 const reload=async()=>{const [people,rows]=await Promise.all([readWorkers(),loadAssignments(workspaceId,job.jobId,async(columns,ws,id)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_assignments').select(columns).eq('workspace_id',ws).eq('job_id',id);if(error)throw Error('Unavailable');return data;})]);if(mounted.current){setWorkers(people);setAssignments(rows);setReady(true);}};
 useEffect(()=>{mounted.current=true;void(async()=>{try{const a=restoreAssignment(window.sessionStorage,workspaceId,userId,job.jobId);if(a&&mounted.current){setPending(a);setMessage('An assignment save is unconfirmed. Retry the same request first.');}}catch{if(mounted.current){setBlocked(true);setMessage('Pending allocation could not be read. Contact support.');}}try{await reload();}catch{if(mounted.current)setMessage('Assignments could not be loaded. Refresh to try again.');}})();return()=>{mounted.current=false;};},[workspaceId,userId,job.jobId]);
 const save=async(cancelling:Assignment|null=null)=>{if(lock.current||!ready||disabled||blocked)return;lock.current=true;setBusy(true);setMessage('');let attempt=pending;
 try{if(!attempt){if(cancelling){attempt={workspaceId,workerId:cancelling.workerId,jobId:job.jobId,requestId:crypto.randomUUID(),assignmentId:cancelling.assignmentId,status:'cancelled',expectedVersion:cancelling.version,expectedWorkerVersion:null,expectedJobVersion:null,expectedPatternVersion:null,expectedStartAt:cancelling.startAt,expectedEndAt:cancelling.endAt};}
 else{if(job.status!=='open'||!selected)throw Error('Choose worker');const people=await readWorkers(),worker=people.find(w=>w.workerId===selected);if(!worker?.active||!job.requiredSkills.every(s=>worker.skillTags.includes(s)))throw Error('Worker not suitable');const pattern=await loadWorkingPattern(workspaceId,selected,async(columns,ws,id)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_worker_patterns').select(columns).eq('workspace_id',ws).eq('worker_id',id);if(error)throw Error('Unavailable');return data;});if(!pattern)throw Error('Working pattern required');attempt={workspaceId,workerId:selected,jobId:job.jobId,requestId:crypto.randomUUID(),assignmentId:null,status:'active',expectedVersion:0,expectedWorkerVersion:worker.version,expectedJobVersion:job.version,expectedPatternVersion:pattern.version,expectedStartAt:job.startAt,expectedEndAt:job.endAt};}
 rememberAssignment(window.sessionStorage,userId,attempt);if(mounted.current)setPending(attempt);}
 await submitAssignmentAttempt(attempt,async(name,body)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error){const context=(error as {context?:unknown}).context;if(context instanceof Response&&context.status===409)return {status:409,data:await context.clone().json()};throw Error('Uncertain result');}return {status:200,data};});
 clearAssignment(window.sessionStorage,workspaceId,userId,job.jobId);if(!mounted.current)return;setPending(null);setCancel(null);setSelected('');setMessage(cancelling||attempt.status==='cancelled'?'Assignment cancelled. No notification was sent.':'Worker assigned. No notification was sent.');try{await reload();}catch{if(mounted.current){setReady(false);setMessage('Saved. Refresh to reload assignments.');}}
 }catch(error){if(!mounted.current)return;if(error instanceof AllocationRefused){try{clearAssignment(window.sessionStorage,workspaceId,userId,job.jobId);setPending(null);setCancel(null);setMessage(error.message);}catch{setBlocked(true);setMessage('Allocation refused, but pending information could not be cleared. Contact support.');}try{await reload();}catch{setReady(false);}}
 else{let remembered=false;try{remembered=restoreAssignment(window.sessionStorage,workspaceId,userId,job.jobId)!==null;}catch{setBlocked(true);remembered=true;}setMessage(remembered?'Outcome unconfirmed. Retry the same request without creating a replacement assignment.':'Choose an active worker with the required skills and a saved working pattern. Refresh if their details changed.');}}
 finally{lock.current=false;if(mounted.current)setBusy(false);}};
 const controlsDisabled=busy||disabled||blocked||!ready||!!pending;
 const activeRows=assignments.filter(a=>a.status==='active');
 const candidates=workers.filter(w=>w.active&&job.requiredSkills.every(s=>w.skillTags.includes(s))&&!activeRows.some(a=>a.workerId===w.workerId));
 return <div className="border-t mt-3 pt-3"><h4 className="font-medium">Worker allocation</h4><p className="text-sm">Assigned: {activeRows.length} / {job.staffingCount}. Final availability and conflict checks run when saving.</p>{message&&<p role="status" className="my-2">{message}</p>}
 {pending&&<button className="btn-secondary my-2" disabled={busy||disabled||blocked||!ready} onClick={()=>void save()}>RETRY SAME ASSIGNMENT SAVE</button>}
 <ul className="my-2">{activeRows.map(a=><li key={a.assignmentId} className="my-2">{workers.find(w=>w.workerId===a.workerId)?.displayName||'Worker unavailable'} <button className="btn-secondary ml-2" disabled={controlsDisabled||!!cancel} onClick={()=>setCancel(a)}>CANCEL ASSIGNMENT</button></li>)}</ul>
 {job.status==='open'&&<><label className="block my-2">Worker<select className="block border rounded p-2 w-full" value={selected} disabled={controlsDisabled||!!cancel||activeRows.length>=job.staffingCount} onChange={e=>setSelected(e.target.value)}><option value="">Choose worker</option>{candidates.map(w=><option key={w.workerId} value={w.workerId}>{w.displayName}</option>)}</select></label><button className="btn-secondary" disabled={controlsDisabled||!!cancel||!selected||activeRows.length>=job.staffingCount} onClick={()=>void save()}>ASSIGN WORKER</button></>}
 {cancel&&<div role="group" aria-label="Confirm assignment cancellation" className="my-2"><p>Cancel this assignment? The job stays open and history is retained.</p><button className="btn-secondary" disabled={controlsDisabled} onClick={()=>void save(cancel)}>CONFIRM ASSIGNMENT CANCELLATION</button><button className="btn-secondary ml-2" disabled={controlsDisabled} onClick={()=>setCancel(null)}>KEEP ASSIGNMENT</button></div>}
 <button className="btn-secondary my-2 ml-2" disabled={busy||disabled} onClick={()=>{void reload().catch(()=>{if(mounted.current){setReady(false);setMessage('Refresh failed. Reload the page to try again.');}});}}>REFRESH ALLOCATION</button>
 {assignments.some(a=>a.status==='cancelled')&&<p className="text-sm">Cancelled assignment history retained.</p>}
 </div>;
}
