import {useCallback,useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {loadPlannerData,plannerMonday,addPlannerDays,localPlannerDate,spansPlannerDay,jobVacancies,workerSetupIssue,assignmentConflict,type PlannerData,type PlannerJob} from '@/services/schedulingPlanner';
import {formatSchedulingDate,formatSchedulingInstant,formatSchedulingTime} from '@/services/schedulingDisplay';
function openWorker(workerId:string){const card=document.getElementById(`scheduling-worker-${workerId}`);const details=card?.querySelector('details');if(details)details.open=true;card?.scrollIntoView({behavior:'smooth',block:'start'});}
function openJob(jobId:string){document.getElementById(`scheduling-job-${jobId}`)?.scrollIntoView({behavior:'smooth',block:'start'});}
export function SchedulingWeeklyPlanner({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<PlannerData|null>(null),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[updated,setUpdated]=useState<string|null>(null),[message,setMessage]=useState(''),[timezone,setTimezone]=useState('Europe/London'),[week,setWeek]=useState(()=>plannerMonday(localPlannerDate(new Date().toISOString(),'Europe/London'))),[workerFilter,setWorkerFilter]=useState(''),[locationFilter,setLocationFilter]=useState('');
 const mounted=useRef(true),sequence=useRef(0),running=useRef(false),refreshAgain=useRef(false);
 const reload=useCallback(async()=>{if(running.current){refreshAgain.current=true;return;}running.current=true;const token=++sequence.current;setBusy(true);
 try{const loaded=await loadPlannerData(workspaceId,async(table,columns,ws,from,to)=>{if(!supabaseClient)throw Error('Unavailable');const {data:rows,error}=await supabaseClient.from(table).select(columns).eq('workspace_id',ws).order('id',{ascending:true}).range(from,to);if(error)throw Error('Unavailable');return rows;});if(mounted.current&&token===sequence.current){setData(loaded);setStale(false);setUpdated(new Date().toISOString());setMessage('Planner updated.');}}
 catch{if(mounted.current&&token===sequence.current){setStale(true);setMessage('Planner could not be updated. Any visible schedule is the last successful view. Refresh before relying on it.');}}
 finally{if(token===sequence.current){running.current=false;if(mounted.current){setBusy(false);if(refreshAgain.current){refreshAgain.current=false;window.setTimeout(()=>window.dispatchEvent(new Event('rev-scheduling-changed')),0);}}}}},[workspaceId]);
 useEffect(()=>{mounted.current=true;void reload();const refresh=()=>{if(document.visibilityState!=='hidden')void reload();};const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);window.addEventListener('rev-scheduling-changed',refresh);document.addEventListener('visibilitychange',refresh);return()=>{mounted.current=false;sequence.current++;running.current=false;refreshAgain.current=false;window.clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('rev-scheduling-changed',refresh);document.removeEventListener('visibilitychange',refresh);};},[reload]);
 const days=Array.from({length:7},(_,i)=>addPlannerDays(week,i));
 const activeAssignments=data?.assignments.filter(a=>a.status==='active')??[];
 const jobs=data?.jobs.filter(j=>j.status==='open'&&(!locationFilter||j.location===locationFilter))??[];
 const visibleJobs=jobs.filter(j=>days.some(day=>spansPlannerDay(j.startAt,j.endAt,day,timezone)));
 const visibleWorkers=data?.workers.filter(w=>(w.active||activeAssignments.some(a=>a.workerId===w.id&&days.some(day=>spansPlannerDay(a.startAt,a.endAt,day,timezone))))&&(!workerFilter||w.id===workerFilter)).sort((a,b)=>a.name.localeCompare(b.name))??[];
 const time=(value:string)=>formatSchedulingTime(value,timezone);
 const card=(job:PlannerJob,label:string,conflict=false)=><button type="button" onClick={()=>openJob(job.id)} disabled={stale} className={`block w-full text-left rounded-lg border p-2 mb-2 text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${conflict?'bg-red-50 border-red-300 text-red-900':label==='Assigned'?'bg-blue-50 border-blue-200 text-blue-950':'bg-amber-50 border-amber-300 text-amber-950'}`}><span className="block font-semibold">{conflict?'Review needed':label}</span><span className="block font-medium">{job.title}</span><span className="block">{time(job.startAt)}-{time(job.endAt)}</span><span className="block">{job.location}</span>{localPlannerDate(job.startAt,timezone)!==localPlannerDate(new Date(Date.parse(job.endAt)-1).toISOString(),timezone)&&<span className="block">Continues across days</span>}<span className="block mt-1 underline">View job</span></button>;
 return <section className="rounded-xl border border-slate-200 bg-white shadow-sm my-6" aria-label="Weekly scheduling planner"><div className="p-4 sm:p-6 border-b border-slate-200"><h2 className="text-xl font-semibold text-slate-900">Weekly planner</h2><p className="text-sm text-slate-600 mt-1">Saved work, assignments and unavailable periods. Select a job card to manage it below.</p>
 <div className="flex flex-wrap items-end gap-3 mt-4"><button className="btn-secondary" onClick={()=>setWeek(addPlannerDays(week,-7))}>Previous week</button><label className="text-sm">Week beginning<input aria-label="Week beginning" className="block border rounded p-2" type="date" value={week} onChange={e=>{if(e.target.value){try{setWeek(plannerMonday(e.target.value));}catch{setMessage('Choose a valid week.');}}}}/></label><button className="btn-secondary" onClick={()=>setWeek(addPlannerDays(week,7))}>Next week</button><button className="btn-secondary" onClick={()=>setWeek(plannerMonday(localPlannerDate(new Date().toISOString(),timezone)))}>This week</button><label className="text-sm">Display timezone<select className="block border rounded p-2" value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Europe/London</option><option>UTC</option><option>America/New_York</option></select></label><button className="btn-primary" disabled={busy} onClick={()=>void reload()}>{busy?'Updating…':'REFRESH PLANNER'}</button></div>
 <div className="flex flex-wrap gap-3 mt-3"><label className="text-sm">Worker<select className="block border rounded p-2" value={workerFilter} onChange={e=>setWorkerFilter(e.target.value)}><option value="">All workers</option>{data?.workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-sm">Location<select className="block border rounded p-2" value={locationFilter} onChange={e=>setLocationFilter(e.target.value)}><option value="">All locations</option>{[...new Set(data?.jobs.filter(j=>j.status==='open').map(j=>j.location)??[])].sort().map(location=><option key={location} value={location}>{location}</option>)}</select></label></div>
 <p role="status" className={`text-sm mt-3 ${stale?'text-red-800':'text-slate-600'}`}>{busy?'Updating planner…':message} {updated&&`Last successful update: ${new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(updated))} (${timezone}).`}</p><p className="text-xs text-slate-500 mt-1">Refreshes every 30 seconds while this page is visible and after saved changes. Cancelled records are kept in history below.</p>
 <div className="flex flex-wrap gap-2 mt-3 text-xs"><span className="rounded px-2 py-1 bg-blue-50 text-blue-950 border border-blue-200">Assigned</span><span className="rounded px-2 py-1 bg-amber-50 text-amber-950 border border-amber-300">Unfilled</span><span className="rounded px-2 py-1 bg-purple-50 text-purple-950 border border-purple-200">Leave</span><span className="rounded px-2 py-1 bg-slate-100 text-slate-800 border border-slate-300">Unavailable</span><span className="rounded px-2 py-1 bg-red-50 text-red-950 border border-red-300">Review needed</span></div></div>
 {data&&<div className="overflow-x-auto"><table className="w-full border-collapse text-sm" style={{minWidth:1100}}><caption className="sr-only">Weekly schedule in {timezone}, week beginning {formatSchedulingDate(week)}</caption><thead><tr className="bg-slate-50"><th scope="col" className="text-left p-3 border-b w-44">Worker / work</th>{days.map(day=><th key={day} scope="col" className="text-left p-3 border-b">{formatSchedulingDate(day)}</th>)}</tr></thead><tbody>
 <tr><th scope="row" className="text-left p-3 border-b align-top text-amber-900">Unfilled work<p className="text-xs font-normal">{visibleJobs.reduce((sum,j)=>sum+jobVacancies(data,j),0)} places still needed</p></th>{days.map(day=><td key={day} className="p-2 border-b border-l align-top">{visibleJobs.filter(j=>jobVacancies(data,j)>0&&spansPlannerDay(j.startAt,j.endAt,day,timezone)).map(j=><div key={j.id}>{card(j,`Unfilled: ${jobVacancies(data,j)}`)}</div>)}</td>)}</tr>
 {visibleWorkers.map(w=><tr key={w.id}><th scope="row" className="text-left p-3 border-b align-top"><span className="font-semibold text-slate-900">{w.name}</span>{workerSetupIssue(data,w.id,week)&&<><p className="text-xs text-amber-800 mt-1">{workerSetupIssue(data,w.id,week)}</p><button className="text-xs underline text-blue-800 mt-1" onClick={()=>openWorker(w.id)}>SET WORKING HOURS</button></>}</th>{days.map(day=><td key={day} className="p-2 border-b border-l align-top">{activeAssignments.filter(a=>a.workerId===w.id&&jobs.some(j=>j.id===a.jobId)&&spansPlannerDay(a.startAt,a.endAt,day,timezone)).map(a=>{const j=jobs.find(j=>j.id===a.jobId)!;return <div key={a.id}>{card(j,'Assigned',assignmentConflict(data,a))}</div>;})}{data.leave.filter(l=>l.workerId===w.id&&l.status==='active'&&spansPlannerDay(l.startAt,l.endAt,day,timezone)).map(l=><div key={l.id} className={`rounded-lg border p-2 mb-2 text-xs ${l.category==='leave'?'bg-purple-50 text-purple-950 border-purple-200':'bg-slate-100 text-slate-800 border-slate-300'}`}><p className="font-semibold">{l.category==='leave'?'Leave':'Unavailable'}</p><p>{formatSchedulingInstant(l.startAt,timezone)} to {formatSchedulingInstant(l.endAt,timezone)}</p></div>)}</td>)}</tr>)}
 </tbody></table>{visibleWorkers.length===0&&<p className="p-4 text-sm text-slate-600">No workers match this view.</p>}{visibleJobs.length===0&&<p className="p-4 text-sm text-slate-600">No open jobs in this week and location.</p>}</div>}
 {!data&&!busy&&<p className="p-4 text-sm">Planner unavailable. Use Refresh planner to try again.</p>}
 </section>;
}
