import {useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {
 clearAnalysisAttempt,clearConfirmationAttempt,clearJobDocumentUpload,createJobDocumentAttempt,DocumentAnalysisRefused,DocumentAnalysisUnavailable,
 checkDocumentAnalysisAvailability,loadCurrentRequirementReview,loadJobDocumentAnalyses,loadJobDocuments,
 requestJobDocumentAccess,
 rememberAnalysisAttempt,rememberConfirmationAttempt,rememberJobDocumentUpload,RequirementConfirmationRefused,
 restoreAnalysisAttempt,restoreConfirmationAttempt,restoreJobDocumentUpload,submitAnalysisAttempt,submitConfirmationAttempt,submitJobDocumentUpload,
 type AnalysisAttempt,type ConfirmationAttempt,type EvidenceText,type JobDocument,type JobDocumentAnalysis,type JobDocumentUploadAttempt,type JobRequirementReview,
} from '@/services/schedulingJobDocuments';
import type {SchedulingJob} from '@/services/schedulingJobs';

const invoke=async(name:string,body:Record<string,unknown>)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error){const context=(error as {context?:unknown}).context;if(context instanceof Response)return{status:context.status,data:await context.clone().json().catch(()=>null)};throw Error('Unavailable');}return{status:200,data};};
const reference=(item:EvidenceText)=>item.references.map(value=>[value.page?`page ${value.page}`:'',value.section?`section “${value.section}”`:''].filter(Boolean).join(', ')).join('; ');
const evidenceList=(label:string,items:EvidenceText[])=><div className="mt-2"><h6 className="font-medium">{label}</h6>{items.length?<ul className="list-disc pl-5">{items.map((item,index)=><li key={`${item.value}-${index}`}>{item.value} <span className="text-neutral-600">({reference(item)})</span></li>)}</ul>:<p>None extracted.</p>}</div>;

export function SchedulingJobDocumentsPanel({workspaceId,userId,job,disabled,onConfirmed}:{workspaceId:string;userId:string;job:SchedulingJob;disabled:boolean;onConfirmed?:(review:JobRequirementReview)=>void}){
 const [documents,setDocuments]=useState<JobDocument[]>([]),[analyses,setAnalyses]=useState<JobDocumentAnalysis[]>([]),[review,setReview]=useState<JobRequirementReview|null>(null);
 const [pendingUpload,setPendingUpload]=useState<JobDocumentUploadAttempt|null>(null),[pendingAnalysis,setPendingAnalysis]=useState<AnalysisAttempt|null>(null),[pendingConfirmation,setPendingConfirmation]=useState<ConfirmationAttempt|null>(null);
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[accessBusy,setAccessBusy]=useState(''),[message,setMessage]=useState(''),[loadedFor,setLoadedFor]=useState(''),[availability,setAvailability]=useState<{available:boolean;model:string|null}|null>(null),[textPreview,setTextPreview]=useState<{documentId:string;name:string;text:string}|null>(null);
 const mounted=useRef(true),contextRef=useRef(''),contextKey=`${workspaceId}:${job.jobId}`;contextRef.current=contextKey;
 const read=async(table:string,columns:string,jobId:string,current=false)=>{if(!supabaseClient)throw Error('Unavailable');let query=supabaseClient.from(table).select(columns).eq('workspace_id',workspaceId).eq('job_id',jobId);if(current)query=query.eq('current',true);const {data,error}=await query.order('created_at',{ascending:false});if(error)throw Error('Unavailable');return data;};
 const reload=async()=>{const requestedContext=contextKey,[stored,history,current]=await Promise.all([loadJobDocuments(workspaceId,job.jobId,(columns,_ws,id)=>read('scheduling_job_documents',columns,id)),loadJobDocumentAnalyses(workspaceId,job.jobId,(columns,_ws,id)=>read('scheduling_job_document_analyses',columns,id)),loadCurrentRequirementReview(workspaceId,job.jobId,(columns,_ws,id)=>read('scheduling_job_requirement_reviews',columns,id,true))]);if(mounted.current&&contextRef.current===requestedContext){setDocuments(stored);setAnalyses(history);setReview(current);setLoadedFor(requestedContext);if(current)onConfirmed?.(current);}};
 useEffect(()=>{mounted.current=true;setLoadedFor('');setTextPreview(null);setAccessBusy('');void(async()=>{try{const upload=restoreJobDocumentUpload(window.sessionStorage,workspaceId,userId,job.jobId),analysis=restoreAnalysisAttempt(window.sessionStorage,workspaceId,userId,job.jobId),confirmation=restoreConfirmationAttempt(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current&&contextRef.current===contextKey){setPendingUpload(upload);setPendingAnalysis(analysis);setPendingConfirmation(confirmation);if(upload||analysis||confirmation)setMessage('An earlier document action is not confirmed. Use its exact retry control.');}}catch{if(mounted.current&&contextRef.current===contextKey)setMessage('A retained document action could not be read. Do not start another action; contact support.');}try{await reload();}catch{if(mounted.current&&contextRef.current===contextKey)setMessage('Job documents or requirement history could not be loaded. Refresh before relying on this view.');}try{const status=await checkDocumentAnalysisAvailability(workspaceId,job.jobId,invoke);if(mounted.current&&contextRef.current===contextKey)setAvailability(status);}catch{if(mounted.current&&contextRef.current===contextKey)setAvailability({available:false,model:null});}})();return()=>{mounted.current=false;};},[workspaceId,userId,job.jobId]);
 const upload=async(retry=false)=>{if(busy||disabled)return;let attempt=retry?pendingUpload:null;if(!attempt){if(!file){setMessage('Choose a supported document first.');return;}try{attempt=await createJobDocumentAttempt(file,workspaceId,job.jobId,crypto.randomUUID());rememberJobDocumentUpload(window.sessionStorage,userId,attempt);setPendingUpload(attempt);}catch(error){setMessage(error instanceof Error?error.message:'The document could not be prepared safely.');return;}}setBusy(true);setMessage('Uploading the private job document...');try{const saved=await submitJobDocumentUpload(attempt,invoke);clearJobDocumentUpload(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current&&contextRef.current===contextKey){setPendingUpload(null);setFile(null);setDocuments(current=>[saved,...current.filter(document=>document.documentId!==saved.documentId)]);setLoadedFor(contextKey);setMessage(availability?.available?'Document stored privately. Select Analyse document to extract evidence.':'Document stored privately. AI analysis remains unavailable until the server provider is configured.');}}catch{if(mounted.current&&contextRef.current===contextKey)setMessage('Upload outcome unconfirmed. Retry the exact retained upload; do not choose a replacement file.');}finally{if(mounted.current&&contextRef.current===contextKey)setBusy(false);}};
 const analyse=async(document:JobDocument,retry=false)=>{if(busy||disabled)return;let attempt=retry?pendingAnalysis:null;if(!attempt){attempt={workspaceId,jobId:job.jobId,documentId:document.documentId,documentVersion:1,jobVersion:job.version,requestId:crypto.randomUUID()};try{rememberAnalysisAttempt(window.sessionStorage,userId,attempt);setPendingAnalysis(attempt);}catch{setMessage('Analysis was not started because its exact retry details could not be retained.');return;}}setBusy(true);setMessage('Analysing the untrusted document as evidence...');try{const result=await submitAnalysisAttempt(attempt,invoke);clearAnalysisAttempt(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current){setPendingAnalysis(null);setAnalyses(current=>[result,...current.filter(value=>value.analysisId!==result.analysisId)]);setMessage('Requirements extracted for manager review. Nothing has been confirmed or assigned.');}}catch(error){if(error instanceof DocumentAnalysisUnavailable||error instanceof DocumentAnalysisRefused){clearAnalysisAttempt(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current){setPendingAnalysis(null);setMessage(error instanceof DocumentAnalysisUnavailable?'AI analysis is not configured. No provider request was made.':`Analysis stopped: ${error.code.replace(/_/g,' ')}. Start a new analysis only after reviewing the cause.`);}}else if(mounted.current)setMessage('Analysis outcome unconfirmed. The exact request is retained and no automatic second provider attempt will be made.');}finally{if(mounted.current)setBusy(false);}};
 const confirm=async(analysis:JobDocumentAnalysis,retry=false)=>{if(!analysis.extraction||analysis.status!=='succeeded'||analysis.jobVersion!==job.version)return;let attempt=retry?pendingConfirmation:null;if(!attempt){attempt={workspaceId,jobId:job.jobId,analysisId:analysis.analysisId,analysisVersion:2,requirements:analysis.extraction,expectedCurrentReviewId:review?.reviewId??null,expectedCurrentRevision:review?.revision??0,requestId:crypto.randomUUID()};try{rememberConfirmationAttempt(window.sessionStorage,userId,attempt);setPendingConfirmation(attempt);}catch{setMessage('Confirmation was not started because its exact retry details could not be retained.');return;}}setBusy(true);setMessage('Confirming the reviewed requirements...');try{const saved=await submitConfirmationAttempt(attempt,invoke);clearConfirmationAttempt(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current){setPendingConfirmation(null);setReview(saved);onConfirmed?.(saved);window.dispatchEvent(new Event('rev-scheduling-changed'));setMessage('Requirements confirmed. Worker recommendations now use the confirmed skills. No worker was assigned.');}}catch(error){if(error instanceof RequirementConfirmationRefused){clearConfirmationAttempt(window.sessionStorage,workspaceId,userId,job.jobId);if(mounted.current){setPendingConfirmation(null);setMessage(error.code==='stale'?'Not confirmed. The job changed after analysis; analyse the current job and document again.':'Not confirmed. Another requirement review changed first; refresh and review it.');}}else if(mounted.current)setMessage('Confirmation outcome unconfirmed. Retry the exact retained confirmation; do not create a replacement.');}finally{if(mounted.current)setBusy(false);}};
 const access=async(document:JobDocument,action:'open'|'download')=>{if(disabled||accessBusy)return;const requestedContext=contextKey,setKey=`${document.documentId}:${action}`;setAccessBusy(setKey);setMessage(action==='open'?'Creating a private viewing link...':'Preparing a private download...');if(action==='open')setTextPreview(null);try{const link=await requestJobDocumentAccess(document,action,invoke);if(!mounted.current||contextRef.current!==requestedContext)return;if(action==='download'){const anchor=window.document.createElement('a');anchor.href=link.url;anchor.download=document.originalName;anchor.rel='noopener';window.document.body.appendChild(anchor);anchor.click();anchor.remove();setMessage(`Download started for ${document.originalName}. The private link expires shortly.`);}else if(document.mimeType==='application/pdf'){const anchor=window.document.createElement('a');anchor.href=link.url;anchor.target='_blank';anchor.rel='noopener noreferrer';window.document.body.appendChild(anchor);anchor.click();anchor.remove();setMessage(`${document.originalName} opened in a new tab. The private link expires shortly.`);}else{const response=await fetch(link.url,{cache:'no-store'});if(!response.ok)throw Error('The temporary link expired before the document opened. Select Open document again.');const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length!==document.sizeBytes)throw Error('The downloaded text did not match the stored document.');let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw Error('The stored text document is not valid UTF-8.');}if(!mounted.current||contextRef.current!==requestedContext)return;setTextPreview({documentId:document.documentId,name:document.originalName,text});setMessage(`${document.originalName} opened safely as plain text. The temporary link is not stored.`);}}catch(error){if(mounted.current&&contextRef.current===requestedContext)setMessage(error instanceof Error?error.message:'The job document could not be opened.');}finally{if(mounted.current&&contextRef.current===requestedContext)setAccessBusy('');}};
 const visibleDocuments=loadedFor===contextKey?documents:[],latest=loadedFor===contextKey?analyses.find(value=>value.status==='succeeded'&&value.extraction)??null:null,confirmedLatest=Boolean(latest&&review?.analysisId===latest.analysisId),stale=latest?latest.jobVersion!==job.version&&!confirmedLatest:false;
 return <details className="rounded-lg border border-neutral-200 p-3"><summary className="cursor-pointer font-medium">Job documents and requirement review</summary>
  <p className="mt-2 text-sm">Owners and admins can attach a private PDF or UTF-8 text brief to this existing job. Maximum size: 2 MB. Documents are untrusted evidence, never instructions to REV.</p>
  {availability&&!availability.available&&<p role="status" className="mt-2 rounded border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900"><strong>AI analysis unavailable.</strong> Configure the reviewed server provider before extraction. REV will not fabricate requirements.</p>}
  {availability?.available&&<p role="status" className="mt-2 rounded border border-blue-300 bg-blue-50 p-2 text-sm"><strong>AI extraction available:</strong> {availability.model}. Extracted evidence still requires manager confirmation.</p>}
  {!pendingUpload&&<div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-sm font-medium">Choose PDF or text document<input aria-label={`Choose document for ${job.title}`} className="mt-1 block" type="file" accept=".pdf,.txt,application/pdf,text/plain" disabled={disabled||busy} onChange={event=>{setFile(event.target.files?.[0]??null);setMessage('');}}/></label><button type="button" className="btn-secondary" disabled={disabled||busy||!file} onClick={()=>void upload(false)}>{busy?'WORKING...':'UPLOAD DOCUMENT'}</button></div>}
  {pendingUpload&&<div role="alert" className="mt-3 rounded border border-amber-400 bg-amber-50 p-3 text-sm"><p>Upload outcome unconfirmed. Exact bytes and request identity are retained.</p><button type="button" className="btn-primary mt-2" disabled={disabled||busy} onClick={()=>void upload(true)}>RETRY SAME DOCUMENT UPLOAD</button></div>}
  <div className="mt-3"><h5 className="text-sm font-medium">Stored source documents</h5>{loadedFor===contextKey?(visibleDocuments.length?<ul className="mt-1 space-y-2 text-sm">{visibleDocuments.map(document=><li key={document.documentId} className="rounded border p-2"><div><span className="font-medium">{document.originalName}</span><span> — {document.mimeType==='application/pdf'?'PDF':'Plain text'} — {(document.sizeBytes/1024).toFixed(1)} KB</span></div><div className="mt-2 flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={disabled||!!accessBusy} onClick={()=>void access(document,'open')}>{accessBusy===`${document.documentId}:open`?'OPENING...':'OPEN DOCUMENT'}</button><button type="button" className="btn-secondary" disabled={disabled||!!accessBusy} onClick={()=>void access(document,'download')}>{accessBusy===`${document.documentId}:download`?'PREPARING...':'DOWNLOAD'}</button>{availability?.available&&!pendingAnalysis&&<button type="button" className="btn-secondary" disabled={disabled||busy} onClick={()=>void analyse(document,false)}>ANALYSE DOCUMENT</button>}</div></li>)}</ul>:<p className="mt-1 text-sm">No job documents stored.</p>):<p className="mt-1 text-sm">Loading stored documents...</p>}{textPreview&&visibleDocuments.some(document=>document.documentId===textPreview.documentId)&&<div className="mt-3 rounded border border-neutral-300 bg-neutral-50 p-3"><div className="flex items-center justify-between gap-2"><h6 className="font-medium">{textPreview.name}</h6><button type="button" className="btn-secondary" onClick={()=>setTextPreview(null)}>Close text</button></div><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-words text-sm">{textPreview.text}</pre></div>}</div>
  {pendingAnalysis&&<div role="alert" className="mt-3 rounded border border-amber-400 bg-amber-50 p-3 text-sm"><p>Analysis outcome is not confirmed. Retrying checks the durable request and never creates an automatic second provider attempt.</p><button type="button" className="btn-primary mt-2" disabled={disabled||busy} onClick={()=>{const document=documents.find(value=>value.documentId===pendingAnalysis.documentId);if(document)void analyse(document,true);}}>RETRY SAME ANALYSIS REQUEST</button></div>}
  <section className="mt-3 border-t pt-3 text-sm"><h5 className="font-medium">AI-extracted requirements {confirmedLatest?'— confirmed in the current review':'— not confirmed'}</h5>{latest?.extraction?<div>{stale&&<p role="alert" className="mt-1 text-amber-800">Stale analysis: the job changed after this extraction. It cannot replace current job requirements.</p>}{evidenceList('Tasks',latest.extraction.tasks)}{evidenceList('Required skills',latest.extraction.requiredSkills)}{evidenceList('Qualifications',latest.extraction.qualifications)}{latest.extraction.location&&evidenceList('Location',[latest.extraction.location])}{evidenceList('Dates',latest.extraction.dates)}{latest.extraction.duration&&evidenceList('Duration',[latest.extraction.duration])}<div className="mt-2"><strong>Missing information:</strong> {latest.extraction.missingInformation.join('; ')||'None flagged'}</div>{evidenceList('Ambiguities',latest.extraction.ambiguities)}{!stale&&!confirmedLatest&&!pendingConfirmation&&<button type="button" className="btn-primary mt-3" disabled={disabled||busy} onClick={()=>void confirm(latest,false)}>CONFIRM REVIEWED REQUIREMENTS</button>}</div>:<p className="mt-1">No successful extraction available.</p>}</section>
  {pendingConfirmation&&latest&&<div role="alert" className="mt-3 rounded border border-amber-400 bg-amber-50 p-3 text-sm"><p>Requirement confirmation is not confirmed. Its exact reviewed evidence is retained.</p><button type="button" className="btn-primary mt-2" disabled={disabled||busy} onClick={()=>void confirm(latest,true)}>RETRY SAME CONFIRMATION</button></div>}
  <section className="mt-3 border-t pt-3 text-sm"><h5 className="font-medium">Manager-confirmed requirements</h5>{review?<div><p>Review revision {review.revision}. These are separate from the AI extraction and are the current recommendation evidence.</p>{evidenceList('Confirmed skills',review.requirements.requiredSkills)}{review.requirements.qualifications.length>0&&<p className="mt-2 text-amber-800">Qualifications are required, but worker qualification evidence is not recorded. Suitability remains unknown and assignment is blocked.</p>}</div>:<p className="mt-1">No requirements confirmed.</p>}</section>
  <p className="mt-3 text-xs text-neutral-600">Assignment always uses the existing manager-controlled workflow. No analysis or confirmation assigns, cancels or changes a booking automatically.</p>{message&&<p role="status" className="mt-2 text-sm">{message}</p>}
 </details>;
}
