import {JobAssignmentsPanel} from './JobAssignmentsPanel';
import {useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {loadSchedulingJobs,submitJobAttempt,rememberJobAttempt,restoreJobAttempt,clearJobAttempt,type SchedulingJob,type JobAttempt} from '@/services/schedulingJobs';
import {clearDailySessionAttempt,previewDailySessions,rememberDailySessionAttempt,restoreDailySessionAttempt,submitDailySessionAttempt,type DailySessionAttempt} from '@/services/schedulingDailySessions';
import {localLeaveToUtc,utcLeaveToLocal} from '@/services/workerUnavailability';
import {formatSchedulingDate,formatSchedulingLocal} from '@/services/schedulingDisplay';

interface Draft{job:SchedulingJob|null;title:string;start:string;end:string;timezone:string;location:string;skills:string;count:string;firstDay:string;lastDay:string;workingDays:number[];startLocal:string;endLocal:string;}
const blank=():Draft=>({job:null,title:'',start:'',end:'',timezone:'Europe/London',location:'',skills:'',count:'1',firstDay:'',lastDay:'',workingDays:[1,2,3,4,5],startLocal:'09:00',endLocal:'17:00'});
const weekdays=[['Mon',1],['Tue',2],['Wed',3],['Thu',4],['Fri',5],['Sat',6],['Sun',7]] as const;
const tags=(value:string)=>value.trim()?value.split(',').map(tag=>tag.trim()):[];
type DailyFeedback={action:'save'|'retry';tone:'success'|'refused'|'unconfirmed';text:string};
function jobWhen(job:SchedulingJob){const start=formatSchedulingLocal(utcLeaveToLocal(job.startAt,job.timezone)),end=formatSchedulingLocal(utcLeaveToLocal(job.endAt,job.timezone));const sameDay=start.slice(0,10)===end.slice(0,10);return `${start}–${sameDay?end.slice(11):end}${job.timezone==='Europe/London'?'':` (${job.timezone})`}`;}
const spansNights=(job:SchedulingJob)=>utcLeaveToLocal(job.startAt,job.timezone).slice(0,10)!==utcLeaveToLocal(job.endAt,job.timezone).slice(0,10);

export function SchedulingJobsPanel({workspaceId,userId,disabled=false}:{workspaceId:string;userId:string;disabled?:boolean}){
 const [jobs,setJobs]=useState<SchedulingJob[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[pendingJob,setPendingJob]=useState<JobAttempt|null>(null),[pendingDaily,setPendingDaily]=useState<DailySessionAttempt|null>(null),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState(false),[cancel,setCancel]=useState<SchedulingJob|null>(null),[showCancelled,setShowCancelled]=useState(false);
 const [dailyWorking,setDailyWorking]=useState<'save'|'retry'|null>(null),[dailyFeedback,setDailyFeedback]=useState<DailyFeedback|null>(null);
 const mounted=useRef(true),lock=useRef(false),form=useRef<HTMLFormElement>(null),dailyFeedbackRef=useRef<HTMLDivElement|null>(null),focusDailyFeedback=useRef(false);
 useEffect(()=>{const element=dailyFeedbackRef.current;if(!focusDailyFeedback.current||!element)return;focusDailyFeedback.current=false;element.focus({preventScroll:true});const box=element.getBoundingClientRect();if((box.top<0||box.bottom>window.innerHeight)&&typeof element.scrollIntoView==='function')element.scrollIntoView({block:'nearest',behavior:'smooth'});},[dailyFeedback]);
 const load=()=>loadSchedulingJobs(workspaceId,async(columns,ws)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_jobs').select(columns).eq('workspace_id',ws);if(error)throw Error('Unavailable');return data;});
 useEffect(()=>{mounted.current=true;void(async()=>{try{const job=restoreJobAttempt(window.sessionStorage,workspaceId,userId),daily=restoreDailySessionAttempt(window.sessionStorage,workspaceId,userId);if(job&&daily){setBlocked(true);setMessage('Conflicting pending job saves were found. Contact support before changing jobs.');}else if(job){setPendingJob(job);setMessage('A previous job save is unconfirmed. Retry the same request first.');}else if(daily){setPendingDaily(daily);setMessage('A previous daily-session save is unconfirmed. Retry the identical request first.');}}catch{setBlocked(true);setMessage('Pending save could not be read. Contact support.');}try{const list=await load();if(mounted.current){setJobs(list);setReady(true);}}catch{if(mounted.current)setMessage('Jobs could not be loaded. Refresh to try again.');}})();return()=>{mounted.current=false;};},[workspaceId,userId]);
 useEffect(()=>{if(editing)form.current?.scrollIntoView({behavior:'smooth',block:'start'});},[editing,draft.job?.jobId]);
 const change=(patch:Partial<Draft>)=>setDraft(current=>({...current,...patch}));
 const refreshAfterSave=async()=>{window.dispatchEvent(new Event('rev-scheduling-changed'));if(!mounted.current)return true;setCancel(null);setEditing(false);setDraft(blank());try{const list=await load();if(mounted.current)setJobs(list);return true;}catch{if(mounted.current)setReady(false);return false;}};
 const reload=async(success:string)=>{if(mounted.current)setMessage(success);const listed=await refreshAfterSave();if(mounted.current&&!listed)setMessage(`${success} Refresh to reload the list.`);};
 const showDaily=(value:DailyFeedback)=>{focusDailyFeedback.current=true;setDailyFeedback(value);};

 const saveExisting=async(cancelling:SchedulingJob|null=null)=>{if(lock.current||!ready||disabled||blocked||pendingDaily)return;lock.current=true;setBusy(true);setMessage('');let attempt=pendingJob;
 try{if(!attempt){const job=cancelling??draft.job;if(!job)throw Error('Existing job required');attempt={workspaceId,requestId:crypto.randomUUID(),jobId:job.jobId,title:cancelling?job.title:draft.title.trim(),startAt:cancelling?job.startAt:localLeaveToUtc(draft.start,draft.timezone),endAt:cancelling?job.endAt:localLeaveToUtc(draft.end,draft.timezone),timezone:cancelling?job.timezone:draft.timezone,location:cancelling?job.location:draft.location.trim(),requiredSkills:cancelling?job.requiredSkills:tags(draft.skills),staffingCount:cancelling?job.staffingCount:Number(draft.count),status:cancelling?'cancelled':'open',expectedVersion:job.version};rememberJobAttempt(window.sessionStorage,userId,attempt);if(mounted.current)setPendingJob(attempt);}
 await submitJobAttempt(attempt,async(name,body)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error)throw Error('Unavailable');return data;});clearJobAttempt(window.sessionStorage,workspaceId,userId);if(mounted.current)setPendingJob(null);await reload('Job saved. No worker was assigned or notified.');
 }catch{if(mounted.current){let remembered=false;try{remembered=restoreJobAttempt(window.sessionStorage,workspaceId,userId)!==null;}catch{remembered=true;setBlocked(true);}setMessage(remembered?'Save unconfirmed. Retry the same request without creating a replacement job.':'Check job details, staffing count and times. Ambiguous or nonexistent clock-change times cannot be used.');}}finally{lock.current=false;if(mounted.current)setBusy(false);}};

 const plan=()=>({title:draft.title.trim(),timezone:draft.timezone,location:draft.location.trim(),requiredSkills:tags(draft.skills),staffingCount:Number(draft.count),firstDay:draft.firstDay,lastDay:draft.lastDay,workingDays:draft.workingDays,startLocal:draft.startLocal,endLocal:draft.endLocal});
 let preview:ReturnType<typeof previewDailySessions>=[],previewError='';if(editing&&!draft.job){try{preview=previewDailySessions(plan());}catch(error){previewError=error instanceof Error?error.message:'Choose a valid range up to 31 calendar days, at least one included weekday, and daytime start/end hours.';}}
 const saveDaily=async()=>{if(lock.current||!ready||disabled||blocked||pendingJob)return;const action=pendingDaily?'retry':'save';lock.current=true;setBusy(true);setDailyWorking(action);setDailyFeedback(null);setMessage('');let attempt=pendingDaily;
 try{if(!attempt){attempt={workspaceId,requestId:crypto.randomUUID(),...plan()};previewDailySessions(attempt);rememberDailySessionAttempt(window.sessionStorage,userId,attempt);if(mounted.current)setPendingDaily(attempt);}const result=await submitDailySessionAttempt(attempt,async(name,body)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error)throw Error('Unavailable');return data;});clearDailySessionAttempt(window.sessionStorage,workspaceId,userId);if(mounted.current)setPendingDaily(null);const saved=`${result.jobs.length} daily jobs saved. Each session requires ${attempt.staffingCount} worker${attempt.staffingCount===1?'':'s'}. No worker was assigned or notified.`;const listed=await refreshAfterSave();if(mounted.current)showDaily({action,tone:'success',text:listed?saved:`${saved} Refresh to reload the list.`});
 }catch{if(mounted.current){let remembered=false,readable=true;try{remembered=restoreDailySessionAttempt(window.sessionStorage,workspaceId,userId)!==null;}catch{remembered=true;readable=false;setBlocked(true);}
  // Only a request that was never retained (validation failed before sending) is a definite refusal.
  showDaily(!readable?{action,tone:'unconfirmed',text:'The saved request could not be read on this device. Do not create new jobs; contact support so it can be checked.'}:remembered?{action,tone:'unconfirmed',text:'Not confirmed. The daily jobs may or may not have been saved. Select “RETRY IDENTICAL DAILY SAVE” to send the same request again. It will not create a second batch.'}:{action,tone:'refused',text:'Not saved. Check dates, selected weekdays, daytime hours, timezone and staffing. Overnight and ambiguous clock-change sessions are not supported.'});}}finally{lock.current=false;if(mounted.current){setBusy(false);setDailyWorking(null);}}};

 const controlsDisabled=busy||!!pendingJob||!!pendingDaily||disabled||blocked||!ready;
 const dailyInForm=editing&&!draft.job;
 const dailyRetryButton=<button type="button" className="btn-secondary ml-2" aria-busy={dailyWorking==='retry'} disabled={busy||disabled||blocked||!ready} onClick={()=>void saveDaily()}>{dailyWorking==='retry'?'Retrying saved request…':'RETRY IDENTICAL DAILY SAVE'}</button>;
 const dailyResult=dailyFeedback&&<div ref={dailyFeedbackRef} tabIndex={-1} role={dailyFeedback.tone==='success'?'status':'alert'} className={`my-2 rounded-lg border p-3 text-sm ${dailyFeedback.tone==='success'?'border-green-300 bg-green-50 text-green-900':dailyFeedback.tone==='refused'?'border-red-300 bg-red-50 text-red-800':'border-amber-400 bg-amber-50 text-amber-900'}`}>{dailyFeedback.text}</div>;
 return <section className="border-t mt-8 pt-6"><h2 className="text-xl font-semibold">Jobs and shifts</h2><p className="my-2">Create daytime work, then choose a worker under Worker allocation. Location is recorded for planning; travel checks will follow.</p>{message&&<p role="status" className="my-2">{message}</p>}
 <button className="btn-primary my-3" disabled={controlsDisabled||!!cancel} onClick={()=>{setDraft(blank());setEditing(true);}}>ADD JOB / SHIFT</button>
 {pendingJob&&<button className="btn-secondary ml-2" disabled={busy||disabled||blocked||!ready} onClick={()=>void saveExisting()}>RETRY SAME JOB SAVE</button>}{pendingDaily&&!dailyInForm&&dailyRetryButton}{!dailyInForm&&dailyResult}
 {editing&&<form ref={form} className="card p-4 my-3" onSubmit={event=>{event.preventDefault();void(draft.job?saveExisting():saveDaily());}}><fieldset disabled={controlsDisabled}><legend className="font-semibold">{draft.job?'Edit job / shift':'New job / shift'}</legend>
 {!draft.job&&<><h3 className="font-semibold mt-3">Daily working hours</h3><p className="text-sm my-2">Creates one separate job for each selected date. No overnight work. The range may cover at most 31 calendar days.</p></>}{draft.job&&spansNights(draft.job)&&<p role="alert" className="my-2 text-amber-800">This existing interval spans nights. Editing keeps it as one continuous interval; it will never be split or converted automatically.</p>}
 <label className="block my-2">Title<input className="block border rounded p-2 w-full" required maxLength={160} value={draft.title} onChange={event=>change({title:event.target.value})}/></label><label className="block my-2">Timezone<input className="block border rounded p-2" required value={draft.timezone} onChange={event=>change({timezone:event.target.value})}/></label>
 {draft.job?<><label className="block my-2">Start date and time (in the timezone above)<input className="block border rounded p-2" type="datetime-local" required value={draft.start} onChange={event=>change({start:event.target.value})}/></label><label className="block my-2">End date and time (exclusive)<input className="block border rounded p-2" type="datetime-local" required value={draft.end} onChange={event=>change({end:event.target.value})}/></label></>:<><div className="grid gap-3 sm:grid-cols-2"><label className="block my-2">Start date<input className="block border rounded p-2" type="date" required value={draft.firstDay} onChange={event=>change({firstDay:event.target.value})}/></label><label className="block my-2">End date (inclusive)<input className="block border rounded p-2" type="date" required value={draft.lastDay} onChange={event=>change({lastDay:event.target.value})}/></label></div>
 <fieldset className="my-3"><legend className="text-sm font-medium">Selected weekdays</legend><div className="flex flex-wrap gap-3 mt-2">{weekdays.map(([label,value])=><label key={value} className="flex gap-1 items-center"><input type="checkbox" checked={draft.workingDays.includes(value)} onChange={event=>change({workingDays:event.target.checked?[...draft.workingDays,value].sort((a,b)=>a-b):draft.workingDays.filter(day=>day!==value)})}/>{label}</label>)}</div></fieldset><div className="grid gap-3 sm:grid-cols-2"><label className="block my-2">Start time<input className="block border rounded p-2" type="time" required value={draft.startLocal} onChange={event=>change({startLocal:event.target.value})}/></label><label className="block my-2">End time<input className="block border rounded p-2" type="time" required value={draft.endLocal} onChange={event=>change({endLocal:event.target.value})}/></label></div></>}
 <label className="block my-2">Location (use Remote for remote work)<input className="block border rounded p-2 w-full" required maxLength={300} value={draft.location} onChange={event=>change({location:event.target.value})}/></label><label className="block my-2">Required skills (comma-separated, exact worker tags)<input className="block border rounded p-2 w-full" value={draft.skills} onChange={event=>change({skills:event.target.value})}/></label><label className="block my-2">Workers required per session<input className="block border rounded p-2" type="number" required min={1} max={100} step={1} value={draft.count} onChange={event=>change({count:event.target.value})}/></label>
 {!draft.job&&<div className="my-3" aria-live="polite"><h4 className="font-medium">Session preview</h4>{preview.length?<ul className="list-disc pl-5 mt-1">{preview.map(session=><li key={session.date}>{formatSchedulingDate(session.date)}: {session.startLocal}-{session.endLocal} ({draft.timezone})</li>)}</ul>:<p className="text-sm text-amber-800">{previewError}</p>}</div>}<button className="btn-primary" type="submit" aria-busy={dailyWorking==='save'}>{draft.job?'SAVE JOB':dailyWorking==='save'?'Saving daily jobs…':'SAVE DAILY JOBS'}</button><button className="btn-secondary ml-2" type="button" onClick={()=>setEditing(false)}>DISCARD EDIT</button></fieldset>{dailyInForm&&<div className="mt-3">{pendingDaily&&dailyRetryButton}{dailyResult}</div>}</form>}
 <label className="flex gap-2 my-3 text-sm"><input type="checkbox" checked={showCancelled} onChange={event=>setShowCancelled(event.target.checked)}/>Show cancelled job history</label><ul className="grid gap-4 my-4 sm:grid-cols-2">{jobs.filter(job=>showCancelled||job.status==='open').map(job=><li key={job.jobId} id={`scheduling-job-${job.jobId}`} className="card p-4"><JobAssignmentsPanel key={`${workspaceId}:${userId}:${job.jobId}`} workspaceId={workspaceId} userId={userId} job={job} disabled={controlsDisabled||editing||!!cancel} when={jobWhen(job)} note={spansNights(job)&&<p className="text-sm text-amber-800 mt-1">Existing interval spans nights. It remains one continuous job and will not be converted automatically.</p>} jobActions={job.status==='open'&&<><button className="btn-secondary" disabled={controlsDisabled||!!cancel} onClick={()=>{setDraft({...blank(),job,title:job.title,start:utcLeaveToLocal(job.startAt,job.timezone),end:utcLeaveToLocal(job.endAt,job.timezone),timezone:job.timezone,location:job.location,skills:job.requiredSkills.join(', '),count:String(job.staffingCount)});setEditing(true);}}>Edit job</button><button className="btn-secondary text-red-700" disabled={controlsDisabled||editing} onClick={()=>setCancel(job)}>Cancel job</button></>}/></li>)}</ul>
 {cancel&&<div role="group" aria-label="Confirm job cancellation"><p>Cancel {cancel.title}? Its history will remain recorded.</p><button className="btn-secondary my-2" disabled={controlsDisabled} onClick={()=>void saveExisting(cancel)}>CONFIRM JOB CANCELLATION</button><button className="btn-secondary ml-2" disabled={controlsDisabled} onClick={()=>setCancel(null)}>KEEP JOB</button></div>}{ready&&jobs.length===0&&<p>No jobs or shifts recorded.</p>}
 </section>;
}