import {useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {loadWorkerUnavailability,submitLeaveAttempt,rememberLeaveAttempt,restoreLeaveAttempt,clearLeaveAttempt,localLeaveToUtc,utcLeaveToLocal,type UnavailablePeriod,type LeaveAttempt} from '@/services/workerUnavailability';
interface Draft {record:UnavailablePeriod|null;start:string;end:string;category:'leave'|'unavailable';}
const blank=():Draft=>({record:null,start:'',end:'',category:'leave'});
export function WorkerUnavailabilityPanel({workspaceId,userId,workerId,active,disabled=false}:{workspaceId:string;userId:string;workerId:string;active:boolean;disabled?:boolean}){
 const [list,setList]=useState<UnavailablePeriod[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState<LeaveAttempt|null>(null),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState(false),[cancel,setCancel]=useState<UnavailablePeriod|null>(null),[timezone,setTimezone]=useState('Europe/London'),[timezoneInput,setTimezoneInput]=useState('Europe/London');
 const lock=useRef(false),mounted=useRef(true);
 const read=()=>loadWorkerUnavailability(workspaceId,workerId,async(columns,ws,worker)=>{if(!supabaseClient)throw new Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_worker_unavailability').select(columns).eq('workspace_id',ws).eq('worker_id',worker);if(error)throw new Error('Unavailable');return data;});
 useEffect(()=>{mounted.current=true;void(async()=>{try{const a=restoreLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId);if(a&&mounted.current){setPending(a);setMessage('A previous save is unconfirmed. Retry the same request before making another change.');}}catch{if(mounted.current){setBlocked(true);setMessage('Pending save could not be read. Contact support.');}}try{const rows=await read();if(mounted.current){setList(rows);setReady(true);}}catch{if(mounted.current)setMessage('Unavailable periods could not be loaded. Refresh to try again.');}})();return()=>{mounted.current=false;};},[workspaceId,userId,workerId]);
 const save=async(cancelling:UnavailablePeriod|null=null)=>{
  if(lock.current||!ready||disabled||blocked)return;
  if(!pending&&!cancelling&&!active)return;
  lock.current=true;setBusy(true);setMessage('');let attempt=pending;
  try{
   if(!attempt){const existing=cancelling??draft.record;attempt={workspaceId,workerId,requestId:crypto.randomUUID(),unavailabilityId:existing?.unavailabilityId??null,startAt:cancelling?cancelling.startAt:localLeaveToUtc(draft.start,timezone),endAt:cancelling?cancelling.endAt:localLeaveToUtc(draft.end,timezone),category:cancelling?cancelling.category:draft.category,status:cancelling?'cancelled':'active',expectedVersion:existing?.version??0};rememberLeaveAttempt(window.sessionStorage,userId,attempt);if(mounted.current)setPending(attempt);}
   await submitLeaveAttempt(attempt,async(name,body)=>{if(!supabaseClient)throw new Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error)throw new Error('Unavailable');return data;});clearLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId);
   if(!mounted.current)return;setPending(null);setCancel(null);setEditing(false);setDraft(blank());setMessage('Unavailable period saved.');
   try{const rows=await read();if(mounted.current)setList(rows);}catch{if(mounted.current){setReady(false);setMessage('Saved. Refresh to reload the periods.');}}
  }catch{if(mounted.current){let remembered=false;try{remembered=restoreLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId)!==null;}catch{setBlocked(true);remembered=true;}setMessage(remembered?'Save could not be confirmed. Retry the same request without creating a replacement.':'Enter valid start/end times. Clock-change times that are ambiguous or nonexistent cannot be used.');}}
  finally{lock.current=false;if(mounted.current)setBusy(false);}
 };
 const controlsDisabled=busy||!!pending||disabled||blocked||!ready;
 return <details className="border-t mt-4 pt-3"><summary className="font-medium cursor-pointer">Leave and unavailable periods</summary>{message&&<p role="status" className="my-2">{message}</p>}
 <label className="block my-2">Display/input timezone<input className="block border rounded p-2 w-full" value={timezoneInput} disabled={controlsDisabled||editing||!!cancel} onChange={event=>setTimezoneInput(event.target.value)}/></label><button className="btn-secondary" disabled={controlsDisabled||editing||!!cancel} onClick={()=>{try{new Intl.DateTimeFormat('en-GB',{timeZone:timezoneInput});setTimezone(timezoneInput);setMessage('Timezone applied.');}catch{setMessage('Use a valid timezone such as Europe/London.');}}}>APPLY TIMEZONE</button><p className="text-sm my-2">Times are shown in {timezone}. End time is exclusive. No calendar event or notification is created.</p>
 <button className="btn-secondary my-2" disabled={controlsDisabled||!active||!!cancel} onClick={()=>{setDraft(blank());setEditing(true);}}>ADD UNAVAILABLE PERIOD</button>
 {pending&&<button className="btn-secondary my-2" disabled={busy||disabled||blocked||!ready} onClick={()=>void save()}>RETRY SAME LEAVE SAVE</button>}
 {editing&&<form onSubmit={event=>{event.preventDefault();void save();}}><fieldset disabled={controlsDisabled||!active}><legend>{draft.record?'Edit unavailable period':'New unavailable period'}</legend><label className="block my-2">Start ({timezone})<input className="block border rounded p-2" type="datetime-local" required value={draft.start} onChange={event=>setDraft({...draft,start:event.target.value})}/></label><label className="block my-2">End ({timezone})<input className="block border rounded p-2" type="datetime-local" required value={draft.end} onChange={event=>setDraft({...draft,end:event.target.value})}/></label><label className="block my-2">Category<select className="block border rounded p-2" value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value as Draft['category']})}><option value="leave">Leave</option><option value="unavailable">Unavailable</option></select></label><button className="btn-secondary" type="submit">SAVE PERIOD</button><button className="btn-secondary ml-2" type="button" onClick={()=>setEditing(false)}>DISCARD EDIT</button></fieldset></form>}
 <ul className="space-y-3 mt-3">{list.map(p=><li key={p.unavailabilityId} className="border rounded p-3"><p>{p.category==='leave'?'Leave':'Unavailable'} · {p.status}</p><p>{utcLeaveToLocal(p.startAt,timezone).replace('T',' ')} to {utcLeaveToLocal(p.endAt,timezone).replace('T',' ')} ({timezone})</p>{p.status==='active'&&<><button className="btn-secondary mt-2" disabled={controlsDisabled||!active||!!cancel} onClick={()=>{setDraft({record:p,start:utcLeaveToLocal(p.startAt,timezone),end:utcLeaveToLocal(p.endAt,timezone),category:p.category});setEditing(true);}}>EDIT PERIOD</button><button className="btn-secondary mt-2 ml-2" disabled={controlsDisabled||editing} onClick={()=>setCancel(p)}>CANCEL PERIOD</button></>}</li>)}</ul>
 {cancel&&<div role="group" aria-label="Confirm period cancellation" className="my-3"><p>Cancel this unavailable period? Its history will remain recorded.</p><button className="btn-secondary" disabled={controlsDisabled} onClick={()=>void save(cancel)}>CONFIRM CANCELLATION</button><button className="btn-secondary ml-2" disabled={controlsDisabled} onClick={()=>setCancel(null)}>KEEP PERIOD</button></div>}
 {ready&&list.length===0&&<p className="text-sm my-2">No unavailable periods recorded.</p>}
 </details>;
}
