import {useEffect,useRef,useState} from 'react';
import {supabaseClient} from '@/data/supabaseClient';
import {loadWorkerUnavailability,loadAccountedLeaveIds,submitLeaveAttempt,rememberLeaveAttempt,restoreLeaveAttempt,clearLeaveAttempt,submitLegacyLeaveCancellation,rememberLegacyLeaveCancelAttempt,restoreLegacyLeaveCancelAttempt,clearLegacyLeaveCancelAttempt,localLeaveToUtc,utcLeaveToLocal,LeaveSaveRefused,LegacyLeaveCancelRefused,type UnavailablePeriod,type LeaveAttempt,type LegacyLeaveCancelAttempt} from '@/services/workerUnavailability';
import {formatSchedulingLocal} from '@/services/schedulingDisplay';
interface Draft {record:UnavailablePeriod|null;start:string;end:string;category:'unavailable';}
const blank=():Draft=>({record:null,start:'',end:'',category:'unavailable'});
export function WorkerUnavailabilityPanel({workspaceId,userId,workerId,active,disabled=false,retryDisabled=disabled,parentDisabledReason=''}:{workspaceId:string;userId:string;workerId:string;active:boolean;disabled?:boolean;retryDisabled?:boolean;parentDisabledReason?:string}){
 const [list,setList]=useState<UnavailablePeriod[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState<LeaveAttempt|null>(null),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState(false),[cancel,setCancel]=useState<UnavailablePeriod|null>(null),[timezone,setTimezone]=useState('Europe/London'),[timezoneInput,setTimezoneInput]=useState('Europe/London');
 const [accountedLeaveIds,setAccountedLeaveIds]=useState<Set<string>>(new Set()),[legacyPending,setLegacyPending]=useState<LegacyLeaveCancelAttempt|null>(null),[legacyCancel,setLegacyCancel]=useState<UnavailablePeriod|null>(null);
 const lock=useRef(false),mounted=useRef(true);
 const read=()=>loadWorkerUnavailability(workspaceId,workerId,async(columns,ws,worker)=>{if(!supabaseClient)throw new Error('Unavailable');const {data,error}=await supabaseClient.from('scheduling_worker_unavailability').select(columns).eq('workspace_id',ws).eq('worker_id',worker);if(error)throw new Error('Unavailable');return data;});
 const readAccounted=()=>loadAccountedLeaveIds(workspaceId,workerId,async(columns,ws,worker)=>{if(!supabaseClient)throw new Error('Unavailable');const {data,error}=await supabaseClient.from('annual_leave_absences').select(columns).eq('workspace_id',ws).eq('worker_id',worker);if(error)throw new Error('Unavailable');return data;});
 useEffect(()=>{mounted.current=true;void(async()=>{try{const a=restoreLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId),legacy=restoreLegacyLeaveCancelAttempt(window.sessionStorage,workspaceId,userId,workerId);if(a&&legacy)throw Error('Conflicting pending requests');if(a&&mounted.current){setPending(a);setMessage('A previous save is unconfirmed. Retry the same request before making another change.');}if(legacy&&mounted.current){setLegacyPending(legacy);setMessage('A historical leave cancellation is unconfirmed. Retry the same cancellation before making another change.');}}catch{if(mounted.current){setBlocked(true);setMessage('Pending save could not be read. Contact support.');}}try{const [rows,accounted]=await Promise.all([read(),readAccounted()]);if(mounted.current){setList(rows);setAccountedLeaveIds(accounted);setReady(true);}}catch{if(mounted.current)setMessage('Unavailable periods could not be loaded. Refresh to try again.');}})();return()=>{mounted.current=false;};},[workspaceId,userId,workerId]);
 const save=async(cancelling:UnavailablePeriod|null=null,retry=false)=>{
    if(lock.current||!ready||(retry?retryDisabled:disabled)||blocked)return;
  if(!pending&&!cancelling&&!active)return;
  lock.current=true;setBusy(true);setMessage(retry?'Retrying the same unavailable-period request...':cancelling?'Cancelling unavailable period...':'Saving unavailable period...');let attempt=pending;
  try{
   if(!attempt){const existing=cancelling??draft.record;attempt={workspaceId,workerId,requestId:crypto.randomUUID(),unavailabilityId:existing?.unavailabilityId??null,startAt:cancelling?cancelling.startAt:localLeaveToUtc(draft.start,timezone),endAt:cancelling?cancelling.endAt:localLeaveToUtc(draft.end,timezone),category:cancelling?cancelling.category:draft.category,status:cancelling?'cancelled':'active',expectedVersion:existing?.version??0};rememberLeaveAttempt(window.sessionStorage,userId,attempt);if(mounted.current)setPending(attempt);}
   const status=attempt.status;await submitLeaveAttempt(attempt,async(name,body)=>{if(!supabaseClient)throw new Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error){const context=(error as {context?:unknown}).context;if(context instanceof Response&&context.status===409)return{status:409,data:await context.clone().json()};throw new Error('Uncertain result');}return{status:200,data};});clearLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId);window.dispatchEvent(new Event('rev-scheduling-changed'));
   if(!mounted.current)return;setPending(null);setCancel(null);setEditing(false);setDraft(blank());setMessage(status==='cancelled'?'Unavailable period cancelled and planner refresh requested.':'Unavailable period saved and planner refresh requested.');
   try{const rows=await read();if(mounted.current)setList(rows);}catch{if(mounted.current){setReady(false);setMessage('Saved. Refresh to reload the periods.');}}
  }catch(error){if(!mounted.current)return;if(error instanceof LeaveSaveRefused){try{clearLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId);setPending(null);setCancel(null);const rows=await read();if(mounted.current){setList(rows);setMessage(error.message);}}catch{setReady(false);setMessage(`${error.message} Refresh this page to reload the current periods.`);}}else{let remembered=false;try{remembered=restoreLeaveAttempt(window.sessionStorage,workspaceId,userId,workerId)!==null;}catch{setBlocked(true);remembered=true;}setMessage(remembered?'Outcome still unconfirmed. Retry the same unavailable-period request; its request ID and payload have been retained.':'Enter valid start/end times. Clock-change times that are ambiguous or nonexistent cannot be used.');}}
  finally{lock.current=false;if(mounted.current)setBusy(false);}
 };
  const cancelLegacy=async(retry=false)=>{
   if(lock.current||!ready||retryDisabled||disabled||blocked)return;
   lock.current=true;setBusy(true);setMessage(retry?'Retrying the same historical leave cancellation...':'Cancelling historical leave without changing balances...');let attempt=legacyPending;
   try{
    if(!attempt){if(!legacyCancel)throw Error('Historical leave required');attempt={workspaceId,workerId,unavailabilityId:legacyCancel.unavailabilityId,requestId:crypto.randomUUID(),expectedVersion:legacyCancel.version};rememberLegacyLeaveCancelAttempt(window.sessionStorage,userId,attempt);if(mounted.current)setLegacyPending(attempt);}
    await submitLegacyLeaveCancellation(attempt,async(name,body)=>{if(!supabaseClient)throw Error('Unavailable');const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error){const context=(error as {context?:unknown}).context;if(context instanceof Response&&context.status===409)return{status:409,data:await context.clone().json()};throw Error('Uncertain result');}return{status:200,data};});
    clearLegacyLeaveCancelAttempt(window.sessionStorage,workspaceId,userId,workerId);window.dispatchEvent(new Event('rev-scheduling-changed'));
    if(!mounted.current)return;setLegacyPending(null);setLegacyCancel(null);setMessage('Historical leave cancelled with no balance change. Planner refresh requested.');
    const [rows,accounted]=await Promise.all([read(),readAccounted()]);if(mounted.current){setList(rows);setAccountedLeaveIds(accounted);}
   }catch(error){if(!mounted.current)return;if(error instanceof LegacyLeaveCancelRefused){clearLegacyLeaveCancelAttempt(window.sessionStorage,workspaceId,userId,workerId);setLegacyPending(null);setLegacyCancel(null);setMessage(error.message);try{const [rows,accounted]=await Promise.all([read(),readAccounted()]);if(mounted.current){setList(rows);setAccountedLeaveIds(accounted);}}catch{setReady(false);}}else setMessage('Historical leave cancellation outcome is unconfirmed. Retry the same cancellation request.');}
   finally{lock.current=false;if(mounted.current)setBusy(false);}
  };
  const controlsDisabled=busy||!!pending||!!legacyPending||disabled||blocked||!ready;
  const disabledReason=busy?'A save is in progress. Wait for its result.':blocked?'Pending request details cannot be read. Contact support before changing unavailable periods.':!ready?'Unavailable periods are not ready. Refresh this page to reload them.':disabled?parentDisabledReason||'Another scheduling change is unresolved. Recover it from Scheduling before changing unavailable periods.':pending?'This save outcome is unconfirmed. Use RETRY SAME LEAVE SAVE; editing would change the retained payload.':legacyPending?'This cancellation outcome is unconfirmed. Use RETRY HISTORICAL LEAVE CANCELLATION.':!active?'This worker is inactive. Reactivate the worker before adding or editing unavailable periods.':cancel||legacyCancel?'Finish or keep the pending cancellation before using other controls.':editing?'Save or discard the current edit before using timezone or cancellation controls.':'';
 return <details className="border-t mt-4 pt-3"><summary className="font-medium cursor-pointer">Leave and unavailable periods</summary>{message&&<p role="status" className="my-2">{message}</p>}{disabledReason&&<p className="text-sm my-2">Controls unavailable: {disabledReason}</p>}
 <label className="block my-2">Display/input timezone<input className="block border rounded p-2 w-full" title={disabledReason||undefined} value={timezoneInput} disabled={controlsDisabled||editing||!!cancel} onChange={event=>setTimezoneInput(event.target.value)}/></label><button className="btn-secondary" title={disabledReason||undefined} disabled={controlsDisabled||editing||!!cancel} onClick={()=>{try{new Intl.DateTimeFormat('en-GB',{timeZone:timezoneInput});setTimezone(timezoneInput);setMessage('Timezone applied.');}catch{setMessage('Use a valid timezone such as Europe/London.');}}}>APPLY TIMEZONE</button><p className="text-sm my-2">Times are shown in {timezone}. End time is exclusive. No calendar event or notification is created.</p>
 <button className="btn-secondary my-2" title={disabledReason||undefined} disabled={controlsDisabled||!active||!!cancel} onClick={()=>{setDraft(blank());setEditing(true);}}>ADD UNAVAILABLE PERIOD</button>
 {pending&&<button className="btn-secondary my-2" title={retryDisabled?disabledReason||undefined:undefined} disabled={busy||retryDisabled||blocked||!ready} onClick={()=>void save(null,true)}>{busy?'RETRYING...':'RETRY SAME LEAVE SAVE'}</button>}
 {legacyPending&&<button className="btn-secondary my-2" title={retryDisabled?disabledReason||undefined:undefined} disabled={busy||retryDisabled||blocked||!ready} onClick={()=>void cancelLegacy(true)}>{busy?'RETRYING...':'RETRY HISTORICAL LEAVE CANCELLATION'}</button>}
 {editing&&<form onSubmit={event=>{event.preventDefault();void save();}}><fieldset disabled={controlsDisabled||!active} title={disabledReason||undefined}><legend>{draft.record?'Edit unavailable period':'New unavailable period'}</legend><label className="block my-2">Start ({timezone})<input className="block border rounded p-2" type="datetime-local" required value={draft.start} onChange={event=>setDraft({...draft,start:event.target.value})}/></label><label className="block my-2">End ({timezone})<input className="block border rounded p-2" type="datetime-local" required value={draft.end} onChange={event=>setDraft({...draft,end:event.target.value})}/></label><p className="my-2">Category: Unavailable</p><button className="btn-secondary" type="submit">{busy?'SAVING...':'SAVE PERIOD'}</button><button className="btn-secondary ml-2" type="button" onClick={()=>setEditing(false)}>DISCARD EDIT</button></fieldset></form>}
 <ul className="space-y-3 mt-3">{list.map(p=><li key={p.unavailabilityId} className="border rounded p-3"><p>{p.category==='leave'?'Leave':'Unavailable'} · {p.status}</p><p>{formatSchedulingLocal(utcLeaveToLocal(p.startAt,timezone))} to {formatSchedulingLocal(utcLeaveToLocal(p.endAt,timezone))} ({timezone})</p>{p.status==='active'&&p.category==='unavailable'&&<><button className="btn-secondary mt-2" disabled={controlsDisabled||!active||!!cancel||!!legacyCancel} onClick={()=>{setDraft({record:p,start:utcLeaveToLocal(p.startAt,timezone),end:utcLeaveToLocal(p.endAt,timezone),category:'unavailable'});setEditing(true);}}>EDIT PERIOD</button><button className="btn-secondary mt-2 ml-2" disabled={controlsDisabled||editing} onClick={()=>setCancel(p)}>CANCEL PERIOD</button></>}{p.status==='active'&&p.category==='leave'&&(accountedLeaveIds.has(p.unavailabilityId)?<p className="text-sm mt-2">Recorded annual leave — cancel through Annual Leave for an exact balance reversal.</p>:<button className="btn-secondary mt-2" disabled={controlsDisabled||editing||!!cancel} onClick={()=>setLegacyCancel(p)}>CANCEL HISTORICAL LEAVE (NO BALANCE CHANGE)</button>)}</li>)}</ul>
 {cancel&&<div role="group" aria-label="Confirm period cancellation" className="my-3"><p>Cancel this unavailable period? Its history will remain recorded.</p><button className="btn-secondary" disabled={controlsDisabled} onClick={()=>void save(cancel)}>CONFIRM CANCELLATION</button><button className="btn-secondary ml-2" disabled={controlsDisabled} onClick={()=>setCancel(null)}>KEEP PERIOD</button></div>}
 {legacyCancel&&<div role="group" aria-label="Confirm historical leave cancellation" className="my-3"><p>Cancel this historical leave? Dates and history remain recorded. No annual-leave balance will be deducted or credited.</p><button className="btn-secondary" disabled={controlsDisabled} onClick={()=>void cancelLegacy()}>CONFIRM HISTORICAL LEAVE CANCELLATION</button><button className="btn-secondary ml-2" disabled={controlsDisabled} onClick={()=>setLegacyCancel(null)}>KEEP HISTORICAL LEAVE</button></div>}
 {ready&&list.length===0&&<p className="text-sm my-2">No unavailable periods recorded.</p>}
 </details>;
}
