export interface AnnualLeaveAccountInput{target_workspace_id:string;initiating_user_id:string;target_request_id:string;target_worker_id:string;target_leave_year_start:string;expected_version:number;}
export interface AnnualLeaveAccountDependencies{allowedOrigin?:string;getUserId(authorization:string):Promise<string|null>;canManage(authorization:string,workspaceId:string,userId:string):Promise<boolean>;open(input:AnnualLeaveAccountInput):Promise<unknown>;}
export const annualLeaveAccountRefusalReasons={'Annual leave account already exists':'account_exists','Leave year start does not match policy':'policy_date_mismatch','Annual leave account overlaps existing year':'account_overlap'} as const;
export type AnnualLeaveAccountRefusalCode=typeof annualLeaveAccountRefusalReasons[keyof typeof annualLeaveAccountRefusalReasons];
export class AnnualLeaveAccountRefusal extends Error{readonly code:AnnualLeaveAccountRefusalCode;constructor(code:AnnualLeaveAccountRefusalCode){super('Annual leave account refused');this.code=code;}}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,id=(value:unknown):value is string=>typeof value==='string'&&uuid.test(value),date=(value:unknown):value is string=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
const integer=(value:unknown,min:number,max:number)=>Number.isSafeInteger(value)&&(value as number)>=min&&(value as number)<=max;
const decimal=(value:unknown)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>10000)return null;const scaled=Math.round(value*10000);return scaled===value*10000?{value,scaled}:null;};
function oneYearBoundary(start:unknown,end:unknown){if(!date(start)||!date(end))return false;const year=Number(start.slice(0,4));if(year>=9999)return false;return end===`${String(year+1).padStart(4,'0')}${start.slice(4)}`;}
export async function handleAnnualLeaveAccountOpen(request:Request,deps:AnnualLeaveAccountDependencies):Promise<Response>{
 if(!deps.allowedOrigin||request.headers.get('Origin')!==deps.allowedOrigin)return new Response(null,{status:403});const headers={'Access-Control-Allow-Origin':deps.allowedOrigin,Vary:'Origin','Cache-Control':'no-store','Content-Type':'application/json'},reply=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'authorization, content-type, apikey, x-client-info'}});if(request.method!=='POST')return reply(405,{error:'Method not allowed.'});const authorization=request.headers.get('Authorization')??'';if(!/^Bearer\s+\S+$/i.test(authorization))return reply(401,{error:'Authentication required.'});if(request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')return reply(415,{error:'JSON required.'});
 try{const raw=await request.text();if(raw.length>2048)return reply(400,{error:'Invalid annual leave account.'});const body=JSON.parse(raw);if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).sort().join(',')!=='expectedVersion,leaveYearStart,requestId,workerId,workspaceId'||!id(body.workspaceId)||!id(body.workerId)||!id(body.requestId)||!date(body.leaveYearStart)||body.expectedVersion!==0)return reply(400,{error:'Invalid annual leave account.'});const userId=await deps.getUserId(authorization);if(!id(userId))return reply(401,{error:'Authentication required.'});if(!await deps.canManage(authorization,body.workspaceId,userId))return reply(403,{error:'Annual leave account could not be opened.'});let value:unknown;try{value=await deps.open({target_workspace_id:body.workspaceId,initiating_user_id:userId,target_request_id:body.requestId,target_worker_id:body.workerId,target_leave_year_start:body.leaveYearStart,expected_version:0});}catch(error){if(error instanceof AnnualLeaveAccountRefusal&&Object.values(annualLeaveAccountRefusalReasons).includes(error.code))return reply(409,{status:'refused',code:error.code,requestId:body.requestId});throw error;}if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid result');const row=value as Record<string,unknown>,allowanceInputValue=decimal(row.allowance_input_value);
  if(!id(row.account_id)||!id(row.policy_id)||row.workspace_id!==body.workspaceId||row.worker_id!==body.workerId||row.leave_year_start!==body.leaveYearStart||!oneYearBoundary(row.leave_year_start,row.leave_year_end_exclusive)||!integer(row.policy_version,1,Number.MAX_SAFE_INTEGER-1)||!['workspace','worker'].includes(row.policy_scope as string)||!['hours','days'].includes(row.allowance_input_unit as string)||allowanceInputValue===null||!integer(row.configured_allowance_minutes,0,10000000)||!integer(row.hours_per_day_minutes,1,1440)||(row.allowance_input_unit==='hours'?allowanceInputValue.scaled*60!==(row.configured_allowance_minutes as number)*10000:allowanceInputValue.scaled*(row.hours_per_day_minutes as number)!==(row.configured_allowance_minutes as number)*10000)||!['included','additional'].includes(row.bank_holiday_treatment as string)||row.adjustment_total_minutes!==0||row.accounting_status!=='policy_only'||row.version!==1)throw Error('Invalid result');
  return reply(200,{accountId:row.account_id,workspaceId:row.workspace_id,workerId:row.worker_id,leaveYearStart:row.leave_year_start,leaveYearEndExclusive:row.leave_year_end_exclusive,policyId:row.policy_id,policyVersion:row.policy_version,policyScope:row.policy_scope,allowanceInputUnit:row.allowance_input_unit,allowanceInputValue:allowanceInputValue.value,configuredAllowanceMinutes:row.configured_allowance_minutes,hoursPerDayMinutes:row.hours_per_day_minutes,bankHolidayTreatment:row.bank_holiday_treatment,adjustmentTotalMinutes:0,accountingStatus:'policy_only',version:1});
 }catch{return reply(503,{error:'Annual leave account outcome could not be confirmed.',code:'outcome_unknown'});}
}