// Local Supabase only. Fake identities and data; no hosted URL or provider calls.
import{randomBytes,randomUUID}from'node:crypto';import{spawnSync}from'node:child_process';
const baseUrl='http://127.0.0.1:55321',anonKey=process.env.REV_LOCAL_SUPABASE_ANON_KEY,serviceKey=process.env.REV_LOCAL_SUPABASE_SERVICE_ROLE_KEY;if(!anonKey||!serviceKey)throw Error('Local Supabase test keys required.');
const identities=[],workspaces=[];let failures=0;const check=(name,value)=>{console.log(`${name}=${value?'PASS':'FAIL'}`);if(!value)failures++;};
async function request(token,method,path,body){const response=await fetch(baseUrl+path,{method,headers:{apikey:anonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>null);return{status:response.status,payload,rows:Array.isArray(payload)?payload:[]};}
const rpc=(token,name,body)=>request(token,'POST',`/rest/v1/rpc/${name}`,body);
function runSql(statement){return spawnSync('docker',['exec','-i','supabase_db_revive-app','psql','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1','-Atq'],{input:statement,encoding:'utf8'});}
function sql(statement){const result=runSql(statement);if(result.error||result.status!==0)throw Error(`Local SQL failed: ${result.stderr}`);return result.stdout.trim();}
function sqlRejectedBy(statement,expectedError){const result=runSql(statement);if(result.error)throw Error(`Local SQL failed: ${result.error.message}`);return result.status!==0&&result.stderr.includes(expectedError);}
const uuid=/^[0-9a-f-]{36}$/i,id=value=>{if(typeof value!=='string'||!uuid.test(value))throw Error('Invalid fixture identifier');return value;};
async function identity(label){const email=`annual-leave-${Date.now()}-${label}-${randomBytes(4).toString('hex')}@example.test`,password=`Local-${randomBytes(24).toString('base64url')}`,created=await request(serviceKey,'POST','/auth/v1/admin/users',{email,password,email_confirm:true});if(created.status!==200)throw Error('Identity fixture failed');const userId=id(created.payload.id);identities.push(userId);const login=await request(anonKey,'POST','/auth/v1/token?grant_type=password',{email,password});if(login.status!==200)throw Error('Login fixture failed');return{id:userId,token:login.payload.access_token};}
async function workspace(owner){const stamp=`${Date.now()}-${randomBytes(4).toString('hex')}`,created=await rpc(owner.token,'create_workspace_with_owner',{workspace_name:`Annual leave ${stamp}`,workspace_slug:`annual-leave-${stamp}`});const workspaceId=id(created.payload?.[0]?.created_workspace_id);workspaces.push(workspaceId);return workspaceId;}
async function retire(){for(const workspaceId of workspaces)await request(serviceKey,'PATCH',`/rest/v1/workspace_members?workspace_id=eq.${workspaceId}`,{status:'suspended'});for(const userId of identities){const found=await request(serviceKey,'GET',`/auth/v1/admin/users/${userId}`),email=found.payload?.email??found.payload?.user?.email;if(found.status===200&&typeof email==='string'&&email.startsWith('annual-leave-')&&email.endsWith('@example.test'))await request(serviceKey,'PUT',`/auth/v1/admin/users/${userId}`,{ban_duration:'87600h'});}console.log('APPEND_ONLY_AUDIT_PRESERVED=PASS');}
try{
 const owner=await identity('owner'),member=await identity('member'),outsider=await identity('outsider'),ws=await workspace(owner),other=await workspace(outsider);await request(serviceKey,'POST','/rest/v1/workspace_members',{workspace_id:ws,user_id:member.id,role:'member',status:'active'});
 const workerResult=await rpc(serviceKey,'save_rev_scheduling_worker',{target_workspace_id:ws,initiating_user_id:owner.id,target_request_id:randomUUID(),target_worker_id:null,target_display_name:'Annual Leave Worker',target_role_labels:[],target_skill_tags:[],target_active:true,expected_version:0});const worker=id(workerResult.payload?.worker_id);
 const policyInput={target_workspace_id:ws,initiating_user_id:owner.id,target_request_id:randomUUID(),target_worker_id:null,target_effective_from_leave_year:2026,target_allowance_input_unit:'days',target_allowance_input_value:28,target_allowance_minutes:12600,target_hours_per_day_minutes:450,target_leave_year_start_month:4,target_leave_year_start_day:1,target_bank_holiday_treatment:'included',expected_version:0};
 const savePolicy=(patch={},token=serviceKey)=>rpc(token,'save_rev_annual_leave_policy',{...policyInput,...patch});
 const policyRace=await Promise.all([savePolicy(),savePolicy()]);check('CONCURRENT_POLICY_REQUEST_CREATED_ONCE',policyRace.every(value=>value.status===200)&&policyRace[0].payload?.policy_id===policyRace[1].payload?.policy_id);check('WORKSPACE_DEFAULT_28_DAYS_FROZEN_AS_12600_MINUTES',policyRace[0].payload?.allowance_minutes===12600&&policyRace[0].payload?.bank_holiday_treatment==='included');check('IDENTICAL_POLICY_RETRY_SAFE',JSON.stringify((await savePolicy()).payload)===JSON.stringify(policyRace[0].payload));check('CHANGED_POLICY_RETRY_DENIED',(await savePolicy({target_allowance_minutes:13000})).status>=400);
 const firstPolicyRace=await Promise.all([savePolicy({target_request_id:randomUUID(),target_effective_from_leave_year:2027,expected_version:1}),savePolicy({target_request_id:randomUUID(),target_effective_from_leave_year:2028,expected_version:1})]);check('DIFFERENT_POLICY_REQUESTS_SERIALIZE_BY_VERSION',firstPolicyRace.filter(value=>value.status===200).length===1&&firstPolicyRace.filter(value=>value.status>=400).length===1);
 const override=await savePolicy({target_request_id:randomUUID(),target_worker_id:worker,target_allowance_input_unit:'hours',target_allowance_input_value:200,target_allowance_minutes:12000,target_hours_per_day_minutes:420,target_bank_holiday_treatment:'additional'});check('FULL_WORKER_OVERRIDE_SAVED',override.status===200&&override.payload?.worker_id===worker&&override.payload?.allowance_minutes===12000);
 const stalePolicy=await savePolicy({target_request_id:randomUUID(),target_worker_id:worker,expected_version:0});check('STALE_POLICY_VERSION_DENIED',stalePolicy.status>=400&&stalePolicy.payload?.message==='Annual leave policy changed');check('MEMBER_POLICY_SAVE_DENIED',(await savePolicy({target_request_id:randomUUID(),initiating_user_id:member.id})).status>=400);check('CROSS_TENANT_POLICY_SAVE_DENIED',(await savePolicy({target_request_id:randomUUID(),target_workspace_id:other,initiating_user_id:outsider.id,target_worker_id:worker})).status>=400);for(const token of[anonKey,owner.token])check('BROWSER_POLICY_RPC_DENIED',(await savePolicy({target_request_id:randomUUID()},token)).status>=400);
 const accountInput={target_workspace_id:ws,initiating_user_id:owner.id,target_request_id:randomUUID(),target_worker_id:worker,target_leave_year_start:'2026-04-01',expected_version:0},open=(patch={},token=serviceKey)=>rpc(token,'open_rev_annual_leave_account',{...accountInput,...patch});const accountRace=await Promise.all([open(),open()]);check('CONCURRENT_ACCOUNT_REQUEST_CREATED_ONCE',accountRace.every(value=>value.status===200)&&accountRace[0].payload?.account_id===accountRace[1].payload?.account_id);const account=id(accountRace[0].payload?.account_id);check('WORKER_OVERRIDE_PRECEDENCE_AND_POLICY_ONLY',accountRace[0].payload?.policy_scope==='worker'&&accountRace[0].payload?.configured_allowance_minutes===12000&&accountRace[0].payload?.hours_per_day_minutes===420&&accountRace[0].payload?.bank_holiday_treatment==='additional'&&accountRace[0].payload?.accounting_status==='policy_only'&&!Object.hasOwn(accountRace[0].payload,'remaining_minutes'));
 const changed=await savePolicy({target_request_id:randomUUID(),target_worker_id:worker,target_allowance_input_unit:'hours',target_allowance_input_value:220,target_allowance_minutes:13200,target_hours_per_day_minutes:450,target_bank_holiday_treatment:'included',expected_version:1});check('LATER_POLICY_REVISION_SAVED',changed.status===200&&changed.payload?.version===2);const shifted=await savePolicy({target_request_id:randomUUID(),target_worker_id:worker,target_effective_from_leave_year:2027,target_leave_year_start_month:1,target_leave_year_start_day:1,expected_version:2});check('CHANGED_LEAVE_YEAR_POLICY_SAVED',shifted.status===200&&shifted.payload?.version===3);const frozen=(await request(owner.token,'GET',`/rest/v1/annual_leave_accounts?id=eq.${account}&select=*`)).rows[0];check('OPEN_ACCOUNT_SNAPSHOT_UNCHANGED',frozen.configured_allowance_minutes===12000&&frozen.policy_version===1&&frozen.bank_holiday_treatment==='additional'&&frozen.leave_year_start==='2026-04-01'&&frozen.leave_year_end_exclusive==='2027-04-01');const duplicate=await open({target_request_id:randomUUID()});check('DUPLICATE_WORKER_YEAR_ACCOUNT_DENIED',duplicate.status>=400&&duplicate.payload?.message==='Annual leave account already exists');const mismatch=await open({target_request_id:randomUUID(),target_leave_year_start:'2027-02-01'});check('MISMATCHED_LEAVE_YEAR_START_DENIED',mismatch.status>=400&&mismatch.payload?.message==='Leave year start does not match policy');const overlap=await open({target_request_id:randomUUID(),target_leave_year_start:'2027-01-01'});check('POLICY_CHANGE_OVERLAP_DENIED',overlap.status>=400&&overlap.payload?.message==='Annual leave account overlaps existing year');check('OVERLAP_DENIAL_CREATED_NO_ACCOUNT',sql(`select count(*) from public.annual_leave_accounts where workspace_id='${id(ws)}' and worker_id='${worker}';`)==='1');check('OVERLAP_EXCLUSION_CONSTRAINT_PRESENT',sql(`select count(*) from pg_catalog.pg_constraint where conname='annual_leave_accounts_no_overlap' and contype='x';`)==='1');
 check('ACCOUNT_SNAPSHOT_UPDATE_REJECTED_BY_DATABASE_GUARD',sqlRejectedBy(`update public.annual_leave_accounts set configured_allowance_minutes=1 where id='${account}';`,'Annual leave account snapshot is immutable'));check('ACCOUNT_SNAPSHOT_DATABASE_PROTECTED',sql(`select configured_allowance_minutes from public.annual_leave_accounts where id='${account}';`)==='12000');
 const adjustmentInput={target_workspace_id:ws,initiating_user_id:owner.id,target_request_id:randomUUID(),target_account_id:account,target_adjustment_minutes:450,target_reason:'Contractual correction',expected_version:1},adjust=(patch={},token=serviceKey)=>rpc(token,'save_rev_annual_leave_adjustment',{...adjustmentInput,...patch});const adjustmentRace=await Promise.all([adjust(),adjust()]);check('IDENTICAL_ADJUSTMENT_REQUEST_CREATED_ONCE',adjustmentRace.every(value=>value.status===200)&&adjustmentRace[0].payload?.adjustment_id===adjustmentRace[1].payload?.adjustment_id);check('REASONED_ADJUSTMENT_ADVANCES_ACCOUNT',adjustmentRace[0].payload?.account_version===2&&adjustmentRace[0].payload?.adjustment_total_minutes===450&&adjustmentRace[0].payload?.accounting_status==='policy_only');const staleAdjustment=await adjust({target_request_id:randomUUID(),target_adjustment_minutes:-225});check('STALE_ADJUSTMENT_VERSION_DENIED',staleAdjustment.status>=400&&staleAdjustment.payload?.message==='Annual leave account changed');check('REASON_REQUIRED',(await adjust({target_request_id:randomUUID(),target_reason:'',expected_version:2})).status>=400);
 const competing=await Promise.all([adjust({target_request_id:randomUUID(),target_adjustment_minutes:60,target_reason:'First correction',expected_version:2}),adjust({target_request_id:randomUUID(),target_adjustment_minutes:120,target_reason:'Second correction',expected_version:2})]);check('CONCURRENT_ACCOUNT_VERSION_ONCE',competing.filter(value=>value.status===200).length===1&&competing.filter(value=>value.status>=400).length===1);check('ADJUSTMENTS_APPEND_ONLY',sql(`select count(*) from public.annual_leave_adjustments where workspace_id='${id(ws)}' and account_id='${account}';`)==='2');check('DIRECT_ADJUSTMENT_MUTATION_DENIED',(await request(serviceKey,'PATCH',`/rest/v1/annual_leave_adjustments?id=eq.${adjustmentRace[0].payload.adjustment_id}`,{reason:'Changed'})).status>=400&&(await request(serviceKey,'DELETE',`/rest/v1/annual_leave_adjustments?id=eq.${adjustmentRace[0].payload.adjustment_id}`)).status>=400);
 check('MANAGER_READ_ALLOWED',(await request(owner.token,'GET',`/rest/v1/annual_leave_accounts?workspace_id=eq.${ws}&select=id`)).rows.length===1);check('MEMBER_READ_DENIED',(await request(member.token,'GET',`/rest/v1/annual_leave_accounts?workspace_id=eq.${ws}&select=id`)).rows.length===0);check('OUTSIDER_READ_DENIED',(await request(outsider.token,'GET',`/rest/v1/annual_leave_accounts?workspace_id=eq.${ws}&select=id`)).rows.length===0);
 const before=sql(`select count(*) from public.scheduling_worker_unavailability where workspace_id='${id(ws)}';`);check('EXISTING_UNAVAILABILITY_UNCHANGED',before==='0'&&sql(`select count(*) from public.scheduling_worker_unavailability where workspace_id='${id(ws)}';`)==='0');check('NO_ABSENCE_ACCOUNTING_TABLES',sql("select count(*) from pg_catalog.pg_class where relnamespace='public'::regnamespace and relname in ('annual_leave_absences','annual_leave_segments','annual_leave_postings');")==='0');
 const failed=randomUUID(),currentVersion=Number(sql(`select version from public.annual_leave_accounts where id='${account}';`));const atomic=sql(`begin;create function pg_temp.refuse_leave_audit() returns trigger language plpgsql as $$begin raise exception 'audit refused';end$$;create trigger refuse_leave_audit before insert on public.audit_log for each row when(new.resource_type='annual_leave_adjustment')execute function pg_temp.refuse_leave_audit();do $$begin begin perform public.save_rev_annual_leave_adjustment('${id(ws)}','${id(owner.id)}','${id(failed)}','${account}',30,'Rollback proof',${currentVersion});exception when raise_exception then null;end;end$$;select case when (select version from public.annual_leave_accounts where id='${account}')=${currentVersion} and not exists(select 1 from rev_scheduling_private.annual_leave_adjustment_requests where request_id='${id(failed)}') and not exists(select 1 from public.annual_leave_adjustments where reason='Rollback proof') then 'ATOMIC_PASS' else 'ATOMIC_FAIL' end;rollback;`);check('AUDIT_FAILURE_ROLLS_BACK_ADJUSTMENT',atomic.includes('ATOMIC_PASS'));
 check('AUDIT_EXACTLY_ONCE',sql(`select count(*)=3 and count(distinct metadata->>'request_id')=3 from public.audit_log where workspace_id='${id(ws)}' and metadata->>'request_id' in ('${id(policyInput.target_request_id)}','${id(accountInput.target_request_id)}','${id(adjustmentInput.target_request_id)}');`)==='t');check('PRIVATE_REQUEST_LEDGERS_DENIED',sql("select not has_schema_privilege('service_role','rev_scheduling_private','USAGE') and not has_schema_privilege('authenticated','rev_scheduling_private','USAGE');")==='t');
}catch(error){console.error(error instanceof Error?error.message:'Stage 1 validation failed');check('ANNUAL_LEAVE_STAGE1_VALIDATION',false);}finally{await retire();}
console.log('EXTERNAL_PROVIDER_REQUESTS=0');check('ANNUAL_LEAVE_STAGE1_LOCAL',failures===0);if(failures)process.exitCode=1;