import test from 'node:test';
import assert from 'node:assert/strict';
import { captureCalendarOAuthReturn, startCalendarOAuth, completeCalendarOAuth } from '../services/calendarOAuthBrowser.ts';
const workspaceId='fdce6c53-d1cb-48bc-b35a-7f57674d80f6',userId='baf67b40-2fdf-4496-9c1d-1ac1aa5e9892',state='s'.repeat(43),now=1000000;
function storage(){const map=new Map();return{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k),values:()=>[...map.values()]};}
function fake(){const calls=[];return{calls,invoke:async(name,body)=>{calls.push({name,body});if(name==='rev-calendar-connection-create')return{connectionId:body.requestId,connectionStatus:'disconnected'};if(name==='rev-calendar-oauth-start'){const u=new URL('https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize');u.search=new URLSearchParams({client_id:userId,state,response_type:'code',code_challenge_method:'S256',code_challenge:'c'.repeat(43),scope:'offline_access https://graph.microsoft.com/Calendars.Read',redirect_uri:'http://127.0.0.1:5180/calendar/outlook/callback'}).toString();return{authorizationUrl:u.href};}return{status:'authorization_saved',connectionId:body.connectionId,connectionStatus:'disconnected'};}};}
test('Outlook callback is captured and URL scrubbed; ordinary REV auth URLs are untouched',()=>{const replaced=[];assert.deepEqual(captureCalendarOAuthReturn({pathname:'/calendar/outlook/callback',search:`?code=fake-code&state=${state}`},u=>replaced.push(u)),{code:'fake-code',state,failed:false});assert.deepEqual(replaced,['/calendar/outlook/callback']);assert.equal(captureCalendarOAuthReturn({pathname:'/',search:'?code=rev-login'},()=>assert.fail()),null);assert.equal(captureCalendarOAuthReturn({pathname:'/calendar/outlook/callback',search:'?error=denied'},()=>{}).failed,true);});
test('create precedes start; exact bodies and actor-bound pending metadata are saved',async()=>{const s=storage(),f=fake();await startCalendarOAuth(workspaceId,userId,s,f.invoke,now);assert.deepEqual(f.calls.map(c=>c.name),['rev-calendar-connection-create','rev-calendar-oauth-start']);assert.deepEqual(Object.keys(f.calls[0].body).sort(),['requestId','workspaceId']);const pending=JSON.parse(s.values()[0]);assert.equal(pending.userId,userId);assert.equal(pending.state,state);assert.ok(!s.values()[0].includes('fake-code'));});
test('creation retry reuses request ID after interrupted start',async()=>{const s=storage(),f=fake();const broken=async(name,body)=>{if(name==='rev-calendar-oauth-start')throw new Error('interrupted');return f.invoke(name,body);};await assert.rejects(startCalendarOAuth(workspaceId,userId,s,broken,now));await startCalendarOAuth(workspaceId,userId,s,f.invoke,now+1);assert.equal(f.calls[0].body.requestId,f.calls[1].body.requestId);});
test('unexpected response and external authorization redirect fail closed',async()=>{for(const response of [{authorizationUrl:'https://evil.test/authorize'},{authorizationUrl:'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize'}, {authorizationUrl:'https://evil.test',refresh_token:'injected'}]){const s=storage();await assert.rejects(startCalendarOAuth(workspaceId,userId,s,async(name,body)=>name==='rev-calendar-connection-create'?{connectionId:body.requestId,connectionStatus:'disconnected'}:response,now));}});
test('matching callback remains bound to its original workspace and connection; replay is denied',async()=>{const s=storage(),f=fake();await startCalendarOAuth(workspaceId,userId,s,f.invoke,now);const pending=JSON.parse(s.values()[0]);await completeCalendarOAuth({code:'fake-code',state,failed:false},userId,s,f.invoke,now+1);assert.deepEqual(f.calls[2],{name:'rev-calendar-oauth-complete',body:{workspaceId:pending.workspaceId,connectionId:pending.connectionId,state,code:'fake-code'}});assert.deepEqual(s.values(),[]);await assert.rejects(completeCalendarOAuth({code:'fake-code',state,failed:false},userId,s,f.invoke,now+2));assert.equal(f.calls.length,3);});
test('wrong user, wrong state, denial and expired pending state never invoke completion',async()=>{for(const variant of ['user','state','denial','expiry']){const s=storage(),f=fake();await startCalendarOAuth(workspaceId,userId,s,f.invoke,now);await assert.rejects(completeCalendarOAuth({code:'fake-code',state:variant==='state'?'x'.repeat(43):state,failed:variant==='denial'},variant==='user'?workspaceId:userId,s,f.invoke,variant==='expiry'?now+600000:now+1));assert.equal(f.calls.length,2);}});
test('uncertain completion removes pending state and prevents automatic retry',async()=>{const s=storage(),f=fake();await startCalendarOAuth(workspaceId,userId,s,f.invoke,now);let calls=0;const fail=async()=>{calls++;throw new Error('timeout');};await assert.rejects(completeCalendarOAuth({code:'fake-code',state,failed:false},userId,s,fail,now+1));await assert.rejects(completeCalendarOAuth({code:'fake-code',state,failed:false},userId,s,fail,now+2));assert.equal(calls,1);});
