import test from 'node:test';
import assert from 'node:assert/strict';
import {requestCalendarSelection,loadCalendarConnectionMetadata} from '../services/calendarConnectionMetadata.ts';
const workspaceId='fdce6c53-d1cb-48bc-b35a-7f57674d80f6',calendarId='4d2b4b34-9f79-496b-82b0-663e71cd3b5a',connectionId='baf67b40-2fdf-4496-9c1d-1ac1aa5e9892';
test('selection sends only workspace and calendar IDs',async()=>{let calls=0;await requestCalendarSelection(workspaceId,calendarId,connectionId,async(name,body)=>{calls++;assert.equal(name,'rev-calendar-select');assert.deepEqual(body,{workspaceId,calendarId});return{calendarId,connectionId,selected:true};});assert.equal(calls,1);});
test('invalid identifiers stop before invocation',async()=>{for(const args of [['bad',calendarId,connectionId],[workspaceId,'bad',connectionId],[workspaceId,calendarId,'bad']]){let calls=0;await assert.rejects(requestCalendarSelection(...args,async()=>{calls++;}));assert.equal(calls,0);}});
test('mismatched calendar, connection, selection and unexpected fields fail closed',async()=>{for(const result of [{calendarId:workspaceId,connectionId,selected:true},{calendarId,connectionId:workspaceId,selected:true},{calendarId,connectionId,selected:false},{calendarId,connectionId,selected:true,refreshToken:'unexpected'},null])await assert.rejects(requestCalendarSelection(workspaceId,calendarId,connectionId,async()=>result));});
test('endpoint failure is not automatically retried',async()=>{let calls=0;await assert.rejects(requestCalendarSelection(workspaceId,calendarId,connectionId,async()=>{calls++;throw new Error('timeout');}));assert.equal(calls,1);});
test('saved selection reconstructs on a fresh metadata load',async()=>{const read=async table=>table==='workspace_calendar_connections'?[{id:connectionId,connection_status:'connected',provider_account_reference:'owner@example.test',authorized_by_user_id:workspaceId}]:[{id:calendarId,connection_id:connectionId,display_name:'Calendar',timezone:'Europe/London',is_selected:true,active:true}];const result=await loadCalendarConnectionMetadata(workspaceId,read);assert.equal(result.calendars[0].selected,true);assert.equal(result.calendars[0].id,calendarId);});
