import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {loadSchedulingWorkers,submitWorkerAttempt,workerColumns,rememberWorkerAttempt,restoreWorkerAttempt,clearWorkerAttempt} from '../services/schedulingWorkers.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444';
const input={workspaceId:ws,requestId,workerId:null,displayName:'Test Worker',roleLabels:['Support','Admin'],skillTags:[],active:true,expectedVersion:0};
const result={workspaceId:ws,workerId:worker,displayName:'Test Worker',roleLabels:['Admin','Support'],skillTags:[],active:true,version:1};
const row={workspace_id:ws,id:worker,display_name:'Test Worker',role_labels:['Admin','Support'],skill_tags:[],active:true,version:1};
function storage(){const values=new Map();return{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};}
test('worker list requests only display fields within exact workspace',async()=>{const calls=[];assert.deepEqual(await loadSchedulingWorkers(ws,async(...args)=>{calls.push(args);return[row];}),[result]);assert.deepEqual(calls,[[workerColumns,ws]]);});
test('foreign, duplicate and malformed worker rows refuse partial lists',async()=>{for(const rows of [[{...row,workspace_id:actor}],[row,row],[{...row,active:'yes'}],[{...row,version:0}],[{...row,role_labels:['Admin','Admin']}],[{...row,private:'unexpected'}]])await assert.rejects(loadSchedulingWorkers(ws,async()=>rows));});
test('save forwards canonical fields and stable request exactly once',async()=>{const calls=[];assert.deepEqual(await submitWorkerAttempt(input,async(...args)=>{calls.push(args);return result;}),result);assert.deepEqual(calls,[['rev-worker-save',{...input,roleLabels:['Admin','Support']}]]);});
test('invalid worker input stops before endpoint invocation',async()=>{for(const patch of [{displayName:''},{requestId:'bad'},{skillTags:['']},{roleLabels:['Admin','Admin']},{expectedVersion:1},{workerId:worker,expectedVersion:0}]){let count=0;await assert.rejects(submitWorkerAttempt({...input,...patch},async()=>{count++;}));assert.equal(count,0);}});
test('mismatched and unsafe responses cannot confirm a save',async()=>{for(const patch of [{workspaceId:actor},{version:9},{active:false},{skillTags:['Other']},{private:'secret'}])await assert.rejects(submitWorkerAttempt(input,async()=>({...result,...patch})));});
test('pending request survives reload and is scoped to business and signed-in manager',()=>{const s=storage();rememberWorkerAttempt(s,actor,input);assert.deepEqual(restoreWorkerAttempt(s,ws,actor),{...input,roleLabels:['Admin','Support']});assert.equal(restoreWorkerAttempt(s,actor,actor),null);assert.equal(restoreWorkerAttempt(s,ws,worker),null);clearWorkerAttempt(s,ws,actor);assert.equal(restoreWorkerAttempt(s,ws,actor),null);});
test('uncertain save retains identical request for explicit retry without automatic retry',async()=>{const s=storage();rememberWorkerAttempt(s,actor,input);let calls=0;const invoke=async()=>{calls++;throw new Error('uncertain');};await assert.rejects(submitWorkerAttempt(restoreWorkerAttempt(s,ws,actor),invoke));assert.equal(calls,1);assert.equal(restoreWorkerAttempt(s,ws,actor).requestId,requestId);});
test('invalid or cross-workspace pending data fails closed',()=>{const s=storage();const key=`rev-worker-save:${ws}:${actor}`;s.setItem(key,JSON.stringify({...input,workspaceId:actor}));assert.throws(()=>restoreWorkerAttempt(s,ws,actor));s.setItem(key,'bad json');assert.throws(()=>restoreWorkerAttempt(s,ws,actor));});
test('manager role gate precedes list read; pending request blocks editing and repeat-clicks',()=>{const source=readFileSync(new URL('../components/SchedulingModule.tsx',import.meta.url),'utf8');assert.match(source,/data\?\.status!=='active'\|\|!\['owner','admin'\]\.includes/);assert.match(source,/locked.current\|\|access!=='allowed'/);assert.match(source,/disabled=\{busy\|\|!!pending/);assert.match(source,/RETRY SAME SAVE/);assert.match(source,/mounted.current=false/);});
