import test from 'node:test';
import assert from 'node:assert/strict';
import {handleWorkerPatternSave,WorkerPatternRefusal,type WorkerPatternDependencies} from './workerPatternSaveBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',pattern='55555555-5555-4555-8555-555555555555',origin='http://localhost:5180';
const body={workspaceId:ws,workerId:worker,requestId,timezone:'Europe/London',workingDays:[5,1],startLocal:'09:00',endLocal:'17:00',effectiveFrom:'2026-10-01',effectiveUntil:null,expectedVersion:0};
const req=(value:unknown=body,headers:Record<string,string>={},method='POST')=>new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(value)}:{})});
function fixture(){const calls:unknown[]=[];const deps:WorkerPatternDependencies={allowedOrigin:origin,getUserId:async()=>actor,canManage:async()=>true,save:async(input)=>{calls.push(input);return{pattern_id:pattern,workspace_id:input.target_workspace_id,worker_id:input.target_worker_id,timezone:input.target_timezone,working_days:input.target_working_days,start_local:input.target_start_local,end_local:input.target_end_local,effective_from:input.target_effective_from,effective_until:input.target_effective_until,version:input.expected_version+1,private:'never expose'};}};return{calls,deps};}
test('verified actor and stable request reach exact worker RPC; sanitized no-store result returns',async()=>{const f=fixture();const r=await handleWorkerPatternSave(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.deepEqual(f.calls,[{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_worker_id:worker,target_timezone:'Europe/London',target_working_days:[1,5],target_start_local:'09:00',target_end_local:'17:00',target_effective_from:'2026-10-01',target_effective_until:null,expected_version:0}]);assert.deepEqual(await r.json(),{patternId:pattern,workspaceId:ws,workerId:worker,timezone:'Europe/London',workingDays:[1,5],startLocal:'09:00',endLocal:'17:00',effectiveFrom:'2026-10-01',effectiveUntil:null,version:1});});
test('invalid days, times, calendar dates, IDs and injected actor stop before writes',async()=>{for(const patch of [{userId:actor},{workerId:'bad'},{workingDays:[]},{workingDays:[1,1]},{workingDays:[8]},{timezone:'Wrong/Zone'},{startLocal:'9:00'},{endLocal:'08:00'},{effectiveFrom:'2026-02-30'},{effectiveUntil:'2026-09-30'},{effectiveUntil:'infinity'},{expectedVersion:-1},{expectedVersion:1.5}]){const f=fixture();assert.equal((await handleWorkerPatternSave(req({...body,...patch}),f.deps)).status,400);assert.deepEqual(f.calls,[]);}});
test('origin, method, bearer and content type refuse writes',async()=>{for(const r of [req(body,{Origin:'https://wrong.test'}),req(body,{},'GET'),req(body,{Authorization:''}),req(body,{'Content-Type':'text/plain'})]){const f=fixture();assert.ok((await handleWorkerPatternSave(r,f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('invalid session and denied management role refuse writes',async()=>{for(const mode of ['auth','role']){const f=fixture();if(mode==='auth')f.deps.getUserId=async()=>null;else f.deps.canManage=async()=>false;assert.ok((await handleWorkerPatternSave(req(),f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('preflight includes Supabase headers without invoking auth or save',async()=>{const f=fixture();f.deps.getUserId=async()=>{throw new Error('unreachable');};const r=await handleWorkerPatternSave(req(body,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers')??'',/x-client-info/);assert.deepEqual(f.calls,[]);});
test('existing revision advances once and inclusive end date is preserved',async()=>{const f=fixture();const r=await handleWorkerPatternSave(req({...body,expectedVersion:3,effectiveUntil:'2026-12-31'}),f.deps);assert.equal(r.status,200);assert.equal((await r.json()).version,4);assert.equal(f.calls.length,1);});
test('allowlisted assignment conflict returns a scoped definitive refusal',async()=>{const f=fixture();f.deps.save=async()=>{throw new WorkerPatternRefusal('assignment_conflict');};const r=await handleWorkerPatternSave(req(),f.deps);assert.equal(r.status,409);assert.deepEqual(await r.json(),{status:'refused',code:'assignment_conflict',requestId});});
test('RPC refusal or mismatched result refuses success without private errors or retries',async()=>{for(const mode of ['refused','worker','workspace','version','days','date']){const f=fixture();const original=f.deps.save;let calls=0;f.deps.save=async(input)=>{calls++;if(mode==='refused')throw new Error('private error');const row=await original(input) as Record<string,unknown>;if(mode==='worker')row.worker_id=actor;if(mode==='workspace')row.workspace_id=actor;if(mode==='version')row.version=100;if(mode==='days')row.working_days=[2];if(mode==='date')row.effective_until='2026-12-31';return row;};const r=await handleWorkerPatternSave(req(),f.deps);assert.equal(r.status,403);assert.equal(calls,1);assert.deepEqual(await r.json(),{error:'Working pattern could not be saved.'});}});
test('local development preflights echo the exact accepted origin without authentication or authority',async()=>{for(const local of ['http://localhost:5180','http://127.0.0.1:5180']){const f=fixture();let auth=0,roles=0;f.deps.getUserId=async()=>{auth++;return actor;};f.deps.canManage=async()=>{roles++;return true;};const r=await handleWorkerPatternSave(req(undefined,{Origin:local},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),local);assert.equal(r.headers.get('Vary'),'Origin');assert.deepEqual({auth,roles},{auth:0,roles:0});assert.deepEqual(f.calls,[]);}});
test('missing, unrelated and wrong-port origins are refused before authority calls',async()=>{for(const headers of [{Origin:''},{Origin:'https://foreign.test'},{Origin:'http://127.0.0.1:5181'},{Origin:'http://localhost'}]){for(const method of ['OPTIONS','POST']){const f=fixture();let auth=0,roles=0;f.deps.getUserId=async()=>{auth++;return actor;};f.deps.canManage=async()=>{roles++;return true;};const r=await handleWorkerPatternSave(req(body,headers,method),f.deps);assert.equal(r.status,403);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);assert.deepEqual({auth,roles},{auth:0,roles:0});assert.deepEqual(f.calls,[]);}}const f=fixture();const r=await handleWorkerPatternSave(req(undefined,{},'OPTIONS'),{...f.deps,allowedOrigin:undefined});assert.equal(r.status,403);});
test('production origin restriction stays exact',async()=>{const production='https://app.revive.example';for(const other of ['http://localhost:5180','http://127.0.0.1:5180','https://foreign.test']){const f=fixture();let auth=0;f.deps.getUserId=async()=>{auth++;return actor;};const r=await handleWorkerPatternSave(req(undefined,{Origin:other},'OPTIONS'),{...f.deps,allowedOrigin:production});assert.equal(r.status,403);assert.equal(auth,0);}const f=fixture();const r=await handleWorkerPatternSave(req(undefined,{Origin:production},'OPTIONS'),{...f.deps,allowedOrigin:production});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),production);});
