import test from 'node:test';
import assert from 'node:assert/strict';
import {handleSchedulingJobSave,JobSaveRefusal,jobSaveRefusalFor,type JobDependencies,type JobInput} from './schedulingJobBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',job='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444';
const origin='http://localhost:5180';
const body={workspaceId:ws,requestId,jobId:null as string|null,title:'Support shift',startAt:'2026-10-08T09:00:00.000Z',endAt:'2026-10-08T12:00:00.000Z',timezone:'Europe/London',location:'Birmingham office',requiredSkills:['Phone','Admin'],staffingCount:2,status:'open',expectedVersion:0};
function req(value:unknown=body,headers:Record<string,string>={},method='POST'){return new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer verified','Content-Type':'application/json',...headers},body:['OPTIONS','GET'].includes(method)?undefined:JSON.stringify(value)});}
function fixture(){const calls:JobInput[]=[];let auth=0,roles=0;const deps:JobDependencies={allowedOrigin:origin,getUserId:async()=>{auth++;return actor;},canManage:async()=>{roles++;return true;},save:async input=>{calls.push(input);return {job_id:input.target_job_id??job,workspace_id:input.target_workspace_id,title:input.target_title,start_at:input.target_start_at.replace('.000Z','+00:00'),end_at:input.target_end_at,timezone:input.target_timezone,location:input.target_location,required_skills:input.target_required_skills,staffing_count:input.target_staffing_count,status:input.target_status,version:input.expected_version+1,private_token:'never return'};}};return {deps,calls,counts:()=>({auth,roles})};}
test('verified manager forwards canonical requirements and returns sanitized no-store job',async()=>{const f=fixture(),r=await handleSchedulingJobSave(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(f.calls.length,1);assert.equal(f.calls[0].initiating_user_id,actor);assert.deepEqual(f.calls[0].target_required_skills,['Admin','Phone']);assert.deepEqual(await r.json(),{jobId:job,workspaceId:ws,title:body.title,startAt:body.startAt,endAt:body.endAt,timezone:body.timezone,location:body.location,requiredSkills:['Admin','Phone'],staffingCount:2,status:'open',version:1});});
test('invalid fields, injected actor and invalid creation states stop before auth or writes',async()=>{for(const patch of [{actorUserId:actor},{title:''},{title:' padded '},{title:'x'.repeat(161)},{location:''},{timezone:'bad/zone'},{endAt:body.startAt},{startAt:'2026-02-30T09:00:00.000Z'},{requiredSkills:['Admin','Admin']},{requiredSkills:[null]},{staffingCount:0},{staffingCount:1.5},{staffingCount:101},{status:'cancelled'},{expectedVersion:1},{jobId:job},{expectedVersion:Number.MAX_SAFE_INTEGER}]){const f=fixture(),r=await handleSchedulingJobSave(req({...body,...patch}),f.deps);assert.equal(r.status,400);assert.equal(f.calls.length,0);assert.equal(f.counts().auth,0);}});
test('origin, method, bearer and content type refuse service writes',async()=>{for(const r of [req(body,{Origin:'https://foreign.test'}),req(body,{},'GET'),req(body,{Authorization:''}),req(body,{'Content-Type':'text/plain'})]){const f=fixture();assert.ok((await handleSchedulingJobSave(r,f.deps)).status>=400);assert.equal(f.calls.length,0);}});
test('invalid session and denied management role never save',async()=>{for(const patch of [{getUserId:async()=>null},{canManage:async()=>false}]){const f=fixture();assert.ok((await handleSchedulingJobSave(req(),{...f.deps,...patch})).status>=400);assert.equal(f.calls.length,0);}});
test('preflight permits Supabase headers without authentication or save',async()=>{const f=fixture(),r=await handleSchedulingJobSave(req(undefined,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.ok(r.headers.get('Access-Control-Allow-Headers')?.includes('x-client-info'));assert.deepEqual(f.counts(),{auth:0,roles:0});assert.equal(f.calls.length,0);});
test('local development preflights echo the exact accepted origin without authority calls',async()=>{for(const local of ['http://localhost:5180','http://127.0.0.1:5180']){const f=fixture(),r=await handleSchedulingJobSave(req(undefined,{Origin:local},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),local);assert.equal(r.headers.get('Vary'),'Origin');assert.deepEqual(f.counts(),{auth:0,roles:0});assert.equal(f.calls.length,0);}});
test('missing, unrelated and wrong-port origins are refused before authority calls',async()=>{for(const headers of [{Origin:''},{Origin:'https://foreign.test'},{Origin:'http://127.0.0.1:5181'},{Origin:'http://localhost'}]){for(const method of ['OPTIONS','POST']){const f=fixture(),r=await handleSchedulingJobSave(req(body,headers,method),f.deps);assert.equal(r.status,403);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);assert.deepEqual(f.counts(),{auth:0,roles:0});assert.equal(f.calls.length,0);}}const f=fixture(),r=await handleSchedulingJobSave(req(undefined,{},'OPTIONS'),{...f.deps,allowedOrigin:undefined});assert.equal(r.status,403);assert.deepEqual(f.counts(),{auth:0,roles:0});});
test('production origin restriction stays exact',async()=>{const production='https://app.revive.example';for(const local of ['http://localhost:5180','http://127.0.0.1:5180','https://foreign.test']){const f=fixture(),r=await handleSchedulingJobSave(req(undefined,{Origin:local},'OPTIONS'),{...f.deps,allowedOrigin:production});assert.equal(r.status,403);assert.deepEqual(f.counts(),{auth:0,roles:0});}const f=fixture(),deps={...f.deps,allowedOrigin:production};const pre=await handleSchedulingJobSave(req(undefined,{Origin:production},'OPTIONS'),deps);assert.equal(pre.status,204);assert.equal(pre.headers.get('Access-Control-Allow-Origin'),production);const post=await handleSchedulingJobSave(req(body,{Origin:production}),deps);assert.equal(post.status,200);assert.equal(post.headers.get('Access-Control-Allow-Origin'),production);});
test('update and cancellation forward existing ID and expected version',async()=>{for(const status of ['open','cancelled']){const f=fixture(),r=await handleSchedulingJobSave(req({...body,jobId:job,expectedVersion:2,status}),f.deps);assert.equal(r.status,200);assert.equal(f.calls[0].target_job_id,job);assert.equal(f.calls[0].expected_version,2);assert.equal((await r.json()).version,3);}});
test('RPC refusal and mismatched results refuse success without private errors or retry',async()=>{for(const field of ['workspace_id','title','timezone','location','required_skills','staffing_count','status','version','job_id','start_at']){const f=fixture(),save=f.deps.save;f.deps.save=async input=>({...await save(input) as object,[field]:'wrong'});const r=await handleSchedulingJobSave(req(),f.deps);assert.equal(r.status,403);assert.equal(f.calls.length,1);assert.ok(!(await r.text()).includes('private'));}let count=0;const f=fixture();f.deps.save=async()=>{count++;throw Error('private DB error');};const r=await handleSchedulingJobSave(req(),f.deps);assert.equal(r.status,403);assert.equal(count,1);assert.ok(!(await r.text()).includes('private'));});
test('cancelling a job with active assignments returns a request-bound refusal once, without retry or private detail',async()=>{const f=fixture();let calls=0;f.deps.save=async()=>{calls++;throw new JobSaveRefusal('active_assignments');};const r=await handleSchedulingJobSave(req({...body,jobId:job,expectedVersion:3,status:'cancelled'}),f.deps);assert.equal(r.status,409);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(calls,1);assert.deepEqual(await r.json(),{status:'refused',code:'active_assignments',requestId});});
test('other database failures stay unconfirmed rather than becoming a refusal',async()=>{for(const failure of [Error('Cancel affected assignments before changing job'),Error('Job unavailable or changed'),Error('Job unavailable')]){const f=fixture();f.deps.save=async()=>{throw failure;};const r=await handleSchedulingJobSave(req({...body,jobId:job,expectedVersion:3,status:'cancelled'}),f.deps);assert.equal(r.status,403);assert.ok(!(await r.text()).includes('refused'));}});
test('database refusal mapping requires SQLSTATE P0001 and the exact guard message',()=>{const message='Cancel affected assignments before changing job';const mapped=jobSaveRefusalFor({code:'P0001',message,details:null,hint:null});assert.ok(mapped instanceof JobSaveRefusal);assert.equal(mapped.code,'active_assignments');for(const error of [{code:'P0002',message},{code:'23514',message},{code:'',message},{message},{code:'P0001',message:message+'.'},{code:'P0001',message:' '+message},{code:'P0001',message:'cancel affected assignments before changing job'},{code:'P0001',message:'Job unavailable or changed'},{code:'P0001',message:'Cancel affected assignments before changing worker'},{code:'P0001'},null,undefined,message,Error(message)])assert.equal(jobSaveRefusalFor(error),null);});
