import test from 'node:test';
import assert from 'node:assert/strict';
import {handleWorkerSave,type WorkerSaveDependencies} from './workerSaveBoundary.ts';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',worker='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',origin='http://localhost:5180';
const body={workspaceId:ws,requestId,workerId:null,displayName:'Mike Test',roleLabels:['Support','Admin'],skillTags:['Phone'],active:true,expectedVersion:0};
const req=(value:unknown=body,headers:Record<string,string>={},method='POST')=>new Request('https://example.test',{method,headers:{Origin:origin,Authorization:'Bearer fake','Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(value)}:{})});
function fixture(){const calls:unknown[]=[];const deps:WorkerSaveDependencies={allowedOrigin:origin,getUserId:async()=>actor,canManage:async()=>true,save:async(input)=>{calls.push(input);return{worker_id:input.target_worker_id??worker,workspace_id:input.target_workspace_id,display_name:input.target_display_name,role_labels:input.target_role_labels,skill_tags:input.target_skill_tags,active:input.target_active,version:input.expected_version+1,internal_detail:'never expose'};}};return{calls,deps};}
test('verified actor, stable request and canonical fields reach RPC; only safe metadata returns',async()=>{const f=fixture();const r=await handleWorkerSave(req(),f.deps);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.deepEqual(f.calls,[{target_workspace_id:ws,initiating_user_id:actor,target_request_id:requestId,target_worker_id:null,target_display_name:'Mike Test',target_role_labels:['Admin','Support'],target_skill_tags:['Phone'],target_active:true,expected_version:0}]);assert.deepEqual(await r.json(),{workerId:worker,workspaceId:ws,displayName:'Mike Test',roleLabels:['Admin','Support'],skillTags:['Phone'],active:true,version:1});});
test('injected actor, invalid IDs, fields and versions stop before writes',async()=>{for(const change of [{userId:actor},{workspaceId:123},{requestId:'bad'},{workerId:'bad'},{displayName:''},{displayName:' padded '},{displayName:'a'.repeat(121)},{roleLabels:[null]},{skillTags:['Phone','Phone']},{skillTags:['']},{active:'true'},{expectedVersion:1},{expectedVersion:1.5},{expectedVersion:Number.MAX_SAFE_INTEGER},{workerId:worker,expectedVersion:0}]){const f=fixture();assert.equal((await handleWorkerSave(req({...body,...change}),f.deps)).status,400);assert.deepEqual(f.calls,[]);}});
test('origin, method, bearer and content type stop service writes',async()=>{for(const r of [req(body,{Origin:'https://wrong.test'}),req(body,{},'GET'),req(body,{Authorization:''}),req(body,{'Content-Type':'text/plain'})]){const f=fixture();assert.ok((await handleWorkerSave(r,f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('unverified session and denied management role never invoke save',async()=>{for(const mode of ['auth','role']){const f=fixture();if(mode==='auth')f.deps.getUserId=async()=>null;else f.deps.canManage=async()=>false;assert.ok((await handleWorkerSave(req(),f.deps)).status>=400);assert.deepEqual(f.calls,[]);}});
test('preflight permits Supabase headers and never invokes auth or save',async()=>{const f=fixture();f.deps.getUserId=async()=>{throw new Error('unreachable');};const r=await handleWorkerSave(req(body,{},'OPTIONS'),f.deps);assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers')??'',/x-client-info/);assert.deepEqual(f.calls,[]);});
test('existing worker update preserves ID and advances expected version',async()=>{const f=fixture();const r=await handleWorkerSave(req({...body,workerId:worker,expectedVersion:3,active:false}),f.deps);assert.equal(r.status,200);assert.equal((await r.json()).version,4);assert.equal(f.calls.length,1);});
test('RPC refusal or mismatched result fails closed without retry or private error',async()=>{for(const mode of ['refused','worker','workspace','version','tags','name','active']){const f=fixture();const original=f.deps.save;let calls=0;f.deps.save=async(input)=>{calls++;if(mode==='refused')throw new Error('private error');const row=await original(input) as Record<string,unknown>;if(mode==='worker')row.worker_id=actor;if(mode==='workspace')row.workspace_id=actor;if(mode==='version')row.version=100;if(mode==='tags')row.skill_tags=['Different'];if(mode==='name')row.display_name='Other';if(mode==='active')row.active=false;return row;};const r=await handleWorkerSave(req({...body,workerId:worker,expectedVersion:1}),f.deps);assert.equal(r.status,403);assert.equal(calls,1);assert.deepEqual(await r.json(),{error:'Worker could not be saved.'});}});
